### ISSUE TITLE
Vicky PKGBUILD doesn't need install instructions ...

### ISSUE THREAD

**Issue by filipe-marques** [manjaro/packages-community#10]
Vicky PKGBUILD doesn't need install instructions like these:
install -Dm755 "Vicky" "${pkgdir}/usr/bin/vicky"
install -Dm644 "vicky.desktop" "${pkgdir}/usr/share/applications/vicky.desktop"
install -Dm644 "resource/icons/vicky24.png" "${pkgdir}/usr/share/icons/vicky.png"
install -Dm644 "resource/icons/vicky24.png" "${pkgdir}/usr/share/icons/hicolor/24x24/apps/vicky.png"
install -Dm644 "resource/icons/vicky128.png" "${pkgdir}/usr/share/icons/hicolor/128x128/apps/vicky.png"
install -Dm644 "LICENSE" "${pkgdir}/usr/share/licenses/vicky/LICENSE"

It already have it in vicky.pro file install instructions (of qmake) and then when make is executed it will be there in makefile to be installed by make install

**Comment by Kirek** [comment]
Your .pro has wrong paths
for example:
desk.path = /usr/share/applications/vicky.desktop
should be
desk.path = /usr/share/applications

same for all the other paths
