### ISSUE TITLE
Is wrong enable by default whit pkg the gnome-exstension?

### ISSUE THREAD

**Issue by Ste74** [manjaro/packages-community#132]
I can do in .install this instruction by default ?
glib-compile-schemas usr/share/glib-2.0/schemas/
I don't understand why the key [org.gnome.shell] enable exstension in the desktop settings do me an error

**Comment by Kirek** [comment]
yes, many packages do that
https://wiki.archlinux.org/index.php/GNOME_package_guidelines#GSettings_schemas

**Comment by Ste74** [comment]
Continue here 
https://forum.manjaro.org/index.php?topic=31971.0
