### ISSUE TITLE
Mygtkmenui seems to be corrupt

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/packages-community#133]
That or there is something wrong with Stefanos signature.

**Comment by Ste74** [comment]
What version ? 32 or 64 bit ? other pkg committed are ok ? ( limepanel etc ) ? Yesterday i have trouble whit this pkg .. if other working is not problem on signature .. recompile the pkg local whit last pkgbuild committed from me and if no problem there , i can rebuild

**Comment by Kirek** [comment]
Can confirm here, mygtkmenui has a bad signature, limepanel is fine.
Maybe you rebuilt the package and didn't update the signature? Also remember to increase the pkgrel when you do a rebuild.

**Comment by Ste74** [comment]
Ok,sorry, rebuild and up the rel.
Il 10/mar/2016 17:41, "Ramon Buldó" <notifications@github.com> ha scritto:

**Comment by Ste74** [comment]
@Chrysostomus Please check pushed into unstable .

**Comment by oberon2007** [comment]
@Ste74 you have to watch out: When you rebuild packages you need to remove the old signature file because ``buildpkg -s`` will not overwrite it. Or you have to perform ``signpkgs`` on the new package again. Otherwise the old .sig file will not match the new package! :stuck_out_tongue:

**Comment by Ste74** [comment]
Well.. i don`t know this tip :/ .. but now is ok the pkg?
Il 10/mar/2016 20:48, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by Kirek** [comment]
It's ok now.
