### ISSUE TITLE
virtualbox needs to be compiled against xorg 17

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-community#135]
Utils need to be compiled against Xorg 17

**Comment by Kirek** [comment]
virtualbox or virtualbox-guest-utils/virtualbox-guest-utils-nox?

**Comment by Kirek** [comment]
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160314/006388.html
https://github.com/manjaro/packages-community/commit/ab16e34ffdb0740150657ee56dd513fe450e2fbd

**Comment by philmmanjaro** [comment]
Correct.
