### ISSUE TITLE
Switch to newer Xarchivier?

### ISSUE THREAD

**Issue by mirh** [manjaro/packages-community#140]
https://github.com/ib/xarchiver
instead of http://xarchiver.sourceforge.net/
If any, at least because it's still being maintained. 

Also I wonder: why that's available in official [community] repositories, but there's no mention here?

**Comment by Kirek** [comment]
The xarchiver package is from archlinux: https://www.archlinux.org/packages/community/x86_64/xarchiver/

**Comment by Kirek** [comment]
Maybe you want to tell them that, but note that xarchiver has a number of patches on top of it.
https://projects.archlinux.org/svntogit/community.git/tree/trunk?h=packages/xarchiver

**Comment by mirh** [comment]
Thanks, I will report.
