### ISSUE TITLE
firefox & firefox-kde

### ISSUE THREAD

**Issue by udeved** [manjaro/packages-community#148]
Something is weird with both FF packages in unstable.

FF lost theme support.

FF-kde needs rebuild against icu-57 eventually.
~~~
$ firefox
XPCOMGlueLoad error for file /usr/lib/firefox/libxul.so:
libicui18n.so.56: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
~~~

**Comment by Kirek** [comment]
I know about *-kde, it just take some time to build.

**Comment by udeved** [comment]
Yep, FF is ugly long compile time.

However, default FF lost theme support somehow.
As if theme engine is borked or something.

**Comment by Kirek** [comment]
Maybe the theme need to be updated for gtk 3.20?

**Comment by udeved** [comment]
Perhaps, yes, looks like a broken theme. I use breeze-gtk.
But it looks to me, as if the entire theme engine doesn't work.
No color highlight in menu, nothing. Is this default gtk?
some buttons seem to use proper skin, but not sure.

**Comment by udeved** [comment]
No problem with thunderbird btw.

FF spits out tons of errors when starting...

~~~
$ firefox

(firefox:3520): Gtk-WARNING **: Theme parsing error: gtk.css:34:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(firefox:3520): Gtk-WARNING **: Theme parsing error: gtk.css:44:13: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3520): Gtk-WARNING **: Theme parsing error: gtk.css:45:19: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'

(firefox:3520): Gtk-WARNING **: Theme parsing error: gtk.css:50:29: The :prelight pseudo-class is deprecated. Use :hover instead.

(firefox:3520): Gtk-WARNING **: Theme parsing error: gtk.css:56:32: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3520): Gtk-WARNING **: Theme parsing error: gtk.css:75:18: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3520): Gtk-WARNING **: Theme parsing error: gtk.css:115:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(firefox:3520): Gtk-WARNING **: Theme parsing error: gtk.css:133:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.
~~~
another felt 1000 lines follow

**Comment by FadeMind** [comment]
@udeved @Kirek 
Upstream: https://bugs.kde.org/show_bug.cgi?id=361066

Firefox working like a charm after rebuild against lastest GTK 3.20, icu and poppler.

NOTE: I use `default` GNOME 3 theme for a while.
![screenshot_20160409_191112](https://cloud.githubusercontent.com/assets/9846948/14405093/edc23bc0-fe86-11e5-9142-6e95fd99258a.png)

Thunderbird using GTK 2 engine.

**Comment by Kirek** [comment]
Do you have some chrome.css in your profile?

**Comment by udeved** [comment]
I can confirm that default Adwaita theme works, and breeze gtk doesn't.

No chrome or anything here.

**Comment by FadeMind** [comment]
@Kirek Nope.

**Comment by Kirek** [comment]
![screenshot_20160409_192517](https://cloud.githubusercontent.com/assets/3207574/14405169/e7dc0bee-fe88-11e5-90f1-84104efc176b.png)

breeze-gtk3 is completely broken

**Comment by udeved** [comment]
Yep, follow the link to kde bug tracker fademind posted.

**Comment by FadeMind** [comment]
@Kirek cause GTK3.20 using now CSS schema file.

**Comment by Kirek** [comment]
not only breeze, all but adwaita and vertex (just updated) are broken

**Comment by Kirek** [comment]
I suppose this is the 340120341872 time that gtk3 have broken all themes :)

**Comment by udeved** [comment]
I think the number is an underestimation.

**Comment by Ste74** [comment]
vertex theme maia ( the new official theme ) need changes ? cinnamon , gnome and xfce use that

**Comment by Kirek** [comment]
@Ste74 Yes, it need to be updated too.

**Comment by Ste74** [comment]
But only recompile or need changes ?

**Comment by Kirek** [comment]
Need changes.

**Comment by Ste74** [comment]
I suppose this :wink: . Need contact author @oberon2007 lol

**Comment by Ste74** [comment]
Arghh :weary: most extension is outdated...

**Comment by oberon2007** [comment]
I've tried to notify @ManjaroCinnamonFan [some days ago](https://github.com/oberon2007/vertex-maia-themes/issues/1) already - haven't heard back from him, sigh! ... I'm afraid the changes are not so trivial that one can just simply fix it, or what do you guys think? One could attempt of course to look at a diff between the original **vertex-maia** version compared to the old **vertex** and the port the changes to the new one - It would just be great if the person who knows what to do could do it again ... ... :stuck_out_tongue_winking_eye: :

**Comment by Ste74** [comment]
Do you think to another approach? Ask at the original author Horst if want
adopt it...
Il 10/apr/2016 10:03, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by philmmanjaro** [comment]
Remember to check also if **firefox-kde** and **thunderbird-kde** are needing a rebuild against the **testing** branch. I saw there also [some reports](https://forum.manjaro.org/index.php?topic=32883.msg268688#msg268688).

**Comment by Kirek** [comment]
They posted in testing but obviously he is using unstable, or he wont have any icu issues...

**Comment by philmmanjaro** [comment]
ok, I just wanted to be sure ...

**Comment by oberon2007** [comment]
https://github.com/manjaro/release-plan/issues/36#issuecomment-208088330
