### ISSUE TITLE
Should [vertex-maia-themes] be moved to extra...

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#153]
...since it becomes the official theme now?

**Comment by Kirek** [comment]
no, lets leave themes in community

**Comment by oberon2007** [comment]
What about icons? Better move **vertex-maia-icon-themes** from extra to here, then? :laughing:

**Comment by philmmanjaro** [comment]
It doesn't matter in which folder it is. However it makes sense to have icons and theme in the same :smile:
