### ISSUE TITLE
[vertex-maia-themes] rabideau's whisker menu customization

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#154]
Shall we re-introduce this? @philmmanjaro 

![whisker](https://cloud.githubusercontent.com/assets/11800714/14587032/e9efc7ae-04aa-11e6-9d05-a76ee686fbad.png)

**Comment by oberon2007** [comment]
Using this in the Dark theme only seems like a good idea, maybe?

**Comment by oberon2007** [comment]
Uhm, no. What I last said doesn't make sense, because in the dark theme it's all dark anyway :laughing: ...

**Comment by kouros17** [comment]
I think it's perfect for light version!

**Comment by Ste74** [comment]
I think i can close @oberon :wink:

**Comment by oberon2007** [comment]
:+1:
