### ISSUE TITLE
python-efl needs to been updated

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-community#156]
reported by forum PM:

> The message they sent you was:
> 
> Hi Phil,
> 
> I see you are the maintainer on this package and apologize if you have already received messages about it, but the package in the stable repository (1.15) is out of date and causes Econnman to crash. Like Palo in this message https://forum.manjaro.org/index.php?topic=32265.msg264288#msg264288, I just downloaded the pkgbuild from the AUR (for 1.17), compiled and installed it, which has brought Econnman back to life.
> 
> As chief guru I know you must have just tons of free time to compile little packages like this  ::), but when you get the chance, could you update python-efl in the repositories?
> 
> Best,
> aguador

**Comment by oberon2007** [comment]
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160418/006809.html
