### ISSUE TITLE
Vertex-maia-gtk3 is broken

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/packages-community#159]
@oberon2007 The theme does not work as intended. I think I might have made a mistake adding it, when I dod not have the know how to make it work. Sorry for wasting everybodys time. 

Should we just drop it? Or spend further time trying to fix it? I'm not sure if anyone but myself would have use for it.

**Comment by philmmanjaro** [comment]
What is the issue? You wanted to have a theme just for **gtk3** only. So we stripped everything else out of it. Post some screenshots so we can see what you mean.

**Comment by Chrysostomus** [comment]
In a minute...

**Comment by Chrysostomus** [comment]
Okay... the problem is different than I thought. It does work just fine, it is just that lxappearance does not see it.

**Comment by Chrysostomus** [comment]
I think I can live with that for the time being (while building testing isos). But in the long run it is going to need some fix. I'll try to figure out what lxappearance uses for finding themes. Does anybody have tips on where to start looking?

**Comment by oberon2007** [comment]
I'm not sure if lxappearance will work properly without gtk2 at all, but maybe it helps if you re-add at least the gtk-2.0/gtkrc to make it display the theme?

Am 24. April 2016 17:59:18 MESZ, schrieb Chrysostomus <notifications@github.com>:
>@oberon2007 The theme does not work as intended. I think I might have
>made a mistake adding it, when I dod not have the know how to make it
>work. Sorry for wasting everybodys time. 
>
>Should we just drop it? Or spend further time trying to fix it? I'm not
>sure if anyone but myself would have use for it.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/manjaro/packages-community/issues/159

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Chrysostomus** [comment]
Worth a shot. I'll try it.

**Comment by oberon2007** [comment]
I've just verified that the other way round: When i remove **gtk-2.0/gtkrc**, lxappearance loses it ;)

**Comment by oberon2007** [comment]
You are just lucky that **lxappearance** doesn't officially depend on gtk2 :wink:
I think it will not hurt to put the gtkrc files back to make it work.

**Comment by Chrysostomus** [comment]
That is probably a good idea - how does one do it? I tried fiddling around the pkgbuild, but have not yet been able to confirm what works, because building this package takes way longer than I imagined. I think it is either removing "--disable-gtk2 " argument from autogen, or adding an additional install line to put them back.

**Comment by oberon2007** [comment]
It's a bit complicated ;) I can do it a little later... :)
