### ISSUE TITLE
[steam-manjaro] steam ignores optirun

### ISSUE THREAD

**Issue by minj** [manjaro/packages-community#16]
Ever since `steam`/`steam-native` were replaced with `steam-manjaro` I can no longer run steam with optirun properly.

## Reproducing
My usual command: 
`env STEAM_RUNTIME=0 HOME=/home/user/documents/games XDG_DATA_HOME=/home/user/documents/games/.local/share XDG_CONFIG_HOME=/home/user/documents/games/.config optirun steam`
However, testing suggests that all those env vars does not matter so I get the same result with e. g. `env STEAM_RUNTIME=1 optirun steam`

### Config
**Dell Inspiron 7720**
`Linux hostname 3.18.13-1-MANJARO #1 SMP PREEMPT Sat May 16 09:35:03 UTC 2015 x86_64 GNU/LinuxLinux hostname 3.18.13-1-MANJARO #1 SMP PREEMPT Sat May 16 09:35:03 UTC 2015 x86_64 GNU/Linux`

- `mhwd-gpu --status`
```
Using default
Default lib32 support: true
:: status
  lib32-libGl: '/usr/lib32/mesa/libGL.so.1.2.0'
  lib32-libGLESv1: '/usr/lib32/mesa/libGLESv1_CM.so.1.1.0'
  lib32-libGLESv2: '/usr/lib32/mesa/libGLESv2.so.2.0.0'
  lib32-libEGL: '/usr/lib32/mesa/libEGL.so.1.0.0'
  libGl: '/usr/lib/mesa/libGL.so.1.2.0'
  libGLESv1: '/usr/lib/mesa/libGLESv1_CM.so.1.1.0'
  libGLESv2: '/usr/lib/mesa/libGLESv2.so.2.0.0'
  libEGL: '/usr/lib/mesa/libEGL.so.1.0.0'
  libglx: '/usr/lib/xorg/modules/extensions/libglx.xorg'
  xorg configuration file: '/etc/X11/mhwd.d/intel.conf'
```
- /etc/bumblebee/bumblebee.conf
```
[bumblebeed]
VirtualDisplay=:8
KeepUnusedXServer=false
ServerGroup=users
TurnCardOffAtExit=true
NoEcoModeOverride=false
Driver=nvidia
XorgConfDir=/etc/bumblebee/xorg.conf.d

[optirun]
Bridge=primus
VGLTransport=proxy
PrimusLibraryPath=/usr/lib/primus:/usr/lib32/primus
AllowFallbackToIGC=false

[driver-nvidia]
KernelDriver=nvidia
PMMethod=auto
LibraryPath=/usr/lib/nvidia:/usr/lib32/nvidia
XorgModulePath=/usr/lib/nvidia/xorg/,/usr/lib/xorg/modules
XorgConfFile=/etc/bumblebee/xorg.conf.nvidia
```
- /etc/bumblebee/xorg.conf.nvidia
```
Section "ServerLayout"
    Identifier "Layout0"
    Option "AutoAddDevices" "false"
EndSection
Section "Device"
	Identifier  "Device1"
	Driver      "nvidia"
	BusID       "PCI:1:0:0"
	VendorName "NVIDIA Corporation"
	Option "NoLogo" "true"
	Option "UseEDID" "false"
	Option "UseDisplayDevice" "none"
	Option "ConnectedMonitor" "DFP"
EndSection
```
- /etc/mkinitcpio.conf
```
MODULES="i915 bbswitch"
BINARIES=""
FILES=""
HOOKS="base udev autodetect modconf block keyboard keymap plymouth resume filesystems fsck"
```

## Results
- `steam 1.0.0.49-2` and `steam-native 1.0.0.49-8.1` (**good**)
  ![desktop 1_019](https://cloud.githubusercontent.com/assets/1035523/7899334/c896ef6e-0727-11e5-8101-de4853e2b4bb.png)
- `steam-manjaro` (**bad**)
  ![desktop 1_018](https://cloud.githubusercontent.com/assets/1035523/7899324/9c5d2742-0727-11e5-8fb1-7cba77218375.png)

**Comment by Kirek** [comment]
I can confirm that using "optirun steam" doesn't work.
I could get it working by using "optirun -b none steam" or "primusrun steam" though.

**Comment by minj** [comment]
Cannot confirm the workaround.

Same results with `primusrun`, `optirun -b primus` `optirun -b none`.
`optirun -b auto`, `optirun -b virtualgl` fails to initialize.

Perhaps something wrong with my bumblebee config?

**Comment by Kirek** [comment]
I've rechecked it and "optirun -b none steam" wasn't working that well, in the steam system information it showed the intel card...

I've made a bunch of modifications in steam-manjaro packages and uploaded new and updated lib32-* libraries.

My result so far:
with STEAM_RUNTIME=1 it works with intel card and optirun, and steam system information shows the correct information.
with STEAM_RUNTIME=0 and intel card it works, it crashed in steam system information, the systray icon doesn't work and when closing steam the console shows a crash
with STEAM_RUNTIME=0 and optirun it tries to start but crashes continously

Tomorrow I will investigate how to resolve the native runtime issues...

**Comment by Kirek** [comment]
The new steam-manjaro it's only in the unstable branch.

**Comment by minj** [comment]
Fix confirmed.
