### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by Ste74** [manjaro/packages-community#161]
@oberon2007 have you see this https://aur.archlinux.org/packages/numix-themes-archblue-git/
for update this 
https://github.com/manjaro/packages-community/tree/master/numix-themes-archblue 

:stuck_out_tongue_winking_eye:

**Comment by oberon2007** [comment]
Ah! That's brilliant! Thank you my friend! My Deepin baby is safe now! :laughing: The original **deepin-gtk-theme** has not been updated sofar :wink: but Manjaro-Deepin's default is numix-archblue :+1:

**Comment by Ste74** [comment]
My pleasure mate :wink:
