### ISSUE TITLE
Remove gtk 3.0 folder in gtk-theme-maia

### ISSUE THREAD

**Issue by Ste74** [manjaro/packages-community#162]
@Kirek , ask you because is your creation :smile: this need to rebuild and remove # 
https://github.com/manjaro/packages-community/blob/master/gtk-theme-maia/PKGBUILD#L35
and also remove gtk3 in description ?

**Comment by Ste74** [comment]
And i can't find the gnome-themes-maia pkg , the pkgbuild ..

**Comment by Kirek** [comment]
The version in the repos is pkgrel=3 and doesn't have gtk3, this will build a version with half broken gtk3, no need to do anything.
