### ISSUE TITLE
Do we keep the package firefox-gtk2?

### ISSUE THREAD

**Issue by Kirek** [manjaro/packages-community#163]
Now gtk3 in firefox is the default, any reason to keep this package around?

**Comment by philmmanjaro** [comment]
I've to check the package **firefox** once more. We created it cos of theme issues. I hope these are gone now. Did you already switched over to gtk3 on your kde package?

**Comment by Kirek** [comment]
Yes, firefox-kde has switched to gtk3 for a while.
The worst problems with the gtk3 where in the menda theme, but I solved the worst I knew https://github.com/manjaro/artwork-menda/commit/2759ebcea6504aaece63d5f71d8c9ab407a18df9
Though this matters very little because now menda is all broken...

**Comment by Chrysostomus** [comment]
I wish we had a firefox package that did not require gtk2. Even the current firefox in repos works just fine when gtk2 is removed, and version 46 should improve it further. 

The only issue I have found with gtk3 compiled firefox is as follows:
When dark gtk3 theme is enabled (gtk-application-prefer-dark-theme=1), the autosuggestions font for website names (not addresses) is difficult read doe to the dark blue color of the font. But this can be fixed on the theming level, so I don't think it is very serious issue.

**Comment by Kirek** [comment]
firefox-gtk2 removed https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160425/006958.html

**Comment by pydsigner** [comment]
Is it too late to complain about this? I can't see my scrollbars in any GTK 3 applications without switching from Boje to Adwaita, which isn't something I'm willing to do.
