### ISSUE TITLE
packages awaiting rebuild to use pacman hooks

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#167]
PKGBUILDs are adjusted. Packages whenever rebuilt from now on can be ticked.
- [x]  abiword-gtk2
- [x]  budgie-desktop
- [x]  cmst
- [x]  compiz-manjaro
- [x]  corebird
- [x]  deepin-iconthemes-manjaro
- [x]  desktop-settings
- [x]  ecrire-git
- [x]  ephoto-git
- [x]  faba-icon-theme
- [x] faenza-manjaro-netbook-icon-theme
- [x] gnome-shell-extension-dash-to-dock
- [x] gnome-shell-extension-gnomenu
- [x] gnome-shell-extension-mediaplayer
- [x] gnome-shell-extension-openweather
- [ ] gtk-theme-config
- [x] guayadeque
- [x] imagewriter
- [x] kde-servicemenus-pkg-tools
- [ ] kio-sysinfo
- [x] liri-browser
- [x] lumina-desktop
- [x] lximage-qt
- [x] menulibre
- [x] moka-icon-theme
- [x] octopi
- [x] open-fuse-iso
- [x] packagekit
- [x] palemoon-atom-bin
- [x] palemoon-bin
- [x] pkgbrowser
- [x] qpdfview
- [x] steam-manjaro
- [x] steam-native
- [x] sunflower
- [x] thunderbird-kde
- [x] tintin-alteraeon
- [x] veracrypt
- [x] virtualbox
- [x] virtualbox-guest-utils
- [x] xfwm4-manjaro-netbook

**Comment by oberon2007** [comment]
No hurry with this, I think ... I thought just to keep track what will still be missing ... :wink:

**Comment by udeved** [comment]
settings packages need one hook to rule them all for gtk compile schemas

**Comment by oberon2007** [comment]
Is [this](https://projects.archlinux.org/svntogit/packages.git/tree/trunk/glib-compile-schemes.hook?h=packages/glib2) not suficient and installed in any case?

**Comment by oberon2007** [comment]
**glib2** installs it.

**Comment by udeved** [comment]
Yeah, a file base trigger should do, so we can remove the install file calls.

**Comment by oberon2007** [comment]
That's already done! :)
commuity: https://github.com/manjaro/packages-community/pull/165
extra: https://github.com/manjaro/packages-extra/commit/7602a16b63556b545066a939451ec39005d75c7e

**Comment by oberon2007** [comment]
I wonder if some of the remaining packages are still needed at all or if one or the other can just be dropped instead of rebuilt?

**Comment by philmmanjaro** [comment]
It depends if they are still used ...

**Comment by Ste74** [comment]
i don't know others but Imagewriter and open-fuse-iso are already update for use hook :)

**Comment by oberon2007** [comment]
true ;)
