### ISSUE TITLE
why ?

### ISSUE THREAD

**Issue by ringo32** [manjaro/packages-community#169]
why use install -d  , is install -dm 755 as example way better  ? otherwise you get package conflict?
by an update

**Comment by korrode** [comment]
**install -d** just allows the creation of a series of (sub-)folders with one command, same as **mkdir -p**

755 is the default creation mode for folders anyway, so specifying it isn't required... unless you think your script is going to be run on an install with a custom dmask, or platform that doesn't use 755 as default - not much of a worry for Arch/Manjaro PKGBUILD's.

**Comment by ringo32** [comment]
dont want to bother, but some issues manjaro-xfce-settings blocks some update.... its also not wat you want... block i mean just it stopped updating so have to reinstall , mayby not so much but should not do it..

**Comment by korrode** [comment]
"blocks some update"

The actual errors you're getting would be nice.

**Comment by ringo32** [comment]
nevermind i cant find the logs anymore....
