### ISSUE TITLE
 Re: [0.8.13] Kernels, KDE Apps 15.04.2, Cinnamon 2.6, Mate 1.10

### ISSUE THREAD

**Issue by saarlo55** [manjaro/packages-community#17]
Issue with compiz08-mate>>

ode: [Select]
saarlo@saarlo-pc ~]$ sudo pacman -Syyu
[sudo] Passwort für saarlo: 
:: Synchronisiere Paketdatenbanken...
 core                     134,6 KiB   149K/s 00:01 [######################] 100%
 totem                    992,0   B  0,00B/s 00:00 [######################] 100%
 extra                   1858,6 KiB   284K/s 00:07 [######################] 100%
 community                  2,9 MiB   192K/s 00:16 [######################] 100%
 multilib                 161,5 KiB   116K/s 00:01 [######################] 100%
 pipelight                 72,3 KiB   161K/s 00:00 [######################] 100%
:: Starte vollständige Systemaktualisierung...
Warnung: liboobs: Lokale Version (3.0.0-3) ist neuer als community (3.0.0-0.3)
:: mate-media-pulseaudio durch community/mate-media ersetzen? [J/n] j
:: mate-settings-daemon-pulseaudio durch community/mate-settings-daemon ersetzen? [J/n] j
Warnung: system-tools-backends: Lokale Version (2.10.2-5) ist neuer als community (2.10.2-0.3)
Löse Abhängigkeiten auf...
Suche nach in Konflikt stehenden Paketen...
Fehler: Konnte den Vorgang nicht vorbereiten (Kann Abhängigkeiten nicht erfüllen)
:: compiz08-mate: benötigt mate-window-manager

Philm wrote to me:
@saarlo: Hmm, seems we have to rebuild this package compiz08-mate somehow. You can try this

sudo pacman -Rdd compiz08-mate
sudo pacman -Syu
sudo pacman -S compiz08-mate

If it can't be installed please do:

sudo pacman -Sdd compiz08-mate

...and fill out a bugreport.

...i had to do "sudo pacman -Sdd compiz08-mate".

LG 

saarlo55

**Comment by Kirek** [comment]
Solved with compiz08 update https://github.com/manjaro/packages-community/commit/64f15990a03640f86e30441b5356a24d14d3db77
