### ISSUE TITLE
[bumblebee] New proper way for unloading nvidia modules via libkmod2 usage

### ISSUE THREAD

**Issue by FadeMind** [manjaro/packages-community#175]
Patching directly 3.2.1 sources failed build in optirun making, so I forked fork https://github.com/JOndra91/Bumblebee and added patches https://github.com/FadeMind/Bumblebee/commit/bf5960e62088921b38ee2b914e02e6d0e58179ef for https://github.com/Bumblebee-Project/Bumblebee/issues/573 and muting bblogger.

I following official `install` file from Arch against systemd freak out and hangs during reloading services (but IDK why this happened). 

https://github.com/FadeMind/archpkgbuilds/tree/master/AUR/nvidia-optimus/bumblebee

Loading and unloading NVIDIA module working fine.
PKGBUILD need additional depend 'kmod'

@philmmanjaro I will not pull changes directly on `packages-community` stage now. I want just talk first about this here. 

Main thead pull with libkmod2: https://github.com/Bumblebee-Project/Bumblebee/pull/762

**Comment by Ste74** [comment]
@FadeMind can close via cc54c8f077861acbca628e5389f7093b93ab5ad5 ?

**Comment by FadeMind** [comment]
@Ste74 yep.
