### ISSUE TITLE
Steam will not start after install of steam-manjaro

### ISSUE THREAD

**Issue by paven** [manjaro/packages-community#177]
Running Steam on manjarolinux 15.12 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1461972496)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

is this missing dependencies?

**Comment by Ste74** [comment]
@paven Waiting upstream correction you can ovverride the .desktop launcher for steam and add this : 

`env LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' /usr/bin/steam %U`

for reference see here https://forum.manjaro.org/t/steam-doesnt-launch/623
