### ISSUE TITLE
[firefox-kde-38.0.5-1] back button constantly greyed out/inactive

### ISSUE THREAD

**Issue by udeved** [manjaro/packages-community#18]
I encountered a theming(?) bug only with firefox-kde-38.0.5-1.
The back navigation button is permanently inactive.

Switching to firefox default package solves it and button is active again.

**Comment by Kirek** [comment]
Don't have this bug, which theme and DE?

**Comment by udeved** [comment]
Plasma5 with Adwaita or clearlooks set.

**Comment by Kirek** [comment]
I'm using adwaita for gtk2/3, with clearlooks I don't have this bug too... I will check the firefox-kde pkgbuild if something is wrong.

**Comment by udeved** [comment]
Its definitely system wide, so its not an issue with firefox profile, addons or something like that.
Only switching to firefox solved it.

**Comment by Kirek** [comment]
Try firefox-kde-38.0.6, should be in the repos in a few minutes.

**Comment by udeved** [comment]
Will do, but I am now at home from what was supposed to be just a quick visit at mom's place for a cup of coffee.

**Comment by Kirek** [comment]
Did you test that?

**Comment by udeved** [comment]
It works fort me at home.
I will test the laptop where it originally occurred the week end.
