### ISSUE TITLE
dmenu-xft

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#19]
please kindly add for i3-profile: https://github.com/oberon2007/dmenu-xft
Thank you.

**Comment by philmmanjaro** [comment]
@oberon2007: would have been faster if you would have cloned our [community] git-repo, added your files to your fork and created a pull request. I'll clone now your repos and put the files manually. Just a suggestion for new packages from your end.

**Comment by oberon2007** [comment]
I'm sorry! All this git-hubbing is still quite Chinese to me 8-/ Thank you anyway! :)

**Comment by philmmanjaro** [comment]
Hey mate. No biggy. If we might find time for it we can do a share-desktop session or something, so I show you some stuff how we developers can work closer and easier together. I don't expect that you know "all" from the get-go :-)
