### ISSUE TITLE
[linux-rt] adjusting config

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#192]
@budimanjojo, I was trying to build the kernel in the chroot - which is probably unnecessary - and it failed because LIVEPATCH was not configured. I think the config for this is triggered by one of our other new settings. I've added this now in **config.rt**
```
CONFIG_HAVE_LIVEPATCH=y
# CONFIG_LIVEPATCH is not set
```
Now automatic config works and results in this [**.config**](https://github.com/oberon2007/manjaro-rt/blob/master/.config)
I'll try a new build with this now.

**Comment by budimanjojo** [comment]
Yeah, I already know that. It should ask you a question about do you want to turn it on before building though, I just pressed Y and it built just fine. I'll add it in config.rt later ☺

**Comment by oberon2007** [comment]
I sent you a pull request with the adjustments.

**Comment by oberon2007** [comment]
Would I mind continuing the work on this in your fork of repo packages-community? I think this will simplify things... :wink: 
I've included all the latest changes there now.

**Comment by budimanjojo** [comment]
Okay, just do it ☺
