### ISSUE TITLE
Vertex-maia-theme : chrome folder problem

### ISSUE THREAD

**Issue by Ste74** [manjaro/packages-community#193]
Hi guys , read here 
https://forum.manjaro.org/t/change-the-dark-theme-of-firefox/4354/1 
do you think 
is better change the permission for chrome folder or split the pkg into another like firefox-vertex-maia-themes ?

**Comment by oberon2007** [comment]
See my comment there. There are some misunderstanding here!

**Comment by Ste74** [comment]
;p
