### ISSUE TITLE
thunderbird-kde, firefox-kde: rebuild against hunspell 1.4

### ISSUE THREAD

**Issue by abashedlumber** [manjaro/packages-community#196]
Thunderbird-kde and Firefox-kde aren't working with hunspell 1.4:
`XPCOMGlueLoad error for file /usr/lib/thunderbird/libxul.so:
libhunspell-1.3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.`

Rebuild against new wersion is needed.
https://bbs.archlinux.org/viewtopic.php?id=214003

**Comment by Kirek** [comment]
It's being done, I will upload the rebuilds tonight.
