### ISSUE TITLE
Correction in vertex-maia-theme

### ISSUE THREAD

**Issue by Ste74** [manjaro/packages-community#197]
Hi guys , vertex maia is our official theme and adopted by almost all our desktop images. Unfortunately it seems that the integration in Firefox is still not the best at some sites example in youtube the search box is unreadable so is possible add a userContent.css in vertex-maia folder and delete vertex-maia-dark in firefox and palemoon folder ? ( vertex-maia-dark with firefox is most in more part broken not know in palemoon ) 

Reference : 
https://forum.manjaro.org/t/manjaro-gnome-16-06-16-06-1/3689/45?u=ste74

and css style
https://forum.manjaro.org/t/manjaro-gnome-16-06-16-06-1/3689/47?u=ste74

I tested myself and the result is more readable

**Comment by oberon2007** [comment]
This is a repeated topic. Obviously people are still not understanding that the css files are only applied by FF when they are copied to or linked from the mozilla profile. I would say it's not an issue of the theme but of firefox that you have to do this manually...
Where do you want to add it "in the theme folder"? I don't understand.
Everything - including that youtube searchbox - looks perfectly fine with chrome folder properly linked in the profile, like we do it in the default profile on the xfce-edition for example:
![](http://imgur.com/2UXIZQZl.png)

**Comment by oberon2007** [comment]
When we link it, people complain that the link is there. When we don't link it, they complain that the css is not applied - it will just never be right for everyone :stuck_out_tongue_winking_eye:

**Comment by Ste74** [comment]
But your Chrome folder what contain ? In my folder only userChrome.css ... just for understand :wink: .. In my case whitout userContent.css not see fine youtube tab search .. maybe is problem of DE ?

**Comment by oberon2007** [comment]
We have this (except for the Light folder of course) in **/usr/share/themes/Firefox**:
https://github.com/horst3180/vertex-theme/tree/master/extra/Firefox
and use the chome folder in the profile like this:
https://github.com/manjaro/manjaro-xfce-settings/tree/master/skel/.mozilla/firefox/manjaro.default

**Comment by oberon2007** [comment]
The userContent.css should only be needed when you use the dark theme. So it's not there in the regular chrome folder.

**Comment by oberon2007** [comment]
Here's Vertex-Maia with the link to the Vertex-Maia chrome folder (not Dark). Works equally fine:
![](http://imgur.com/Ffvpk7Ml.png)

**Comment by Ste74** [comment]
Found the guilty .. you and other not use the dark theme of vertex in de ? I use the dark version of vertex in gnome and budgie and vertex-maia for firefox ( vertex-maia-dark is broken not complete in some parts ) . If use vertex-maia bingo youtube is readable

**Comment by oberon2007** [comment]
When you use Vertex-Maia you just have to link to /usr/share/themes/Firefox/Vertex-Maia**-Dark**/chrome :smiley: 
Nothing is broken.

**Comment by Ste74** [comment]
this is my configuration and for firefox 
/usr/share/themes/Firefox/Vertex-Maia-Dark/chrome 
![schermata del 2016-06-25 18-43-07](https://cloud.githubusercontent.com/assets/11218234/16357933/efd0f522-3b04-11e6-93b4-1a4330dfb8cf.png)
![schermata del 2016-06-25 18-43-07](https://cloud.githubusercontent.com/assets/11218234/16357942/26baa79a-3b05-11e6-8362-25f39770afb5.png)

**Comment by Ste74** [comment]
Gnome is equal .. if use vertex-maia and not dark for firefox ok work fine

**Comment by Ste74** [comment]
I'm confused :stuck_out_tongue_winking_eye:
