### ISSUE TITLE
dkms.service runs after systemd-modules-load

### ISSUE THREAD

**Issue by ghost** [manjaro/packages-community#2]
Hi. 

The issue is, that because `systemd-modules-load` runs before dkms, it loads old modules (eg. vboxdrv and related) before `dkms` has a chance to rebuild them (when needed). Sometimes it's ok because the old modules don't load due to "Exec format error" but there's at least one case where loading them causes a kernel oops (when new kernel has lock debugging enabled but old modules were built with a kernel that hadn't - if I remember correctly).

Currently, for me, the date/time when `systemd-modules-load` and `dkms` got started is seen below (although this is not the only way that I know `dkms` gets started after `systemd-modules-load` - the other way was reading dmesg and seeing how old modules failed to load, though dkms loaded them after recompilation):

```
$ systemctl status system-modules-load
● system-modules-load.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
[emacs@manji ~]$ systemctl status systemd-modules-load
● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/usr/lib/systemd/system/systemd-modules-load.service; static)
   Active: failed (Result: exit-code) since Fri 2014-07-11 00:15:24 CEST; 2h 21min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
  Process: 1582 ExecStart=/usr/lib/systemd/systemd-modules-load (code=exited, status=1/FAILURE)
 Main PID: 1582 (code=exited, status=1/FAILURE)

```
(ignore the failure, it's because `nfs` wasn't built into the kernel, and I didn't have enough time yet to see how to disable `systemd-modules-load` from trying to load them **EDIT:** fixed that, I had to uninstall nfs-utils package because it put the `nfs` text inside this file /usr/lib/modules-load.d/nfs-utils.conf  very sneaky ;) 'cause I was looking only in /etc/mod*/)

```
$ systemctl status dkms
● dkms.service - Dynamic Kernel Modules System
   Loaded: loaded (/usr/lib/systemd/system/dkms.service; enabled)
   Active: active (exited) since Fri 2014-07-11 00:15:27 CEST; 2h 21min ago
  Process: 2299 ExecStart=/usr/lib/systemd/scripts/dkms start (code=exited, status=0/SUCCESS)
 Main PID: 2299 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/dkms.service
```

I didn't not find any immediately obvious solution to this although I tried(but I don't have enough knowledge - beginner), for example putting a `Before=systemd-modules-load.service` into `dkms.service`   seemed to have no effect.

Thanks.

PS: I'm reporting this here (probably wrongly) because dkms is from community (pacman-wise).
PS2: this issue is probably the same on archlinux too - note that I have recompiled the kernel manually, ergo maybe I am missing something and this happens only for me (this=the fact that dkms runs after s-m-l;  not that i got kernel oops or Exec format error)

**Comment by philmmanjaro** [comment]
Well, all extramodules we compile anyway. DKMS is not used here. If your issue is still open, please reopen this issue once more.
