### ISSUE TITLE
Package functionality already provided in gnome 3.20.x

### ISSUE THREAD

**Issue by sljunkie** [manjaro/packages-community#201]
In GNOME 3.20.x this extension functionality (MPRIS media player control) is built-in in the shell https://help.gnome.org/misc/release-notes/3.20/ so this package could be pulled from 16.04 + installation

**Comment by Ste74** [comment]
Do you mean exactly ? I not understand can you explain more ? In our repo is present this https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer

**Comment by sljunkie** [comment]
Manjaro gnome install the package 'manjaro-gnome-settings'. Here's the pacman -Qi manjaro-gnome-settings output:

```
Name            : manjaro-gnome-settings
Version         : 20160605-1
Description     : Manjaro Linux gnome settings
Architecture    : any
URL             : https://github.com/manjaro/desktop-settings
Licenses        : GPL
Groups          : None
Provides        : manjaro-desktop-settings
Depends On      : gnome-shell  gnome-shell-extensions  gnome-shell-extension-openweather  gnome-shell-extension-mediaplayer  gnome-shell-extension-gnomenu  gnome-shell-extension-dash-to-dock  gnome-wallpapers  xcursor-simpleandsoft
Optional Deps   : plymouth-theme-manjaro-gnome [installed]
Required By     : None
Optional For    : None
Conflicts With  : manjaro-desktop-settings
Replaces        : None
Installed Size  : 84.00 KiB
Packager        : Stefano Capitani <stefano@manjaro.org>
Build Date      : Sun 05 Jun 2016 02:15:53 PM BRT
Install Date    : Tue 07 Jun 2016 04:26:53 PM BRT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

This extension is basically obsolete in GNOME 3.20.x since its feature is built-in in the shell. So at least the package should be dropped from the 'depends' array in the manjaro-gnome-settings PKGBUILD.

**Comment by Ste74** [comment]
So you mean to install via browser ( example firefox ) this extension ?  If you mean this is not possible drop it in manjaro-gnome-settings because this file is only used to help new user to install easy the look of the last iso image .

**Comment by sljunkie** [comment]
hum I see. So we have an upgrade problem... perhaps putting the package as an 'optional dependency' could work out.

**Comment by Ste74** [comment]
Why upgrade problem ? gnome-shell-extensions-mediaplayer is not developed ? When eonpatapon update pkg i push new pkg in our repo

**Comment by sljunkie** [comment]
No, that's not it. This package provides an extension whose functionality is present on gnome-shell 3.20.x. So it's reduntant to include in a default gnome installation from 16.06 on.

**Comment by Ste74** [comment]
Ah i see now you intend this future ? 
http://www.omgubuntu.co.uk/2016/03/gnome-3-20-new-features-improvements
media player control ?

**Comment by sljunkie** [comment]
Yep; gnome 3.20 is installed in Manjaro Gnome 16.06 and the media control provided in gnome-shell 3.20 works perfectly.

**Comment by Ste74** [comment]
Close via https://github.com/manjaro/packages-community/commit/57c7c4a341a41bdf9272cd7b714963dfd58a8621
thank you to point me :smile:
