### ISSUE TITLE
linux-rt8 vboxhost-module error

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#203]
```
/home/bernhard/manjaro/community/linux-rt-manjaro-extramodules/virtualbox-modules/src/dkms/vboxhost/5.0.24_OSE/build/vboxdrv/r0drv/linux/timer-r0drv-linux.c: In function ‘rtTimerLnxStartSubTimer’:
/home/bernhard/manjaro/community/linux-rt-manjaro-extramodules/virtualbox-modules/src/dkms/vboxhost/5.0.24_OSE/build/vboxdrv/r0drv/linux/timer-r0drv-linux.c:364:13: error: implicit declaration of function ‘mod_timer_pinned’ [-Werror=implicit-function-declaration]
             mod_timer_pinned(&pSubTimer->u.Std.LnxTimer, pSubTimer->u.Std.ulNextJiffies);
             ^~~~~~~~~~~~~~~~
  CC [M]  /home/bernhard/manjaro/community/linux-rt-manjaro-extramodules/virtualbox-modules/src/dkms/vboxhost/5.0.24_OSE/build/vboxdrv/common/alloc/alloc.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:291: /home/bernhard/manjaro/community/linux-rt-manjaro-extramodules/virtualbox-modules/src/dkms/vboxhost/5.0.24_OSE/build/vboxdrv/r0drv/linux/timer-r0drv-linux.o] Error 1
```

**Comment by oberon2007** [comment]
@budimanjojo

**Comment by oberon2007** [comment]
When I had built and installed 4.6.4 rt7 this afternoon, virtualbox-dkms still updated successfully. So looks like a recent change in rt8 is causing this problem now.

**Comment by budimanjojo** [comment]
Alright, that means we have to wait for another rt9? Where should we report this to?

**Comment by oberon2007** [comment]
I guess we'll have to wait for the [virtualbox-dkms packages](https://www.archlinux.org/packages/community/i686/virtualbox-host-dkms/) to be updated ... :wink:

**Comment by budimanjojo** [comment]
Okay, hope that's what causing the error here :)

**Comment by oberon2007** [comment]
**virtualbox**, including dkms has been updated upstream. I'll try rebuilding the rt8 against it tonight...

**Comment by oberon2007** [comment]
Unfortunately the error persists with virtualbox-dkms 5.1.0
I haven't found a proper place to discuss such issues. I'll try to contact the author of the rt-patch...

**Comment by budimanjojo** [comment]
So this error didn't happen in rt7 but in rt8?

**Comment by oberon2007** [comment]
Exactly! It appeared with rt8.

**Comment by budimanjojo** [comment]
So we really need to contact the rt patch maintainer here. You already did? Here's his contact: Sebastian Andrzej Siewior <bigeasy@linutronix.de>

**Comment by oberon2007** [comment]
I found a relevant [mailing-list](http://www.spinics.net/lists/linux-rt-users/) - Just until now I was not able to post to it ... I'm working on it :wink: 
(maybe remove the author's mail address here - he might not be all to happy to have it out on the net openly like that... :stuck_out_tongue_winking_eye: )

**Comment by budimanjojo** [comment]
Deleted 😄

**Comment by oberon2007** [comment]
http://www.spinics.net/lists/linux-rt-users/msg15522.html

**Comment by budimanjojo** [comment]
https://github.com/manjaro/packages-extra/issues/93
Is this issue also happening in manjaro core kernels?

**Comment by oberon2007** [comment]
no. It's only with rt8.

**Comment by budimanjojo** [comment]
Okay :)

**Comment by oberon2007** [comment]
inux-rt in AUR has also been updated to 4.6.4-rt8 now. Building it now to see if it has the same issue or if it might be caused by our config...

**Comment by budimanjojo** [comment]
Okay :)

**Comment by oberon2007** [comment]
So we know that now: Same situation there:
```

**Comment by budimanjojo** [comment]
Okay, so we're not alone here. So I hope it won't be a long fix :smile:

**Comment by oberon2007** [comment]
In any case we have a well working rt7 for the time being - no problem there. :)

**Comment by budimanjojo** [comment]
@oberon2007 I think you should post your report in the 4.6.4-rt8 announcement instead, http://www.spinics.net/lists/linux-rt-users/msg15512.html. 
Sorry I was caught up on something else yesterday. Will test this out tonight.

**Comment by oberon2007** [comment]
Here's more information from Sebastian:
> This change will be part of v4.8. If virtualbox wants to work with v4.8+
they need to update their code. Once this happens, it will work with
-RT.

For us I think the strategy will have to be, wait for vbox to drop ``mod_timer_pinned`` before we can use rt8. Until then we'll just have to stick to rt7-patch...

**Comment by oberon2007** [comment]
I've opened an [issue](https://www.virtualbox.org/ticket/15695) at virtualbox about this. Meanwhile I wonder, since we're building vbox anyway if we could maybe simply patch **virtualbox** for now. Kernel maintainer Thomas Gleixner just suggested via email:
> The fix is trivial. See
    http://marc.info/?l=linux-kernel&m=146762632027319&w=2
for reference.

**Comment by budimanjojo** [comment]
Nice, the patch seems like a patch for the kernel instead of virtualbox? I'll try to build it later with the patch.

**Comment by oberon2007** [comment]
I've built vbox with this patch now and will check extramodules against rt8 later

**Comment by budimanjojo** [comment]
Okay, thanks mate :)

**Comment by oberon2007** [comment]
https://github.com/manjaro/packages-community/pull/207#issuecomment-235372439

**Comment by oberon2007** [comment]
That one appears to be [working fine](https://github.com/manjaro/packages-community/commit/ee98a6c42053b275d5a8ab8d7f443a68e2ad4df2#commitcomment-18463796), also with vbox-modules.
How should we procede now until either Oracle adjusts vbox code (or we find a way to patch it in a way that works with all current kernels)?
Patching the patches newer than 4.6.4-rt7 for **linux-rt-manjaro** seems dirty.
I think the feasible options are:
* freeze **linux-rt-manjaro** at 4.6.4_rt7 (currently in unstable) and wait until vbox works with newer patches
* continue updating **linux-rt-manjaro** (accepting that currently it just won't work with vbox plus additionally maintain **linux-rt-lts-manjaro** based on linux44
* stick with just one package **linux-rt-manjaro** and downgrade to **4.4.15_rt23** - or introduce epoch **1:4.4.15_rt23** (not so nice)

What do you guys think? @budimanjojo @philmmanjaro ?

**Comment by budimanjojo** [comment]
I myself prefer to just downgrade to base on lts kernel. :)

**Comment by philmmanjaro** [comment]
Simply downgrade without the epoch. The kernel isn't in stable anyway. So only **unstable** and **testing** users will have the `You*re using something newer than in repo`-thingy ...

**Comment by oberon2007** [comment]
Another option would be to remove **linux-rt-manjaro** for the time being and just add **linux-rt-lts-manjaro**. That will save us quite some editing when switching back and forth between basekernels...

**Comment by budimanjojo** [comment]
But will it disable the mhwd settings to recognize rt kernel again?

**Comment by philmmanjaro** [comment]
Please ask @Kirek regarding how it was implemented.

**Comment by Kirek** [comment]
Only "linux-rt-manjaro" is recognized now, but adding "linux-rt-lts-manjaro" is trivial.

**Comment by oberon2007** [comment]
If you wouldn't mind, @Kirek , that would be great. To me it looks like the most convenient course of action to keep the packages seperate. I'd remove **linux-rt-manjaro** from the repos now but keep maintaining it, so we can re-add it once the vbox issue is solved - and meanwhile add **linux-rt-lts-manjaro** instead.

**Comment by philmmanjaro** [comment]
@oberon2007: why remove it? If only one extramodule doesn't work, remove that. Also you can keep it on a version and update the package later. Depends on your will. Support for **linux-rt-lts-manjaro** can be [similar added](https://github.com/manjaro/manjaro-settings-manager/commit/189111a4eaa4e8e903a88194b2189b9d3666e125).

**Comment by oberon2007** [comment]
ok. lets do that :smiley: I favour updating it, so you will have to choice of a bleeding edge 46rt without virtualbox (which normally you will not need in a music production environment :wink:) and a (hopefully) more stable and versatile 44rt - seems to make sense. We can then also experiment more with that brand new [CONFIG_NO_HZ_FULL](https://github.com/manjaro/packages-community/commit/124a126dd73e94b1e01f7fcad2c61424dd139d1f), which is only available with linux46 afaik and can maybe find some people to test this. :+1:

**Comment by budimanjojo** [comment]
Okay ☺

**Comment by oberon2007** [comment]
https://github.com/manjaro/manjaro-settings-manager/pull/82

**Comment by budimanjojo** [comment]
Can you give me the link of the build later @oberon2007? I'll need virtualbox, nvidia, headers, and the kernel. I don't have time to compile :crying_cat_face:

**Comment by oberon2007** [comment]
**linux-rt-lts** is in the unstable repo now, together with headers and extramodules. Testing branch still has **linux-rt 4.6.4_rt7**, so your save on every branch ;)

**Comment by oberon2007** [comment]
**rt-4.6.5_rt9** also in unstable now.

**Comment by budimanjojo** [comment]
Alright. Thanks :smile:

**Comment by Kirek** [comment]
Merged you code @oberon2007 and changed how we detect the running kernel, so we can support the normal and the lts rt kernel.
https://github.com/manjaro/manjaro-settings-manager/commit/fa49fba61dee57f19ce1b8616c2ec7b92f09058e

**Comment by budimanjojo** [comment]
Thanks @Kirek :)

**Comment by oberon2007** [comment]
Thank you very much! :smile:

**Comment by oberon2007** [comment]
Oracle has now addressed the problem of removed ``mod_timer_pinned`` for linux48 by checking the kernel version like this: https://www.virtualbox.org/changeset/63341/vbox
This leaves us with the problem that **linux-rt-manjaro** is of course still recognized as linux46 regardless of the fact that with the rt-patch we would infact need that code-change in order for vbox to work with linux-rt.
I have asked Sebastian, the rt-author, for advice on how we could make vbox distinguish between a standard and an rt-patched linux46 and he suggests to add an RT specific define in the kernel's Makefile, similar to ``KBUILD_CPPFLAGS := -D__KERNEL__``
We could the simply patch vbox with a test for that RT define.
Can anyone help in accomplishing this? @philmmanjaro ? @Kirek ?

**Comment by oberon2007** [comment]
I was now at least able to build the vbox-extramodules for **linux-rt** by modifying the original upstream patch (to apply for kernels >=4.6
Of course this is not really satisfying, yet, because with virtualbox-dkms compiled like that you cannot build the extramodules for regular 4.6 and 4.7 kernels and I have to compile a separate version for 4.6-rt :stuck_out_tongue_closed_eyes: 
A better solution would be more than welcome!
I've tried running virtualbox now with the regular **virtualbox** package from the repo under **linux-rt** with the extramodules built from the special **vbox-dkms** versions and it seems to run normally...

**Comment by budimanjojo** [comment]
Hope it works. :) 
So I think this should be a workaround until 4.8 rt came out? I hope we can get 4.7 rt soon.

**Comment by oberon2007** [comment]
With the 4.7 series I expect we'll have the same issue, because very likely the rt-patch will again remove the ``mod_timer_pinned`` function while the official kernel only does this step with the 4.8 release :stuck_out_tongue_closed_eyes: We need an elegant solution for vbox. It's tedious to compile virtualbox twice just for that...

**Comment by budimanjojo** [comment]
What did Sebastian suggested you? Did he ask us to include the specific make flag into our PKGBUILD?

**Comment by oberon2007** [comment]
We should export an RT specific define from the kernel Makefile, but I'm afraid I don't know how to do that properly. That's why I asked for help :wink: 
Maybe it would also be an option to add a variable that gets exported to **version.h** here:
```
define filechk_version.h
	(echo \#define LINUX_VERSION_CODE $(shell                         \
	expr $(VERSION) \* 65536 + 0$(PATCHLEVEL) \* 256 + 0$(SUBLEVEL)); \
	echo '#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))';)
endef
```
(Makefile line 1041)
We just need someone with some coding experince here ;)

**Comment by budimanjojo** [comment]
```
build() {
  cd "${srcdir}/${_srcname}"

  # build!
  make ${MAKEFLAGS} LOCALVERSION= bzImage modules
}
```
Can we specify it using the MAKEFLAG in our PKGBUILD?

**Comment by oberon2007** [comment]
I wonder if we can simply use something like
``KBUILD_CPPFLAGS := -DRT_PATCHED`` in the Makefile
and then test in vbox code:
``# if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 8, 0) || ifdef RT_PATCHED``
?

**Comment by budimanjojo** [comment]
Yeah, I think we shouldn't modify the kernel version in the patch. But add another statement like above, maybe using kernel version= 4.6?Because linux46 is already EOL right? I don't know but seems like people using linux46 are not going to update to 4.7 so soon. I'm confused too.

**Comment by philmmanjaro** [comment]
**linux46** is history anyway. However you have to use the known workarounds to patch the needed dkms file like I did [many times before](https://github.com/manjaro/packages-extra/commit/4e7114665dfc32c3c127b2126decf08e1ab321da). Most likely Oracle won't patch it.

**Comment by oberon2007** [comment]
I'll check out the possibilities... of course we'll continue to have the same issue with linux47... :wink:

**Comment by philmmanjaro** [comment]
Yeah, I know. It is sometimes special cases after all ...

**Comment by oberon2007** [comment]
I was indeed able to fix this quite beautifully by adding an extra [define](https://github.com/manjaro/packages-community/commit/68edd6f20ca1976d45f4ca7db1cd7dd1247173b3#diff-8f295f62d4a0926737bb486a54b57e8bR171) in the rt-kernel and [extending](https://github.com/manjaro/packages-community/commit/68edd6f20ca1976d45f4ca7db1cd7dd1247173b3#diff-104ad2d114dd51a5e96966b7041f1365R7) Oracle's pending patch to test for the kernel version in vbox code like described above.
dkms-extramodules are now building successfully for all our kernels with ``mod_timer_pinned()`` replaced only for >=linux48 and linux-rt-manjaro :tada: :laughing: 
```
:: Running post-transaction hooks...
(1/4) Install DKMS modules
==> dkms install -m vboxguest -v 5.1.4_OSE -k 3.10.102-1-MANJARO
==> dkms install -m vboxguest -v 5.1.4_OSE -k 3.12.62-1-MANJARO
==> dkms install -m vboxguest -v 5.1.4_OSE -k 3.14.76-1-MANJARO
==> dkms install -m vboxguest -v 5.1.4_OSE -k 3.16.36-1-MANJARO
==> dkms install -m vboxguest -v 5.1.4_OSE -k 3.18.39-1-MANJARO
==> dkms install -m vboxguest -v 5.1.4_OSE -k 4.1.30-1-MANJARO
==> dkms install -m vboxguest -v 5.1.4_OSE -k 4.4.17-1-rt25-MANJARO
==> dkms install -m vboxguest -v 5.1.4_OSE -k 4.4.18-1-MANJARO
==> dkms install -m vboxguest -v 5.1.4_OSE -k 4.6.5-2-rt10-MANJARO
==> dkms install -m vboxguest -v 5.1.4_OSE -k 4.6.7-1-MANJARO
==> dkms install -m vboxguest -v 5.1.4_OSE -k 4.7.1-1-MANJARO
```

**Comment by oberon2007** [comment]
We will just need to use our own **virtualbox-guest-dkms** and **virtualbox-host-dkms** packages from now on, but we are  building them anyway. Once the linux48 patch gets included updstream by Oracle we'll just have to adjust our patch to add the rt-specific extra test.

**Comment by budimanjojo** [comment]
So what's the conclusion here? Do we keep on building vbox twice?

**Comment by oberon2007** [comment]
Absolutely not! The whole point is that our patched vbox is now able to distinguish **rt-manjaro** from the regular **linux46** and the modules get compiled accordingly with the correct timer function used that are available in the respective kernel. :smile:

**Comment by budimanjojo** [comment]
Nice, I didn't see your last 2 posts before (didn't refresh my browser). So we now have the vbox module back. Thanks oberon :D
