### ISSUE TITLE
[linux-rt] consider setting CONFIG_NO_HZ_FULL=y

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#204]
As announced [here](http://www.spinics.net/lists/linux-rt-users/msg15512.html), [NO_HZ_FULL](https://www.kernel.org/doc/Documentation/timers/NO_HZ.txt) is supported since rt8. So I guess we should consider setting it in our config?
Though, at the moment I'm wondering if exactly these recent "Refactor the timer wheel" changes, introduced with the new patch are responsible for our [issue]() with the failing [vbox-modules](https://github.com/manjaro/packages-community/issues/203)

**Comment by budimanjojo** [comment]
What is that doing? Does it mean we need to disable the CONFIG_HZ_1000?

**Comment by oberon2007** [comment]
It should be possible to set both HZ_1000 and NO_HZ_FULL.
Maybe you'd like to run a testbuild in your latency sensible test environment? :smile:

**Comment by budimanjojo** [comment]
I'll do that tomorrow. Weekend here. Thanks for the update man. :smile:

**Comment by oberon2007** [comment]
My experiences sofar are not so good with this config.
I see random crashes with
```
kernel: [drm:intel_pipe_update_end [i915]] *ERROR* Atomic update failure on pipe A (start=68236 end=68237) time 9 us, min 763, max 767, scanline start 760, end 767
```
and 
```
kernel: [drm:intel_pipe_update_end [i915]] *ERROR* Atomic update failure on pipe A (start=104199 end=104200) time 154 us, min 763, max 767, scanline start 762, end 770
```

**Comment by budimanjojo** [comment]
I'll give it a try tomorrow. Also, looking at the known issue in the NO_HZ_FULL manual above, it seems like this is not something good for CPU performance and stability.

**Comment by oberon2007** [comment]
I'll implement this with the next update. Since we have the more conservative rt-lts I think we can be more experimental with this one :wink:

**Comment by budimanjojo** [comment]
Okay, let's do it. :)

**Comment by korrode** [comment]
Considering the goal of this kernel, why use NO_HZ at all?

**Comment by budimanjojo** [comment]
I don't really understand after reading the documentation. Can you give us an explanation why using NO_HZ is not good towards our goal?

**Comment by oberon2007** [comment]
Is it a misundestanding that NO_HZ means a gain in latency?

**Comment by korrode** [comment]
I'd have thought that introducing the potential of needing to wake from idle would be bad for RT, but indeed the documentation says NO_HZ is better for it...

**Comment by oberon2007** [comment]
It appears that the guys on the rt-mailing lists were quite keen on finally getting this parameter to work with the latest 4.6 patch... So I took that as a sign that the rt users think they will profit from it. I can't say that I really understand, why ... :stuck_out_tongue_winking_eye:

**Comment by korrode** [comment]
The [documentation](https://www.kernel.org/doc/Documentation/timers/NO_HZ.txt) isn't really helping.

At first it says no_hz_full is good for RT, then at one point it says:
_"Therefore, systems with aggressive real-time response constraints often run CONFIG_HZ_PERIODIC=y kernels [...] in order to avoid degrading from-idle transition latencies."_

Then later it gives a list of negatives to using no_hz_full over no_hz_idle and a couple them relate to real time...

...but yeah, presumably the guys on RT mailing list know best.

**Comment by budimanjojo** [comment]
Yeah, I'm also confused. So which one should we use? I presume we just add NO_HZ_FULL?

**Comment by oberon2007** [comment]
**4.6.5-rt10** was just released. How about we set ``NO_HZ_FULL`` and you test it a little against the rt-lts @budimanjojo ?

**Comment by budimanjojo** [comment]
Okay. What do we need to test though?
