### ISSUE TITLE
sonar-sound-theme

### ISSUE THREAD

**Issue by udeved** [manjaro/packages-community#208]
I am going to simplify the upstream for sonar, I put it in sonar-artworks repo @oberon2007

**Comment by oberon2007** [comment]
OK. And merge the packages?

**Comment by udeved** [comment]
Yes, I am on the sonar-artworks package, I have just added sonar-sound-theme and sonar-common.

**Comment by udeved** [comment]
https://github.com/manjaro/packages-extra/commit/66c5bada5655c1651f50f8d3f2aa178bc55ca64e
