### ISSUE TITLE
Upgrade 'engrampa-thunar' to v1.10.0

### ISSUE THREAD

**Issue by telephone** [manjaro/packages-community#21]
[Engrampa](https://github.com/mate-desktop/engrampa/releases) is now v1.10.0 (released 5th of May).

Creating the package (v1.10.0) locally resulted in an error with [caja_schema_fix.patch](https://github.com/manjaro/packages-community/blob/a1ca80999a40b075e859567a832787c4229d0e92/engrampa-thunar/caja_schema_fix.patch) failing to patch. I commented out the patch and the package creation worked. I've tested it locally and everything is in working order.

^ I'm unsure if the patch is still required as it appears they've added conditionals for the caja scheme. (I only did a quick browse).

**Comment by korrode** [comment]
It's good to check if a package is sourced from AUR and that the issue exists on Arch, and if so, then report about it in the comments section for the package on AUR.

**Comment by telephone** [comment]
@korrode The package is originally from [AUR](https://aur.archlinux.org/packages/en/engrampa-thunar/), but has been disowned since October last year. Of which I didn't feel like taking over the project, so I reported it here.

Before disowning, the owner (n00b) left this comment:
> I'll disown the package, since I don't use it anymore,and upstream they merged a similar patch, so from engrampa 1.10 no more schema error. [¹]

The problem remains that engrampa (vanilla install) does not install the necessary .tap file to work with XFCE's thunar-archive-plugin. Thus making this package still relevant. If the Manjaro team would like to takeover the AUR/4 project then I won't complain :smile:.

---

[1] - [Use Caja GSettings schema optionally](https://github.com/mate-desktop/engrampa/pull/60/)

**Comment by korrode** [comment]
@telephone As can be seen if one simply looks at the "Maintainer:" field on the AUR page (which btw, your link doesn't work, here is a working link: https://aur.archlinux.org/packages/engrampa-thunar/ ), the package is not currently disowned, it has a maintainer (i.e. me).

The previous maintainer posted that comment prior to the 1.10 release, he was saying that they merged the patch into their git master branch, so *once* 1.10 gets released it would no longer be needed.

The AUR package simply needed to be flagged out-of-date and then it would have been updated, not only for Manjaro users, but for all Arch users.

**Comment by telephone** [comment]
@korrode Whoops, sorry about the dead link. When I was browsing, I looked at [AUR4](https://aur4.archlinux.org/packages/engrampa-thunar/) (not AUR) which has no maintainer. For the past week, I've seen quite a growing number of packages only being updated on AUR4 so that's my default now.

Would you like me to flag it out-of-date for you? :stuck_out_tongue_winking_eye:

**Comment by korrode** [comment]
I didn't think it existed on AUR4 at all (if one does a search for "engrampa" or "thunar" from the AUR4 front page, it doesn't show up). I guess it's some kind of partly-hidden auto-migration.

I'll update it on AUR now. I have reasons why i haven't migrated my stuff to AUR4 yet, but that's another topic.
