### ISSUE TITLE
[vertex-maia-icon-theme] Please add xfce-nomail icon

### ISSUE THREAD

**Issue by Photon89** [manjaro/packages-community#211]
I'm using the mail notification applet for the Xfce panel and, while its icon matches the Vertex Maia icon theme when new mails are there, it uses the standard icon (grey envelope, see screenshot) when no mails are there. Looks like the icon theme has no xfce-nomail icon. I could find no bugtracker for the actual icon theme, so I report this problem here.

![_2016-08-03_15-35-22](https://cloud.githubusercontent.com/assets/1191480/17367354/ed76af7a-598f-11e6-9541-535575c2328e.png)

**Comment by oberon2007** [comment]
Do you have a screenshot for me with the new-mail icon?

**Comment by Photon89** [comment]
Here is the icon itself: https://raw.githubusercontent.com/manjaro/vertex-maia-icon-themes/master/Vertex-Maia/apps/scalable/xfce-newmail.svg

**Comment by oberon2007** [comment]
I'm not convinced that this is the one used in the panel. It has a round background! ...

**Comment by Photon89** [comment]
But it is still used. :) Same as the weather applet on the screenshot above!

**Comment by oberon2007** [comment]
ok. I'll try to cook something up ...

**Comment by oberon2007** [comment]
@Photon89 please test the new package and let me know if it's better now:
``sudo pacman -U http://mirror.netzspielplatz.de/manjaro/packages/unstable/community/x86_64/vertex-maia-icon-theme-20160805-1-any.pkg.tar.xz``

**Comment by Photon89** [comment]
Sorry for the late reply, I had a flat renovation going on and internet access was limited. I like the idea of just changing colours! However, the red colour clashes with the stop bar symbol which is being positioned over the mail icon if there are connection errors. Therefore I attached another proposal.

[xfce-mail-icons.tar.gz](https://github.com/manjaro/packages-community/files/406952/xfce-mail-icons.tar.gz)

**Comment by oberon2007** [comment]
hm. for me those two icons are too similar, I can almost not distinguish between them at all :laughing: We'll find a better solution..
So is that connection error icon being displayed instead of the mail icon, when something goes wrong with the connection? Or next to it?

**Comment by Photon89** [comment]
Well, if the blue is too pale, I can change the colour. :) Here is how the problem with the connection error and the red icon looks like (the stop sign is in the bottom left corner).
![auswahl_025](https://cloud.githubusercontent.com/assets/1191480/17515645/e2e26460-5e39-11e6-9884-d3269ec0042c.png)

**Comment by oberon2007** [comment]
How about this one, with the blue a little more obvious and using vertex-maia hightight colour for the background? https://github.com/manjaro/vertex-maia-icon-themes/commit/15577a23840069417327f3837b5c6b9fc46d1e3d

**Comment by oberon2007** [comment]
![](http://imgur.com/f0WtmdNl.png)

**Comment by Photon89** [comment]
Imho it looks nice but doesn't match with the style of the theme (which seems to have no colour gradients, only plain colours).

**Comment by oberon2007** [comment]
It does use gradients. The original backgroud was
```
  <linearGradient id="linearGradient3764" x1="1" x2="47" gradientUnits="userSpaceOnUse" gradientTransform="matrix(0,-1,1,0,-1.5e-6,47.999998)">
   <stop style="stop-color:#3d3d3d;stop-opacity:1"/>
   <stop offset="1" style="stop-color:#474747;stop-opacity:1"/>
  </linearGradient>
```
maybe mine is just too strong. :wink: I'll make the values closer...

**Comment by oberon2007** [comment]
Like this?

![](http://imgur.com/o31BGwZl.png)

**Comment by Photon89** [comment]
Looks good!

**Comment by oberon2007** [comment]
OK, thanks :)
``vertex-maia-icon-theme-20160809-1-any.pkg.tar.xz``
