### ISSUE TITLE
[PROPOSE] Is it possible to maintain an ffmpeg-full-nvenc package ?

### ISSUE THREAD

**Issue by Elrondo46** [manjaro/packages-community#214]
It will be cute, some nvidia users like use HW/Cuda accel for encoding videos (Openshot, OBS...)

**Comment by korrode** [comment]
Before making suggestions for packages to be included in Manjaro's repos you should check the license(s) of what you're asking us to consider distrusting.

You can see clearly just from the AUR page that it's not legally distributable.
https://aur.archlinux.org/packages/ffmpeg-full-nvenc/

Also: we don't need it for installation media, people who want it can install it from AUR.
IMO it's not worth us maintaining it.

**Comment by philmmanjaro** [comment]
Closed with given reasons ...
