### ISSUE TITLE
[i3-gaps] resize- and shutdown-menu issue

### ISSUE THREAD

**Issue by akarvi** [manjaro/packages-community#218]
After Sysupdate today I found a potential bug in community/i3-gaps 4.12.r118.g155f034-1. After changing to resize-mode ($mod+r) every key binded in resize-section in .i3/config failed. Also the Escape-Key to change to the default-mode. Same issue with shutdown-menu-script.
  
Installing  i3-gaps-git 4.12-1 from the AUR by yaourt -Sdd fixed it. But now a dependency issue with manjaro-i3-settings appears in pacman (without consequences).

Reproduced on two machines, No usable errors encountered in debug and X-logs.

**Comment by oberon2007** [comment]
You can remove **manjaro-i3-settings** safely to avoid dependency issue. It is only needed when you create a new user.
To be honest: The AUR package is identical to what is currently in our community repo. They use the same commit **155f034** (branches gaps and gaps-next are identical at the moment)
I would assume something in your config is causing this. Or it might be the ["Shift" bug](https://github.com/i3/i3/issues/2417).
You can switch to stable package **i3-wm**. That should not have any issues.

**Comment by Ste74** [comment]
Only to remember @akarvi now to report a bug is open our https://bugs.manjaro.org/

**Comment by akarvi** [comment]
@oberon2007: with git-version everything is fine here. I did not customize my config very much, on the other machine it was nearly original (except some bindsym changes), so I dont think its beause of the config. I'll read the Shift-bug.

I thought i3-wm is without gaps?

Thanks.

@Ste74: sorry, its my first bug report for manjaro. Next time I'll write there.

**Comment by oberon2007** [comment]
**i3-wm** is without gaps, yes. The **gaps-git** version from the AUR should be identical to our package, really! :wink: What about **i3-gaps-next-git** from the AUR? Does that work for you?

**Comment by akarvi** [comment]
I'll test gaps-next at work on monday and report here, if you are interested in.

**Comment by Ste74** [comment]
Don`t worry ;)
Il 26/ago/2016 19:38, Alex <notifications@github.com> ha scritto:@oberon2007: with git-version everything is fine here. I did not customize my config very much, on the other machine it was nearly original (except some bindsym changes), so I dont think its beause of the config. I'll read the Shift-bug.

I thought i3-wm is without gaps?

Thanks.

@Ste74: sorry, its my first bug report for manjaro. Next time I'll write there.

**Comment by akarvi** [comment]
The Shift-bug doesnt seem to be the one that plagued me. Shift-bindsyms work, especially close windows.

When git and community-version are the same it is really strange. Because I didn't change config or something else. I updated to new community/i3-gaps,  then tested resize-menu (and received issues) then installed git-version and all issues are gone (I tested it on VMWare-Install at work before, same way after on an Acer-laptop with native Manjaro-install at home).

**Comment by oberon2007** [comment]
Ok. more research tells me that the packages are infact not the same, even though the last commit ID is identical... Can you please check if this version works for you? :
``sudo pacman -U "http://oberon.at/oberon/i3-gaps-4.12.1-1-$(uname -m).pkg.tar.xz"``
Thanks.

**Comment by akarvi** [comment]
This version works fine.

**Comment by oberon2007** [comment]
Great! It's in the repos already. Thank you for reporting and testing!

**Comment by akarvi** [comment]
No problem.
One issue I detected: the statusbar seems to be "shifted" down. please look at the png: the font is pressed at the upper egde. With the old git-version (the one with the Resize-issue) the status bar was "higher" so that the font was in the middle of it. (I use i3blocks, but I tested with i3status > same issue)
![2016-08-27-094254_1366x768_scrot](https://cloud.githubusercontent.com/assets/21007212/18026027/5ea3367e-6c3b-11e6-877b-a21ccc2ab1e3.png)

**Comment by oberon2007** [comment]
What you see there is a [current issue](https://forum.manjaro.org/) of font **Cantarell**. You can either switch to for example **noto**, which looks very similar to Cantarell, or alternatively remove this config symlink **/etc/fonts/conf.d/31-cantarell.conf**

**Comment by akarvi** [comment]
Ahh, ok many thanks. :)
