### ISSUE TITLE
my package packnroll doesn't show in the repository lists

### ISSUE THREAD

**Issue by filipe-marques** [manjaro/packages-community#22]
I wrote a package called packnroll, that helps casual packagers and experienced packagers doing the package process and it is already packaged here in packages-community, but it doesn't show in the repository lists of octopi to install it. I refreshed the repository lists many times in this lasts weeks, but the problem remains.

**Comment by Kirek** [comment]
We probably missed it, it seems the PKGBUILD is broken though.

```
==> Retrieving sources...
  -> Found packnroll-1.0.0.tar.gz
==> Validating source files with md5sums...
    packnroll-1.0.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting packnroll-1.0.0.tar.gz with bsdtar
==> Starting build()...
WARNING: icon24.path is not defined: install target not created

WARNING: icon24_2.path is not defined: install target not created

/usr/lib/qt/bin/uic ui/prmainwindow.ui -o ui_prmainwindow.h
ui/prmainwindow.ui: Warning: The name 'layoutWidget' (QWidget) is already in use, defaulting to 'layoutWidget1'.
/usr/lib/qt/bin/uic ui/prdialog.ui -o ui_prdialog.h
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o main.o src/main.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o PRMainWindow.o src/PRMainWindow.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o PRDialog.o src/PRDialog.cpp
/usr/lib/qt/bin/rcc -name pnrresources resources/pnrresources.qrc -o qrc_pnrresources.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o qrc_pnrresources.o qrc_pnrresources.cpp
/usr/lib/qt/bin/moc -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/qt/mkspecs/linux-g++ -I/build/packnroll/src/packnroll-packnroll-1.0.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.1.0 -I/usr/include/c++/5.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/include-fixed -I/usr/include inc/PRMainWindow.hpp -o moc_PRMainWindow.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o moc_PRMainWindow.o moc_PRMainWindow.cpp
/usr/lib/qt/bin/moc -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/qt/mkspecs/linux-g++ -I/build/packnroll/src/packnroll-packnroll-1.0.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.1.0 -I/usr/include/c++/5.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/include-fixed -I/usr/include inc/PRDialog.hpp -o moc_PRDialog.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o moc_PRDialog.o moc_PRDialog.cpp
g++ -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro -o PacknRoll main.o PRMainWindow.o PRDialog.o qrc_pnrresources.o moc_PRMainWindow.o moc_PRDialog.o   -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat 'resource/icons/packnroll128.png': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting..
```

**Comment by philmmanjaro** [comment]
Well, it is not part of Manjaro yet. Please fix the mentioned issues.

**Comment by filipe-marques** [comment]
That's strange, because before I push to github I tested it (with namcap) and everything was alright.
I even package it and it was alright.
But I will test it again and if some errors show I will fix them.

**Comment by philmmanjaro** [comment]
@filipe-marques: always test it with our buildsystem 'manjaro-tools':
<pre>sudo buildpkg -p packnroll</pre>
We don't pack with makepkg directly.

**Comment by filipe-marques** [comment]
@philmmanjaro 
Thanks for the advice, but do I need to use sudo ?
The problem with the package packnroll is solved.
It was a typo that was causing the problem.

==> A criar o pacote: packnroll 1.0.0-1 (Sex Jul 24 09:53:51 WEST 2015)
==> A verfificar as dependências para executar a aplicação...
==> A verificar as dependências para construir a aplicação...
==> A obter as fontes ...
  -> A realizar a descarga de packnroll-1.0.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   141    0   141    0     0    181      0 --:--:-- --:--:-- --:--:--   181
100 40502  100 40502    0     0  24502      0  0:00:01  0:00:01 --:--:-- 53930
==> A validar ficheiros fonte com md5sums...
    packnroll-1.0.0.tar.gz ... Passou
==> A extrair as fontes...
  -> A extrair packnroll-1.0.0.tar.gz com bsdtar
==> A iniciar build()...
/usr/lib/qt/bin/uic ui/prmainwindow.ui -o ui_prmainwindow.h
ui/prmainwindow.ui: Warning: The name 'layoutWidget' (QWidget) is already in use, defaulting to 'layoutWidget1'.
/usr/lib/qt/bin/uic ui/prdialog.ui -o ui_prdialog.h
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o main.o src/main.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o PRMainWindow.o src/PRMainWindow.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o PRDialog.o src/PRDialog.cpp
/usr/lib/qt/bin/rcc -name pnrresources resources/pnrresources.qrc -o qrc_pnrresources.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o qrc_pnrresources.o qrc_pnrresources.cpp
/usr/lib/qt/bin/moc -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/qt/mkspecs/linux-g++ -I/home/filipe/C++/packages-community/packnroll/src/packnroll-packnroll-1.0.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.1.0 -I/usr/include/c++/5.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/include-fixed -I/usr/include inc/PRMainWindow.hpp -o moc_PRMainWindow.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o moc_PRMainWindow.o moc_PRMainWindow.cpp
/usr/lib/qt/bin/moc -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/qt/mkspecs/linux-g++ -I/home/filipe/C++/packages-community/packnroll/src/packnroll-packnroll-1.0.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/5.1.0 -I/usr/include/c++/5.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/include-fixed -I/usr/include inc/PRDialog.hpp -o moc_PRDialog.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o moc_PRDialog.o moc_PRDialog.cpp
g++ -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro -o PacknRoll main.o PRMainWindow.o PRDialog.o qrc_pnrresources.o moc_PRMainWindow.o moc_PRDialog.o   -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
==> Entra no ambiente fakeroot...
==> A iniciar package()...
==> A organizar a instalação...
  -> A remover ficheiros indesejados ...
  -> A remover libtool ficheiros...
  -> A remover ficheiros de bibliotecas estáticas...
  -> A comprimir páginas man e infos...
  -> A remover símbolos de debug desnecessários de binários e bibliotecas...
==> A criar o pacote "packnroll"...
  -> A gerar .PKGINFO ficheiros...
  -> A gerar o ficheiro .MTREE...
  -> A compactar o pacote...
==> Saindo do ambiente fakeroot.
==> Compilação concluída: packnroll 1.0.0-1 (Sex Jul 24 09:54:10 WEST 2015)

**Comment by oberon2007** [comment]
https://github.com/manjaro/packages-community/pull/23
