### ISSUE TITLE
python-efl needs to be updated

### ISSUE THREAD

**Issue by NuLogicSystems** [manjaro/packages-community#223]
Python-efl and all of the other efl based applications need to be update for the efl 1.18.0 release.

Also Elementary, evas generic loaders, and emotion generic player are now part of EFL 1.18.0.
This means that the dependencies of these packages need to be updated to reflect this change.

The following packages need to be removed from the repository as well:
elementary
evas_generic_loaders
emotion_generic_players
e_dbus (this was changed to el_dbus and added to efl some time ago)

Thanks,
James

**Comment by Ste74** [comment]
Hi James , i can update but can you point me on the pkgs ?

**Comment by NuLogicSystems** [comment]
Right now python-efl is the most important, some packages only depend on it, like econnman.

Some of the others depend directly on these three libs and need updated to depend directly on efl instead, like ecrir-git, ephoto-git, equate-git, etc.

Some have already been fixed upstream like terminology.

I'll need to search through the repos to find them.

**Comment by NuLogicSystems** [comment]
PS. The forecasts module needs to be updated from git and can now be set to depend on enlightenment without the version number. The modules abi has been stabilized.

**Comment by Ste74** [comment]
Ok , now update  python-efl :wink:

**Comment by NuLogicSystems** [comment]
cool

**Comment by Ste74** [comment]
You want take maintainer Enlightment ? :smile: 
python-efl done 8d7ffc6b0ba76f19f49615176e959f4a2deab94c

**Comment by NuLogicSystems** [comment]
No, not at the moment. I'm still playing with EFL to see if EGL (--with-opengl=es --enable-egl) might be a better option than GLX (--with-opengl=full --disable-egl).
