### ISSUE TITLE
[package request] elementary-xfce-icons

### ISSUE THREAD

**Issue by aadityabagga** [manjaro/packages-community#229]
Hi,

Would it be possible for someone to upload and maintain [elementary-xfce-icons](https://aur.archlinux.org/packages/elementary-xfce-icons)?

I could use them in the ```Xfce-OpenRC``` ISO.

Thx,
Aaditya

**Comment by oberon2007** [comment]
Sure, Aaditya, I'll do that with pleasure. :)

kind greetings
Bernhard

**Comment by aadityabagga** [comment]
Thx as usual Bernhard 🙂

**Comment by oberon2007** [comment]
You're welcome. I've already pushed the package through the branches.

greetings :)
