### ISSUE TITLE
Guaydeque 0.4.3 released

### ISSUE THREAD

**Issue by spsf64** [manjaro/packages-community#230]
Please update package

**Comment by oberon2007** [comment]
With pleasure if you can please point me to the source?

**Comment by oberon2007** [comment]
oh. I see. They seem to have migrated to github with the link on their homepage still pointing to the empty sourceforge...
Latest version is 0.4.3 btw.

**Comment by spsf64** [comment]
Sorry, my bad. Corrected title
Thanks for replying.

**Comment by oberon2007** [comment]
I have not been able to solve some dependency issues with this packae... Will keep trying.

**Comment by oberon2007** [comment]
https://github.com/anonbeat/guayadeque/issues/23

**Comment by spsf64** [comment]
@oberon2007 I am no expert in building packages, but I have been building from guayadeque-git and it woks perfectly. 
As both packages pull the same binary, I think you can use the -git to copy the instructions and build an stable package for manjaro?

**Comment by oberon2007** [comment]
Ah great! Yes, there's a helpful patch I can use, thanks! :wink:
