### ISSUE TITLE
[palemoon-bin] request update to 27.0

### ISSUE THREAD

**Issue by LER0ever** [manjaro/packages-community#231]
Palemoon 27.0 just released yesterday (11-22). The current version still got a lot of problems such as crashing on opening Github :(

**Comment by oberon2007** [comment]
Yes will do :smile: I had looked yesterday already but then there was still only the Windows version available. Now I see that they have provided the Linux tarball, too.

**Comment by LER0ever** [comment]
Thanks for the update! Waiting for package.
