### ISSUE TITLE
os-prober Win > vista

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#24]
Should we adopt this? https://bbs.archlinux.org/viewtopic.php?pid=1484092#p1484092

**Comment by philmmanjaro** [comment]
Why not. Also we should add Windows 10 to it too

**Comment by oberon2007** [comment]
fixed with https://github.com/manjaro/packages-community/commit/859e8b493c1dcb372ac140b8e8f3e1f9d05949c7

**Comment by oberon2007** [comment]
https://forum.manjaro.org/index.php?topic=24679.msg212801#msg212801
hmmm. ideas?

**Comment by oberon2007** [comment]
there is a version 1.66 meanwhile https://packages.debian.org/sid/os-prober
Will try it on my system ...

**Comment by oberon2007** [comment]
https://github.com/manjaro/packages-community/commit/e949ca875e85a06785f60829a6beb97e06faf15a
