### ISSUE TITLE
[FreeCAD] Please correct the Release and Revision # in Help > About FreeCAD

### ISSUE THREAD

**Issue by luzpaz** [manjaro/packages-community#249]
Thanks for maintaining the FreeCAD package. I was hoping it would be possible to correctly represent the fields in the About page (see attached). Essentially both the Revision and Release fields are defined as 'Unknowns'. This would really help the FC team to troubleshoot bugs more effectively.
Thanks!
![freecad-about](https://cloud.githubusercontent.com/assets/4140247/21958374/f75b00d8-da7a-11e6-84ee-4a5bbdb666a7.png)

ref: Downstream forum thread: http://forum.freecadweb.org/viewtopic.php?f=4&t=19903

**Comment by Ste74** [comment]
freecad is archlinux pkgs

**Comment by luzpaz** [comment]
> freecad is archlinux pkgs

![image](https://cloud.githubusercontent.com/assets/4140247/21958499/0c3bd9fc-da7e-11e6-8f35-26f148992b86.png)
Where does it say that?

**Comment by Kirek** [comment]
The vast majority of manjaro packages are untouched archlinux ones, that we sync periodically. We sometimes overwrite archlinux packages and add our own, but it's not the case of FreeCAD.
You should report the issue to the archlinux packagers https://www.archlinux.org/packages/community/x86_64/freecad/

**Comment by luzpaz** [comment]
@Kirek is there a way then you can indicate this via pacmac? The packages link you provided doesn't have a bugtracker link? 
I guess I'm looking for what I've been used to with AUR packages that have a forum thread associated with each package to be able to notify the maintainer. This is my first time opening a ticket for a Manjaro Community package (which in this case is really an archlinux package).

**Comment by luzpaz** [comment]
Also, what's the appropriate way to ping the manjaro maintainer that is in charge of syncing archlinux packages in to Manjaro Community ?

**Comment by Kirek** [comment]
I don't think it will be easy to add that, as afaik there isn't any metadata in the packages to indicate of it's a archlinux package or manjaro.
https://www.archlinux.org/packages/community/x86_64/freecad/, in the right side of the page, under Package Actions section, there is a "Bug Reports / Add New Bug" link, or you can go directly to bugs.archlinux.org

**Comment by Kirek** [comment]
We sync packages in the unstable branch at least once a day, sometimes more, no need to ask anyone.

**Comment by luzpaz** [comment]
>>> The vast majority of manjaro packages are untouched archlinux ones, that we sync periodically. We sometimes overwrite archlinux packages and add our own, but it's not the case of FreeCAD.  

>> is there a way then you can indicate this via pacmac?

> I don't think it will be easy to add that, as afaik there isn't any metadata in the packages to indicate of it's a archlinux package or manjaro.

I see. So in the future how do I ascertain if a package is archlinux or manjaro? Just open a ticket in this repo ?

**Comment by luzpaz** [comment]
I made an upstream ticket: https://bugs.archlinux.org/task/52553?events%5B0%5D=2&fromdate=&todate=&event_number=20&project=5&submit= but it was closed because they thought it was a manjaro package 👎

**Comment by Ste74** [comment]
closed via arch ticket reopened
https://bugs.archlinux.org/task/52553?events%5B0%5D=2&fromdate=&todate=&event_number=20&project=5&submit=

**Comment by luzpaz** [comment]
For Posterity:
The issue is the upstream in FreeCAD. They compile by pulling the repo down through git. Not the tarballs offered from github. So version.h doesn't get updated appropriately hence the lack of correct info in the Help > About FreeCAD > Copy to clipboard 

ref: Upstream ticket: http://forum.freecadweb.org/viewtopic.php?f=4&t=19903
