### ISSUE TITLE
Requesting 5 packages for the community repo

### ISSUE THREAD

**Issue by Neverest** [manjaro/packages-community#250]
1-Crossover - Is a paid version of a GUI wrapper to wine. Difference to playonlinux is that by buying a license you are directly supporting the wine devs.

https://aur.archlinux.org/packages/crossover/

2-Papirus theme - A flat icon set with hardcoded tray support, kde color support, libreoffice icon theme and others.

https://aur.archlinux.org/packages/papirus-icon-theme-git/

3-mate-indicator-applet - An applet to display information from various applications. The one in the AUR is orphaned, so here is the official github page:

 https://github.com/mate-desktop/mate-indicator-applet

4-Panther launcher - A fork of Slingshot launcher without Elementary dependencies

 https://aur.archlinux.org/packages/panther-launcher-git/

5-peek- An animated gif recorder

https://aur.archlinux.org/packages/peek

**Comment by Ste74** [comment]
Uhmm .. to adopt pkgs into our repo we need more reasons not a simply list  ... in my view i'm interested on mate indicator applet but others ?  I like if you debate this in our community ..

**Comment by oberon2007** [comment]
We always have to watch out that we don't have too many packages to maintain.
The rule we have established is that normally we adopt only packages needed by our editions. So if for example Stefano decides that he wants to use **mate-indicator-applet** in the mate community edition, that's a reason to adopt the package in the repo. This also especially applies for themes of any kind. The range of choice there is just endless - and tastes differ so much. There is just no reason why people shouldn't just install that stuff from the AUR and why we should maintain that.
Commercial software is a no-go for me in the repos.

**Comment by FadeMind** [comment]
Papirus development is weird. In 2016 I created PKGBUILDs and proper makefiles for easy installs. NOW all is gone (formally moved in other place, makefiles were removed) (I purged from AUR lots of papirus splited packages recently via PR). 

@Ste74 @oberon2007
