### ISSUE TITLE
steam-native dependency on pulseaudio-alsa

### ISSUE THREAD

**Issue by vfjpl** [manjaro/packages-community#258]
Hello. Now steam-native have dependency on pulseaudio-alsa. However steam is perfectly able to run without pulseaudio. So my request is to move pulseaudio-alsa into optional dependency.

**Comment by Tids** [comment]
Steam-native is a switch to make use of the native libraries. We have to provide everything that steam also shipps by itself. So we can not set anything as optional dependency.
