### ISSUE TITLE
adwaita-maia-gtk3 : modifications

### ISSUE THREAD

**Issue by Ste74** [manjaro/packages-community#264]
@Kirek , @oberon2007 and @korrode 
Do you think ?  
https://forum.manjaro.org/t/about-adwaita-maia-gtk3/14442/22

**Comment by oberon2007** [comment]
What exactly was the question here?

**Comment by Ste74** [comment]
Add some configuration with the maia theme but I'm not sure if the effort is worth the result.. 
I forgot this..

**Comment by Ste74** [comment]
No time to invest on it
