### ISSUE TITLE
[faenza-icon-theme] Reboot icon in Xfce logout dialogue resets to default

### ISSUE THREAD

**Issue by Photon89** [manjaro/packages-community#27]
The bug has been fixed upstream, please implement!

https://bugs.archlinux.org/task/44555

Might also affect faenza-green-icon-theme.

**Comment by oberon2007** [comment]
Young and over-motivated as I am, I could do that tonight if there are no objections ;)
Are there any new manjaro-icons that should go into a new package, maybe?

**Comment by oberon2007** [comment]
Ah, I see, it's just the standard icon. So I guess it remains what it is.
Do want to keep/renew faenza-green?

**Comment by Photon89** [comment]
Thanks for the quick reply! I don't know which of the Faenza packages are affected, to be honest, since I'm only using faenza-icon-theme. :)

**Comment by oberon2007** [comment]
https://github.com/manjaro/packages-community/commit/b3c43cef97f6ce496a5fe6ebbb0041223e62827d

**Comment by Photon89** [comment]
Perfect, thx!

**Comment by oberon2007** [comment]
done. ::)
