### ISSUE TITLE
[thunderbird-kde] File name disappears after choosing directory in Save dialogue

### ISSUE THREAD

**Issue by Photon89** [manjaro/packages-community#274]
Bug reported here (German thread): https://forum.manjaro.org/t/community-thunderbird-vergisst-dateinamen-beim-abspeichern-von-e-mails-etc/18936

Short translation of the problem: When saving an email, the Save dialogue is opened and a file name proposal is already entered in the corresponding field. However, when selecting a different folder, the file name field is emptied.

**Comment by oberon2007** [comment]
Is this still an issue?

**Comment by philmmanjaro** [comment]
We removed the package
