### ISSUE TITLE
Gratz on breaking TrueCrypt/Veracrypt Support and entire "Mounting" aspect of Manjaro..... Genius move....

### ISSUE THREAD

**Issue by NovaCygni** [manjaro/packages-community#278]
/dev/mapper/control: open failed: No such device
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper 1.02.137 (2016-11-30) and kernel driver (unknown version).
Command failed

Neither TrueCrypt nor VeraCrypt work anymore... Bravo.... great move!

**Comment by NovaCygni** [comment]
Btw this applies to anyform of mounting, seems anything that tries to mount "Containers", partitions or devices outright works..... smooth move....

**Comment by philmmanjaro** [comment]
I don't know what you mean. The package **device-mapper v2.02.168-1** was added on the **2016-12-06** to Archlinux and merged most likely on the same day to our **unstable** branch. So to the package **lvm2** were [no further changes done](https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/lvm2) so far. Please post your **/var/log/pacman.log** for further analysis what might had changed on your end.

**Comment by philmmanjaro** [comment]
Also none of our developers use **TrueCrypt/Veracrypt** for encryption. We simply don't care much about it from our end.

**Comment by NovaCygni** [comment]
http://pastebin.com/

Yeh I gathered that, you may also want to sort out the "Sha1" issue aswell :/

**Comment by philmmanjaro** [comment]
Is this a rant or what is the issue with you? I simply don't get it ...

**Comment by NovaCygni** [comment]
Log file: https://www.sendspace.com/file/fod9cm As pastebin keeps dying on me.
Also Sha1 was broken last month is should be replaced. An nope you guys pushed a update that breaks stuff, I report it...

**Comment by philmmanjaro** [comment]
I've no time for this BS. Your log ends in **2016**:

```
[2016-11-17 00:29] [ALPM-SCRIPTLET] Using rainbow 2.1.0
[2016-11-17 00:29] [ALPM-SCRIPTLET] Using ref 2.0.0
[2016-11-1
```
Simply post only the snippet of the date your system worked and the update which had broken your system. We simply can't test all. About **sha1**. There might be someone who were able to break it. **md5** was hacked a long time ago, however still part of a Linux distribution. Therefore **sha1** will exist a long time. The application is not broken only the usage is not recommended anymore due given reasons. Also https://gist.github.com can be used if **pastebin** doesn't work for you ...

**Comment by NovaCygni** [comment]
Todays changes...
http://pastebin.com/J8c6TkXG

And yeh I still see people using md5, and its not used for anything anymore as people with half a braincell know Md5 can be cracked in minutes on a mobile phone let alone a proper PC... Sha1 is only recently cracked but again, doesnt require to much hardware to break, and should be replaced ideally ASAP.

**Comment by philmmanjaro** [comment]
Other than this nothing catches my eye creating issues: `[2017-03-22 15:13] [ALPM] upgraded cryptsetup (1.7.3-1 -> 1.7.4-1)`. When exactly did you noticed the breakage and how?

**Comment by NovaCygni** [comment]
I dismounted the Mounted container to replace it with a different one, as I commonly do, Then mounting fails with the message posted above. Are you sure the kernel has been built the same as the others before?

**Comment by NovaCygni** [comment]
Downgrading Kernel to old version fixes the problem... either libdevmapper 1.02.137 isnt compatible with the new kernel or something got b0rked on the compile.

**Comment by philmmanjaro** [comment]
Which kernel series is affected?
