### ISSUE TITLE
Menulibre does not work in Python 3

### ISSUE THREAD

**Issue by alarangeiras** [manjaro/packages-community#28]
Menulibre does not open after a fresh install.
The solution is edit manually the file /usr/lib/python3.4/site-packages/menulibre/util.py and change the instruction psutil.get_pid_list() for psutil.pids().
The project is aimed to Python 2 then I think the best solutions is do a fork.
Can I help with that?

**Comment by philmmanjaro** [comment]
Hi Allan,

yes, why not. We are happy for any fixes. What would be the quick fix for the current issue?

**Comment by alarangeiras** [comment]
Hi, 

I researched the problem better and realized three solutions:
- We can make a fork of the last release menulibre available in PPA repository (2.0.6). The project seems to receive no updates since September 2014.
- We can downgrade the lib psutil to version 1.2.1 which still shows compatible with menulibre. However, I think this is a risky option as it could break the operation of other applications
- I left a comment on menulibre creator's blog about this issue. There are chances this correction can be incorporated directly into the original code.

**Comment by philmmanjaro** [comment]
Please check if [2.0.7](https://launchpad.net/menulibre) fixes the issue.

**Comment by alarangeiras** [comment]
Yes, I think this will solve the problem.
Are you a menulibre commiter? This release was made 8 hours ago.

Thanks
