### ISSUE TITLE
New versions of Guayadeque and Dropbox

### ISSUE THREAD

**Issue by spsf64** [manjaro/packages-community#281]
Please update packages in repos as they are older than in AUR.
If I update from aur I get warnings from pacman and pamac about package being newer than the ones from the repo...

Guayadeque 0.4.5 https://github.com/anonbeat/guayadeque/releases
https://aur.archlinux.org/packages/guayadeque/

Dropbox 22.4.24-1 https://aur.archlinux.org/packages/dropbox/

Thank you

**Comment by ThanosApostolou** [comment]
Guayadeque 0.4.5 and Dropbox 25.4.28 are now on unstable branch 😄
