### ISSUE TITLE
firefox-kde use the KF5 port of kmozillahelper?

### ISSUE THREAD

**Issue by ahjolinna** [manjaro/packages-community#30]
I wonder does the current version of firefox-kde use the kf5 port of kmozillahelper? :
https://github.com/cruiseliu/kmozillahelper-frameworks
https://aur.archlinux.org/packages/kmozillahelper-frameworks/

PS. firefox 40 just arrived, plz update

**Comment by Kirek** [comment]
No it uses the kde4 libs version, I will check the kf5 version when I have time.

I will update firefox-kde 40 tomorrow.

**Comment by ahjolinna** [comment]
@Kirek : firefox-kde 40.0.3 is not using the native file dialog (dolphin) anymore, after dolphin-kf5 port arrived.

**Comment by Kirek** [comment]
In my system is still using the kde dialog, firefox 40.0.3 or 40.1

**Comment by ahjolinna** [comment]
apprently I didn't notice that the latest update had changed my firefox-kde to the normal firefox...for some reason
