### ISSUE TITLE
[purple-facebook]Please update to 0.9.3 since 0.9.0 is non-functioning

### ISSUE THREAD

**Issue by Photon89** [manjaro/packages-community#303]
Pull from https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/purple-facebook&id=4133a6f0853b9da8304acf1e0982b0102943cd84

**Comment by Ste74** [comment]
Oh , i remove from our overlay , thank you :smile

**Comment by Ste74** [comment]
Done 😄 
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170501/011173.html

**Comment by Photon89** [comment]
So, does it mean that now the package from Arch will be taken over?

**Comment by Ste74** [comment]
Yes , at the next update for unstable

**Comment by Photon89** [comment]
Cool, thanks for the quick solution! :)
