### ISSUE TITLE
[telegram-purple] needs an update or rebuild.

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-community#305]
See also [here](https://forum.manjaro.org/t/testing-update-2017-05-10-kernel-virtualbox-haskell-gnome/23426/21).

**Comment by Ste74** [comment]
Is a Sonar pkgs .. @oberon2007 already ask https://github.com/manjaro/packages-community/pull/304 .. state of Sonar ?

**Comment by oberon2007** [comment]
Ok. I see now that it is still on pkgs list of the sonar gnome-edition...
So the question is, is this ISO actually built by anyone like that? and also, does it really need twitter support by default? ;)

**Comment by philmmanjaro** [comment]
If we don't need it, then we NAK it and remove it from our binary repository. Somebody might shout anyway when it is gone :smile_cat:

**Comment by oberon2007** [comment]
yeah. 😉  that's exactly what I already did as mentioned in https://github.com/manjaro/packages-community/pull/304

**Comment by Ste74** [comment]
We see who ask it after ..

**Comment by Ste74** [comment]
Removed binary from our [overlay](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170508/011271.html)

**Comment by oberon2007** [comment]
Oh strange. Seems I forgot to actually remove the pkg 😉 Thanks @Ste74
