### ISSUE TITLE
[liri-browser] remove liri browser

### ISSUE THREAD

**Issue by FabioLolix** [manjaro/packages-community#306]
Please remove this zombie package

* alpha state
* development repository has moved 
* qml-material dependency has been removed from AUR (superseded by fluid-git) so can't be installed

It is in fact not a stable release but a git version, superseded by liri-browser-git
I'm going to ask removal from AUR too

**Comment by Ste74** [comment]
Done https://github.com/manjaro/packages-community/commit/849d13f3c064a52e3ebd9f9adb092ddaec6f43aa
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170508/011269.html
