### ISSUE TITLE
Powerpill PKGBUILD

### ISSUE THREAD

**Issue by guinux** [manjaro/packages-community#307]
lacks for python-xdg as dependency

**Comment by oberon2007** [comment]
A new version is available, however the original PKGBUILD doesn't list **python-xdg** either.

**Comment by oberon2007** [comment]
@Ste74 maybe you wanna give **v2017** a try?

**Comment by Ste74** [comment]
Hi , this evening i can do :) .. not at home now..

**Comment by Ste74** [comment]
@guinux just now in unstable , check it 😉 https://github.com/manjaro/packages-community/commit/5f77fca32b1175087ee7bfe00a7fe8c52dc65d80
 otherwise explaine why add python-xdg 😄

**Comment by guinux** [comment]
Powerpill simply doesn't start without python-xdg installed. It complains about xdg missing module.

**Comment by Kirek** [comment]
python-xdg is installed as a dependency of python3-xcpf in the aur, but our python3-xcpf package is missing this dependency. @Ste74 https://github.com/manjaro/packages-community/blob/master/powerpill/python3-xcpf/PKGBUILD https://aur.archlinux.org/packages/python3-xcpf/

**Comment by Ste74** [comment]
Damn , you are right , i have to add on python-xcpf this depends.. strange, i have build with clean chroot so xyne not implement a check for depends needed so when i build the pkglist for powerpill i don't see error :(
Thank you rebuilding the python-xcpf with python-xdg as depends ;)

**Comment by Ste74** [comment]
Yep , @Kirek i see ;p

**Comment by Ste74** [comment]
:( @Kirek , last update for me break the boxit access and also pamac .. 
`boxit: error while loading shared libraries: /usr/lib/libQtDBus.so.4: file too short`

what this ?

**Comment by Ste74** [comment]
Force remove of qt4 and force installing seem solve my issue o_O
btw add depends https://github.com/manjaro/packages-community/commit/59ae995c0d7d8ed49e9bf6983be47c5c41277ed9
