### ISSUE TITLE
How to update manjaro logo in i-nex?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#312]
Where does **i-nex** pick up this logo??

![](http://imgur.com/XSm04dal.png)

Any idea @FadeMind ? @philmmanjaro

**Comment by FadeMind** [comment]
It is hard coded during compile.

https://github.com/i-nex/I-Nex/blob/master/I-Nex/i-nex/Database/Distlogos/manjaro.png

**Comment by oberon2007** [comment]
Ah thanks! I will send them a PR with an update then :)

**Comment by oberon2007** [comment]
https://github.com/i-nex/I-Nex/pull/76

**Comment by FadeMind** [comment]
@oberon2007  merged

**Comment by oberon2007** [comment]
Great, thanks! 👍 Time for a new package then 😉
