### ISSUE TITLE
compiz-manjaro: ccsm error

### ISSUE THREAD

**Issue by ThanosApostolou** [manjaro/packages-community#315]
I'm getting this error when I run **ccsm** from terminal:
```
[thanos@thanos-pc ~]$ ccsm
Traceback (most recent call last):
  File "/usr/bin/ccsm", line 93, in <module>
    import compizconfig
ImportError: libprotobuf.so.12: cannot open shared object file: No such file or directory
```
I see that **protobuf** package has been updated recently and it has the file **libprotobuf.so.13**. So maybe **compiz-manjaro** needs a rebuild?

**Comment by philmmanjaro** [comment]
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170522/011385.html
