### ISSUE TITLE
[lightdm-slick-greeter] Background and password box

### ISSUE THREAD

**Issue by SamBurgos** [manjaro/packages-community#321]
Greetings, I want to let you know that with version 1.0.5 of lightdm-slick-greeter there are problems with the greeter not loading the background, also some of your users might report that the password box is truncated so they might see it weird in that case, is it possible that you can upgrade to version 1.0.6? (I just did it on AUR as well).

You can check the bug reports from both problems on the following links: [Not loading background file](https://github.com/linuxmint/slick-greeter/issues/34) and [truncated password box](https://github.com/linuxmint/slick-greeter/issues/33)

Before (version <= 1.0.5)
https://cloud.githubusercontent.com/assets/1509924/26558912/6304f606-4469-11e7-8b72-e0ffaea74c9f.png

After (version 1.0.6)
https://cloud.githubusercontent.com/assets/1509924/26589770/1d82562a-4516-11e7-9457-adb89ddd8c9f.png

**Comment by Ste74** [comment]
Hi @SamBurgos , sorry for delay , sure tonight i update the version 😉 . Thank you for report it 😄

**Comment by Ste74** [comment]
Close via https://github.com/manjaro/packages-community/commit/2183d6100a881b57b2a124101492607f8890e51d
