### ISSUE TITLE
[package request] lightdm-settings

### ISSUE THREAD

**Issue by SamBurgos** [manjaro/packages-community#322]
Greetings, for any version of Manjaro that you may have available, is it possible to add lightdm-settings? I don't know if you are planning on using the lightdm-slick-greeter on any of those versions, but if you do it will be great to add that tool as a companion and as a GUI-way to configure slick-greeter without getting into dconf or command line

**Comment by Ste74** [comment]
I not checked it before but i can consider it 😄

**Comment by Ste74** [comment]
Uhmm  i wait upstream to add the proper way to open ( pkexec or other polkit rules )

**Comment by SamBurgos** [comment]
is the python-xapp library not useful for you? From the looks of upstream seems like they want to standarize their applications via that library so that distros can choose if gksu or polkit is needed (depending on what is installed), however they decided to go against polkit on Mint particularly because they wanted to localize the pkexec message and it is something that they couldn't achieve on time

Perhaps you may try to use something from [this commit](https://github.com/linuxmint/lightdm-settings/commit/2ce15c3b81e2f2a33048f78cd35bb78801f18544), try to reverse it so it can use pkexec instead of relying on the python-xapp library.

**Comment by Ste74** [comment]
I forgot this 😜 .. let me see how work .. try to build in my side to see 😄 . Thank you for your effort

**Comment by SamBurgos** [comment]
No problem @Ste74 , I will be eager to know of any update on this so I may either to update the package on my side to stop relying on the library (on Arch and derivatives it would be better off to rely on pkexec) or keep it the way I actually have it on AUR (which for now means to rely and pull gksu as a dependency)

As an off-topic, is there any other way to get in touch with you besides here, if you don't mind my question?

**Comment by Ste74** [comment]
If not misunderstanding your question you can use the [e-mail](stefano@manjaro.org)

**Comment by Ste74** [comment]
@SamBurgos add via this https://github.com/manjaro/packages-community/commit/616e68ad412c18f583faf51fb80fa2d100449e50 . Please see the makedepends and depends : i have changed a bit in according with fedora's specifications 😉

**Comment by SamBurgos** [comment]
So far everything is good, the only thing that might give some problems is the python-xapp library since it hasn't been updated to reflect the changes on the code ([one of the commits](https://github.com/linuxmint/python-xapp/commit/4e3f14e918cc79f5e70ccef90a8976ccf89bcc01) actually forces pkexec as a last effort), specially since without gksu it might not run at all. Besides that, so far everything seems good to me though some dependencies like python-gobject, gettext and desktop-file-utils I am not really sure if they are needed or not, but it wouldn't hurt to keep them there (and also you just gave me some work to update dependencies and PKGBUILD as well 😄 )

Perhaps you are going to teach me some of those specifications as well, since I am kind of new to those, honestly  :sweat_smile:

**Comment by Ste74** [comment]
Yep , python-xapp readme not provide any info so i searched on opensuse or fedora if have add this packages and i found in fedora so i have see the build and depend required .. and no  sense add in depend lightdm in lightdm-settings because slick already as a dependence and also for this i have opend the depends and build depends needed in fedora project .. maybe Clemente missed to write the list for build the packages. 
Sure ping me if needed and also if pkgs have to update 😄

**Comment by SamBurgos** [comment]
I am on general Manjaro IRC channel, perhaps we can check and discuss about those packages, but I cannot find you

**Comment by Ste74** [comment]
Yep , im out , if you want tomorrow can connect on IRC . I'm on Italy and now is 23.00 .. i need to go a sleep otherwise tomorrow i'm zombie at my real work

**Comment by SamBurgos** [comment]
Greetings, yesterday I updated the dependencies on lightdm-settings and python-xapp as well as the origins (with python-xapps now it points to github instead of linuxmint), also you can check the updated PKGBUILD of[ python-xapp](https://github.com/SamBurgos/Sam-PKGBUILD/blob/master/PKGBUILD-python-xapp) and [lightdm-settings](https://github.com/SamBurgos/Sam-PKGBUILD/blob/master/PKGBUILD-lightdm-settings). 

Now the only thing remaining is either wait for upstream to update python-xapp to default to pkexec or to install gksu/kdesu (which is something I don't like that much), without any of those options available any program that relies on that library will possibly give errors.

As of my home zone, mine is El Salvador, and if I am not mistaken we have a difference of 8 hours between Italy and my country, also I take some available time on my real job as you do in order to check, update and work with some code (looking to learn Python and Gtk) and the many PKGBUILD that I maintain on Arch, but like I said before I am willing to work with you guys in order to standarize the PKGBUILD so any Arch and derivatives like Manjaro/Antergos can benefit from that

**Comment by Ste74** [comment]
This enable the pkexec rules .
https://github.com/manjaro/packages-community/commit/46be6549c54dfe5c0cbf9c54178ba39f136a6832

**Comment by Ste74** [comment]
Close this request ;)
