### ISSUE TITLE
Compare-Mirrors updated

### ISSUE THREAD

**Issue by joshuastrot** [manjaro/packages-community#331]
Compare-Mirrors was updated to include licensing information. Please update accordingly.

https://github.com/joshuastrot/compare-mirrors/commit/d58b31881b9ddc0fd51d5f67c2ffc7fb6f54fc53

**Comment by Ste74** [comment]
Done https://github.com/manjaro/packages-community/commit/456c81d85b3c668a17527c9ffb9b54e16d3ac859
