### ISSUE TITLE
arc-icon-theme and arc-maia-icon-theme need moka-icon-theme in order to be complete. 

### ISSUE THREAD

**Issue by ThanosApostolou** [manjaro/packages-community#332]
See the panel's icons in screenshots
**arc-maia-icon-theme** without **moka-icon-theme**:
![virtualbox_manjaro lxde_24_06_2017_16_40_15](https://user-images.githubusercontent.com/21288843/27509039-2c534930-58fc-11e7-883d-2c70e9ba12ed.png)

**arc-maia-icon-theme** with **moka-icon-theme** installed:
![virtualbox_manjaro lxde_24_06_2017_16_41_16](https://user-images.githubusercontent.com/21288843/27509041-3fe5cd4c-58fc-11e7-8239-d3e00260ef21.png)

moka-icon-theme is stated as requirement on arc-icon-theme github page and I believe that it should be added as dependency for **arc-maia-icon-theme**. Otherwise, it uses the gnome-icon-theme and it doesn't look as it should be. Furthermore, a user who is using any of the arc-maia or arc icon themes, if he installs moka-icon-theme then he will see that his icon theme will change, which isn't appropriate behavior.

@Ste74 I see that you are the packager of arc-maia-icon-theme, so it would be nice if you can add it as dependency. I left a bug report for that at arch's' arc-icon-theme package, but moka-icon-theme isn't included in arch, so I don't know if they are willing to do this. So, maybe you can build arc-icon-theme as well to manjaro's repositories and add moka-icon-theme as dependency there too?

**Comment by Ste74** [comment]
Done https://github.com/manjaro/packages-community/commit/ccd37681688a6b7da64b2cd45aea4d66fccaad93 , you are right , no reason to not include in the icon package ...  for the regular arc-icon-theme we will see if you obtain an answer otherwise why not ...

**Comment by Ste74** [comment]
Pfff today found time to modify the pkgbuild so now both icon theme install moka 😉 https://github.com/manjaro/packages-community/commit/28a2a821ac7c52eeb9f8d783cb3a7b9c44cf93e5
if arch provide the variant we remove the regular file 😄
