### ISSUE TITLE
jade-desktop-git new PKGBUILD

### ISSUE THREAD

**Issue by codesardine** [manjaro/packages-community#334]
Hi @philmmanjaro the version i had on master was actually outdated and a few things there was only for my personal testing, that was removed in my last commit including baobab dependency, leaving just what is stable.

Everytime i commit to my repo does manjaro build system  picks that up and builds a new package Or do I have to push a new PKGBUILD here, how does it work?

New PKGBUILD 

_pkgname=jade-dashboard
pkgname="$_pkgname-git"
pkgver=0.3.25
pkgrel=6
pkgdesc="JADE, a linux desktop built with HTML5, CSS, JavaScript and Python."
arch=('any')
url="https://github.com/codesardine/Jadesktop"
license=('GPL')
makedepends=('git')
depends=('python-jade-application-kit' 'jade-menu-data' 'python-xdg')
optdepends=('paper-icon-theme-git')
provides=("jade-dashboard")
replaces=('jade-dashboard')
source=("$_pkgname"::"git+$url.git")
md5sums=('SKIP')

pkgver() {
    cd "$_pkgname"
    (
        printf "$pkgver.r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
    )
}

package() {
    cd "$_pkgname"
    cp -r $srcdir/$_pkgname/usr $pkgdir/
    cp -r $srcdir/$_pkgname/etc $pkgdir/
    mkdir -p "$pkgdir/opt/jade"
    cp -r $srcdir/$_pkgname/jade $pkgdir/opt
    chmod 644 $pkgdir/etc/xdg/autostart/jade-dashboard.desktop
    chmod 644 $pkgdir/usr/share/applications/jade-dashboard.desktop
    chmod 755 $pkgdir/usr/bin/jade-dashboard
}

**Comment by Ste74** [comment]
Simply open a PR with the change and we merge it and build 😄

**Comment by codesardine** [comment]
Ok 
Tanks for adding my package it made me happy.

**Comment by Ste74** [comment]
Ah ah , 😄 @philmmanjaro idea 😉
