### ISSUE TITLE
[Package Request] adapta-breath-theme

### ISSUE THREAD

**Issue by ceyhunnabiyev** [manjaro/packages-community#336]
Hi @Ste74 ,
Can you add adapta package with breath colors?
In my opinion, Adapta-Breath looks cooler than Adapta-Maia, even with Arc-Maia icons.
I manually install Adapta with Breath Colors for Manjaro Gnome 17.0.2 as follows:
```
./autogen.sh --disable-cinnamon --disable-unity --disable-xfce --disable-mate  --disable-openbox  --enable-telegram --with-selection_color=#1abc9c --with-second_selection_color=#2fe2bf --with-accent_color=#2fe2bf --with-suggestion_color=#1abc9c 
make 
sudo make install 
```

**Comment by Ste74** [comment]
Hi , i have try your tweak , i like it 😄 . The color is the same of our `breath theme` ?

**Comment by ceyhunnabiyev** [comment]
Yes,  you can see selection color here :
https://github.com/manjaro/artwork-breath-gtk/blob/master/Breath-Dark/gtk-3.20/gtk.css

**Comment by Ste74** [comment]
Perfect . Let me build it 😉

**Comment by Ste74** [comment]
@oberon2007 do you think if build also the regular gtk theme ? Hope you understand this in italian : `Abbiamo fatto 30 facciamo 31`

**Comment by oberon2007** [comment]
Uhm. What do you mean with 'regular gtk theme'? What packages will we have now?
community/adapta-gtk-theme
community/adapta-maia-theme
community/adapta-breath-theme
?

**Comment by Ste74** [comment]
Yep , three version .. adapta-gtk-theme is the original theme..

**Comment by Ste74** [comment]
close via https://github.com/manjaro/packages-community/commit/082d9698df4385993e5ad94cd7ce149c70c0251e

**Comment by ceyhunnabiyev** [comment]
Thanks a lot, @Ste74 , but please don't  add option `--enable-chrome` , users confuse it, because Adapta doesn't need this, in your all Manjaro Branches  chrome version is 59.
You can see details here:
https://github.com/adapta-project/adapta-gtk-theme#extra-browser-support

**Comment by Ste74** [comment]
Argh , damn it , i 'm blind .. this evening rebuild it without this key :p

**Comment by ceyhunnabiyev** [comment]
@Ste74, @oberon2007 ,
If you want to use breath color for famous arc-theme, I have following colors for this:
```
_breath=1abc9c
_breath1=148f77
_breath2=18ab8e
_breath3=2fe2bf
_breath4=5ce8cd
_breath5=1bc3a2
_breath6='26, 188, 156'
_breath7='11, 57, 103'
_breath8=00fcc9  
_breath9=00f7c5
_breath10=009964
_breath11=28e1bd
_breath12=2fe2bf
_breath13='11, 103, 57'
_breath14=62e9cf
_breath15=40e5c4    
_breath16='11, 103, 57, 0.95'
_breath17='11, 103, 57, 0.8'
_breath18='26, 188, 156, 0.9' 
 
```
Generally I get errors in installation  of arc-theme, that's why I can't test it. However if you want, you can test it yourself. If you don't like any colors of these, I will change it, or you can specify what  you want.

**Comment by Ste74** [comment]
For adapta-breath-theme done via https://github.com/manjaro/packages-community/commit/d1dffbd543a0233b3570dcc180829b5547322752

what error you encounter in the arc-theme variation ?

**Comment by ceyhunnabiyev** [comment]
@Ste74 ,  could you please help me  how to  install from your pkgbuild manually?

**Comment by oberon2007** [comment]
@ceyhunnabiyev simply navigate to the PKGBUILD and run `makepkg -si`

**Comment by Ste74** [comment]
I suggest also `-sri` to reomve the un needed dependence after building 😜

**Comment by ceyhunnabiyev** [comment]
@Ste74 , @oberon2007 ,  
Arc theme with Breath Color:
![screenshot-20170719234930-1364x696](https://user-images.githubusercontent.com/5506156/28386843-f0aa0400-6cdd-11e7-8a96-644788bae9e2.png)
![screenshot-20170719235223-1365x701](https://user-images.githubusercontent.com/5506156/28386854-fa7698fe-6cdd-11e7-84be-b8e80111b416.png)

**Comment by Ste74** [comment]
Thank you 😄 i think we can give one chance also at this variant ..

**Comment by oberon2007** [comment]
👍 I like it a lot! YES PLEASE!

**Comment by ceyhunnabiyev** [comment]
@Ste74 , @oberon2007 ,
This is Firefox Arc theme with Breath Color:
![screenshot-20170720095634-1365x256](https://user-images.githubusercontent.com/5506156/28403376-7d9f2848-6d35-11e7-99f8-19b73e5cd5e3.png)
[PKGBUILD.zip](https://github.com/manjaro/packages-community/files/1161354/PKGBUILD.zip)

That is all,
Thanks for your attention,
Great Team, Great Work,
Sincerely,
Jeyhun..

**Comment by Ste74** [comment]
Let me rework the pkgbuild and merge it .. only .. i have to see if arc theme for firefox is needed because mozilla drop t he theming support :(

**Comment by ceyhunnabiyev** [comment]
@Ste74 , I think, generally  following code is more recommended in order to avoid  some unneeded arc-theme supports for Manjaro:

` ./autogen.sh --prefix=/usr --disable-unity --with-gnome=3.22`

![screenshot-20170720114444-967x381](https://user-images.githubusercontent.com/5506156/28406273-e2bb05de-6d40-11e7-9ddd-a6de3d410ed4.png)

**Comment by Ste74** [comment]
Arc-themes modified to build both maia and breath version : https://github.com/manjaro/packages-community/commit/563c8a861c8aa33a03ddff3e22eac5094c308aa6
for firefox theme we will see if upstream continue the development or if is dead , i backupped your pkgbuils ;)

**Comment by ceyhunnabiyev** [comment]
Pleasantly I will wait next Stable Branch Update for this, thanks a lot...

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74, I see some broken symbolic links in Adapta Folders. Please remove unneeded   ln -s lines from PKGBUILD...

Best Regards,
Jeyhun

**Comment by Ste74** [comment]
@ceyhunnabiyev where ? You talk about symbolic link for unity ?

**Comment by ceyhunnabiyev** [comment]
@Ste74 , 

![screenshot-20170728005133-497x465](https://user-images.githubusercontent.com/5506156/28691807-4a95a198-732f-11e7-8e56-87da164fc556.png)
![screenshot-20170728005226-521x426](https://user-images.githubusercontent.com/5506156/28691828-5aba5370-732f-11e7-82f8-35540ba77d93.png)
![screenshot-20170728005318-522x428](https://user-images.githubusercontent.com/5506156/28691854-6e50c2d4-732f-11e7-8663-b383ac0c3d7a.png)

This problem is also related to Adapta-Maia

**Comment by Ste74** [comment]
You have download the last pkgs from our repo ?
```
~ >>> pacman -Qi adapta-breath-theme                                                                 [1]
Nome                      : adapta-breath-theme
Versione                  : 3.91.0.229-2
Descrizione               : An adaptive Gtk+ theme based on Material Design Guidelines.Build with Manjaro
                            Breath color
Architettura              : any
URL                       : https://github.com/adapta-project/adapta-gtk-theme
Licenze                   : GPL2  CCPL
Gruppi                    : Nessuno
Fornisce                  : Nessuno
Dipenda da                : Nessuno
Dipendenze opzionali      : ttf-roboto: The recommended font
                            noto-fonts: The recommended font for improved language support [installato]
                            gtk-engine-murrine: for gtk2 themes [installato]
Richiesto da              : Nessuno
Opzionale per             : Nessuno
Conflitti con             : Nessuno
Sostituisce               : Nessuno
Spazio richiesto          : 17,99 MiB
Pacchettizzatore          : Stefano Capitani <stefano@manjaro.org>
Data di creazione         : mer 19 lug 2017 19:21:00 CEST
Data di installazione     : mer 19 lug 2017 21:58:23 CEST
Motivo dell'installazione : Installato esplicitamente
Script di install         : No
Convalidato da            : Firma
```
I can't reproduce it .. my symlink are right ...

**Comment by ceyhunnabiyev** [comment]
@Ste74 , I have latest build. Please look at the following and I am sure that  you will understand what I am saying. 
[PKGBUILD.zip](https://github.com/manjaro/packages-community/files/1185128/PKGBUILD.zip)

Your some symbolic links aren't correct.

**Comment by Ste74** [comment]
Ok, i'm not at home now, tomorrow looking into it ;) 

---

Greetings
Stefano Capitani

Il 29/07/2017 20:09 ceyhunnabiyev ha scritto: 

> @Ste74 [1] , I have latest build. Please look at the following and I am sure that you will understand what I am saying.
> PKGBUILD.zip [2] 
> 
> Your some symbolic links aren't correct. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].
 

Links:
------
[1] https://github.com/ste74
[2]
https://github.com/manjaro/packages-community/files/1185128/PKGBUILD.zip
[3]
https://github.com/manjaro/packages-community/issues/336#issuecomment-318848265
[4]

**Comment by Ste74** [comment]
Fixed https://github.com/manjaro/packages-community/commit/86ae1e6499e15b569bd73a709c9d05a6aba189d4
:)

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74 , 
Please, please  update Adapta-Breath  to version [3.91.2](https://github.com/adapta-project/adapta-gtk-theme/releases) for [this issue](https://github.com/adapta-project/adapta-gtk-theme/issues/483). 

This release fixes [my issue](https://forum.manjaro.org/t/slow-reading-from-hard-drive/29111) a little bit, because  other themes (especially arc-theme) faster than this theme on me, but I love Adapta-Breath..

**Comment by Ste74** [comment]
Hi @ceyhunnabiyev , i can't do this before 22/8 ( next week ) because i'm out ; i can't use my pc ( holiday time ) .. @oberon2007 , @Chrysostomus , feel free to update if find time :)

**Comment by oberon2007** [comment]
No problem. I'll update to **3.91.2.35** then :)

**Comment by ceyhunnabiyev** [comment]
Thanks a lot..

**Comment by oberon2007** [comment]
on unstable branch now :)

**Comment by ceyhunnabiyev** [comment]
Thanks.. You are the best. Pleasantly  I will wait Stable Branch Update..

**Comment by oberon2007** [comment]
You're welcome :) You can install it directly already with
``sudo pacman -U https://manjaro.ipacct.com/manjaro/pool/overlay/adapta-breath-theme-3.91.2.35-1-any.pkg.tar.xz``

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74 , @oberon2007 ,
Sorry for wasting your time, but **Adapta Important Version** released out  right now:
![screenshot-20170828125314-1006x311](https://user-images.githubusercontent.com/5506156/29766472-eac9512c-8bef-11e7-93fb-fee2e7daba2c.png)

Please update Adapta-gtk-theme to version 3.91.2.109..

**Comment by Ste74** [comment]
Done
https://github.com/manjaro/packages-community/commit/4d1aca42ca41c3839c17d1d69475e0dc8a6555e9
thank you ;)

**Comment by ceyhunnabiyev** [comment]
And thank you too to pay attention to my requests :)

**Comment by Ste74** [comment]
I can't see all update of my pkgs so i'm happy if somebody warning me 😉

**Comment by ceyhunnabiyev** [comment]
Can I install directly, without waiting Stable Branch Update ?

**Comment by Ste74** [comment]
Sorry for delay .. yes the command above is ok

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74 , Another useful update For Adapta (issue [ #497](https://github.com/adapta-project/adapta-gtk-theme/issues/497) and again Memory Usage reduction)

**Comment by Ste74** [comment]
Thank you ;) 
https://github.com/manjaro/packages-community/commit/00ff0954c8679c035f96acedcbdf614e75f5dd61

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74 , @oberon2007 ,

I made Adapta-Breath look more Manjaro specific - changed original dark blue colors to Manjaro specific dark colors..

Before:
![screenshot from 2017-09-06 18-29-33](https://user-images.githubusercontent.com/5506156/30117680-fb6691ea-9331-11e7-9b24-eb128b3b357c.png)

After:
![screenshot from 2017-09-06 18-28-44](https://user-images.githubusercontent.com/5506156/30117664-f351c9d4-9331-11e7-97d3-1ba4c511afa3.png)

If you like it, I will share  color replacements with you. If not, just ignore this message, this is not  an important suggestion.

**Comment by oberon2007** [comment]
Ah, looks very nice! Sorry I had missed this somehow. However I think it would be great to not lose the original nokto versions, I like those a lot. Did you also change anything in the light theme?
Could we maybe add additional folders with Adapta-Black-Breath / Adapta-Black-Eta-Breath to the existing theme? That would be awesome. Or simply do it in a separate **adapta-breath-black-theme** package?

**Comment by ceyhunnabiyev** [comment]
> Did you also change anything in the light theme?

I only changed dark colors, because I don't like background colors of  Adapta dark variant. And so messy colors (how to say, a lot of colors in files, separately given ) in codes, it is difficult to find them..

Dark Blue Colors -> Manjaro Specific Dark Colors:
```
#4a555b -> #1a4239
             
#3f4d53 -> #153a32

#37474F -> #0a2b25

#364249 -> #092621

#2f3d44 -> #09332c

#2e3a40 -> #082b25

#2d4348 -> #0d3830

#323d42 -> #0c382f

#3B464B -> #11493e

#2A353A -> #0b3029

#2d383f -> #072d27

#263238 -> #031A16 //base color

#29353B -> #05231e

#29343a -> #05211c

#28343A -> #04211c

#243035 -> #021613

#222D32 -> #011917

#212B30 -> #011412 

#13191C -> #01110f

rgba(19, 25, 28, -> rgba(1, 17, 15,

mix(0.8, @accent_color, @fg_color) -> mix(0.5, @accent_color, @fg_color)
```
  
> Could we maybe add additional folders with Adapta-Black-Breath / Adapta-Black-Eta-Breath to the existing theme? That would be awesome. Or simply do it in a separate adapta-breath-black-theme package?

I prefer first thought - additional folders 

In additions, Suggestions for default:
Dash-to-panel - user-friendly,  Same panel view for all official releases (XfCE, KDE, Gnome) would be nice 
Arc-menu - simple and user-friendly,
Adapta for Manjaro Default Theme - Of course Arc-theme is the best gtk theme, but nowadays Active Development of Arc-theme became unknown, users are complaining on github, even almost Gnome 3.26 is coming...

Those are just suggestions. I'm so glad that I use Manjaro, that is why any contribution, suggestion, customization that  I have share with you.

**Comment by Ste74** [comment]
You are welcome 😄 let me work to build it

**Comment by Ste74** [comment]
@ceyhunnabiyev do you remember the file or folder where you do the changes ? Just to not spend more time to find in all Adapta files ;) and .. do you mean with this ?

> #263238 -> #031A16 //base color

i need to write **//base color** also or is only a note ?

**Comment by ceyhunnabiyev** [comment]
@Ste74 , 

> Do you remember the file or folder where you do the changes ? Just to not spend more time to find in all Adapta files ;) and .. do you mean with this ?

I will share you the files. I want to do more customization.

> i need to write //base color also or is only a note ?

just a note..

I want to change all Adapta blue colors (light and dark) to Breath specific?
I have two base background colors  #031A16 and #04251f.  What do you think about this? Which color I select? #031a16  is too dark. Or What another color do you prefer?

**Comment by Ste74** [comment]
I like #031a16 dark green but we can try it and replace if not fine .. take your time ;)

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74 , @oberon2007 

I customized Adapta colors:
![screenshot from 2017-09-10 22-10-22](https://user-images.githubusercontent.com/5506156/30251743-0a62ac72-9677-11e7-8859-70fd99c125cf.png)
[Adapta-Breath-Customized.zip](https://github.com/manjaro/packages-community/files/1290801/Adapta-Breath-Customized.zip)

I prefer to use parallel with sed command in order to do replacing operation in multiple CPU cores and to build Adapta without any color selection option, because there is still some colors (e.g. #00BCD4 still exists, it must be recolored as #1abc9c - Breath color ) after building Adapta. All changed colors and files included above zip file.

**Comment by Ste74** [comment]
So you have installed the regular adapta-gtk-theme and changed the color with sed ?

**Comment by ceyhunnabiyev** [comment]
No, because I don't know bash script very well. I did those things in visual studio code, ("find and replace in files" window)  and built manually. I just saw  parallel command from internet.

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74 ,
I see, you have no time for build , that's why I have learned replacing operation with sed in bash and  have done  more help for you. Please remove  color selection options (`--with-selection_color=#1abc9c, --with-second_selection_color=#2fe2bf, --with-accent_color=#2fe2bf,   --with-suggestion_color=#1abc9c `) within  autogen.sh, because this is  done by sed command.  Following code works for me:
```
#!/bin/bash
cd ~/
git clone https://github.com/adapta-project/adapta-gtk-theme.git
cd adapta-gtk-theme/
find ./extra/gedit/adapta.xml \
./extra/plank/dock.theme \
./extra/telegram/dark/colors.tdesktop-theme \
./extra/telegram/light/colors.tdesktop-theme \
./gtk/asset/assets-gtk2.svg.in \
./gtk/asset/assets-gtk3.svg.in \
./gtk/asset/assets-clone/bar-blue.svg \
./gtk/asset/assets-clone/z-depth-1.svg \
./gtk/asset/assets-clone/z-depth-2.svg \
./gtk/gtk-2.0/colors.rc.in \
./gtk/gtk-2.0/colors-dark.rc.in \
./gtk/gtk-2.0/common.rc \
./gtk/gtk-2.0/common-eta.rc \
./gtk/sass/common/_colors.scss \
./m4/adapta-color-scheme.m4 \
./shell/asset/assets-cinnamon/ \
./shell/asset/assets-gnome-shell/ \
./shell/asset/assets-xfce/ \
./shell/sass/common/_colors.scss \
./shell/sass/gnome-shell/3.24/_extension-workspaces-to-dock.scss \
./shell/sass/gnome-shell/3.26/_extension-workspaces-to-dock.scss \
./shell/xfce-notify-4.0/gtkrc \
./wm/asset/assets-metacity/ \
./wm/asset/assets-openbox/ \
./wm/asset/assets-xfwm/ \
./wm/metacity-1/metacity-theme-2.xml \
./wm/openbox-3/themerc \
./wm/openbox-3/themerc-nokto \
./wm/xfwm4/themerc -type f -print | time xargs sed -i -e \
's/#00BCD4/#1abc9c/Ig'  -e \
's/#009688/#1abc9c/Ig'  -e \
's/#4DD0E1/#2fe2bf/Ig'  -e \
's/#4DB6AC/#2fe2bf/Ig'  -e \
's/#263238/#04251f/Ig'  -e \
's/#CFD8DC/#d1fae6/Ig'  -e \
's/#000016/#001600/Ig'  -e \
's/#03A9F4/#299984/Ig'  -e \
's/#0B9BAF/#21977f/Ig'  -e \
's/#13191C/#020e0c/Ig'  -e \
's/#2196F3/#38a8a3/Ig'  -e \
's/#212B30/#031c17/Ig'  -e \
's/#222D32/#031b17/Ig'  -e \
's/#243035/#04201a/Ig'  -e \
's/#28343A/#052922/Ig'  -e \
's/#29343a/#052923/Ig'  -e \
's/#29353B/#062d27/Ig'  -e \
's/#2A353A/#062d26/Ig'  -e \
's/#2d383f/#06322d/Ig'  -e \
's/#2D4348/#063d2b/Ig'  -e \
's/#2e3a40/#07362e/Ig'  -e \
's/#2f3d44/#073b32/Ig'  -e \
's/#315054/#31544d/Ig'  -e \
's/#323D42/#093a31/Ig'  -e \
's/#364249/#0a433b/Ig'  -e \
's/#374248/#0a423a/Ig'  -e \
's/#37474F/#09493e/Ig'  -e \
's/#384449/#0a4237/Ig'  -e \
's/#39444a/#0b473e/Ig'  -e \
's/#3b4c54/#0b5144/Ig'  -e \
's/#3B464B/#0b463b/Ig'  -e \
's/#3f4d53/#0d5446/Ig'  -e \
's/#3F5A62/#0a664e/Ig'  -e \
's/#41656A/#426c63/Ig'  -e \
's/#444F54/#0f574a/Ig'  -e \
's/#455A64/#0d6858/Ig'  -e \
's/#49545A/#115f54/Ig'  -e \
's/#4a555b/#115f54/Ig'  -e \
's/#5099d0/#31b9b0/Ig'  -e \
's/#5294c4/#3baba2/Ig'  -e \
's/#546e7a/#118872/Ig'  -e \
's/#555F64/#156f60/Ig'  -e \
's/#56707d/#118d78/Ig'  -e \
's/#59646A/#16796a/Ig'  -e \
's/#5B6469/#187769/Ig'  -e \
's/#5c9ece/#38bcb1/Ig'  -e \
's/#65aadd/#3ad4ca/Ig'  -e \
's/#677176/#1c8d7a/Ig'  -e \
's/#6ec9cb/#47bd9a/Ig'  -e \
's/#78909C/#1cc4a8/Ig'  -e \
's/#72b1df/#48d5ca/Ig'  -e \
's/#788286/#23a98c/Ig'  -e \
's/#A3ADB1/#47dcbc/Ig'  -e \
's/#A5AAAD/#46d8c7/Ig'  -e \
's/#A5AEB3/#47dcc6/Ig'  -e \
's/#A7ABAE/#4bd8ce/Ig'  -e \
's/#C3C6C8/#c0fcd8/Ig'  -e \
's/#cbd8dc/#c7fadd/Ig'  -e \
's/#d4d6d7/#c9fce1/Ig'  -e \
's/#E4E7E8/#d4fce6/Ig'  -e \
's/#E5E9EC/#dafbe6/Ig'  -e \
's/#E7E9EA/#d9fde9/Ig'  -e \
's/#E9EAEC/#ddfde2/Ig'  -e \
's/#E9F4F4/#e6feeb/Ig'  -e \
's/#e9ebeb/#ddfde4/Ig'  -e \
's/#e9ebec/#ddfdec/Ig'  -e \
's/#eaebec/#ddfde7/Ig'  -e \
's/#eceff1/#e8fcf0/Ig'  -e \
's/#eff1f2/#e7fdf2/Ig'  -e \
's/#F0F2F3/#ecfdf4/Ig'  -e \
's/#f1f3f4/#ecfdf4/Ig'  -e \
's/#F7F9F9/#f1fef4/Ig'  -e \
's/#FAFBFC/#f5fef8/Ig'  -e \
's/#fdfdfe/#fbfffa/Ig'  -e \
's/rgba(19, 25, 28,/rgba(2, 14, 12,/Ig'  -e \
's/19;;25;;28;;/2;;14;;12;;/Ig'  -e \
's/28;;36;;41;;/2;;18;;16;;/Ig'  -e \
's/mix(0.8, @accent_color, @fg_color)/mix(0.5, @accent_color, @fg_color)/Ig'
./autogen.sh  --disable-unity  --enable-plank   --enable-telegram  --enable-parallel
make
sudo rm -rfv /usr/share/themes/{Adapta,Adapta-Eta,Adapta-Nokto,Adapta-Nokto-Eta}
sudo make install 
sudo cp -fv ~/adapta-gtk-theme/shell/gnome-shell-nokto-eta/gnome-shell-theme.gresource /usr/share/gnome-shell/
```

**Comment by Ste74** [comment]
Thank you so much , you simplify my life ,  grab your script to build it .. In this day work to do it... after release mate and budgie iso ;)

**Comment by Ste74** [comment]
@ceyhunnabiyev , finally i have time to do this 😉 . I have a doubt : the script build only the Breath dark version right ?

**Comment by ceyhunnabiyev** [comment]
@Ste74 , both light and dark version :wink:

**Comment by Ste74** [comment]
Last request if you want help me 😉 :  i can modify your script and change the breath color with maia to do both maia and breah version ( i think i can change the breath code color with maia code color )

**Comment by ceyhunnabiyev** [comment]
@Ste74,  You can change  following colors with maia colors: 
```
's/#00BCD4/#1abc9c/Ig'  -e \
's/#009688/#1abc9c/Ig'  -e \
's/#4DD0E1/#2fe2bf/Ig'  -e \
's/#4DB6AC/#2fe2bf/Ig'  -e \
```

**Comment by Ste74** [comment]
Thank you mate 😄 . What is your user name in our forum ( if you have one ) ?

**Comment by ceyhunnabiyev** [comment]
Yes, jeyhunn

**Comment by Ste74** [comment]
Done : https://github.com/manjaro/packages-community/commit/1c1508e9cc8cd5caed9247796ab1d6d4690eb1a6
Now i have only bump the version and push in our repo 😉

**Comment by ceyhunnabiyev** [comment]
@Ste74 , Did you check it ? How does it look?  I didn't see any problem..

**Comment by Ste74** [comment]
Uhmm ... i think in the sed code wrong somewhere .. i don't see difference ...

**Comment by ceyhunnabiyev** [comment]
Remove time command next to xargs, maybe you didn't install [time](https://directory.fsf.org/wiki/Time)

**Comment by ceyhunnabiyev** [comment]
Please check  1c1508e , you see here time command colored as red.

**Comment by Ste74** [comment]
Correct https://github.com/manjaro/packages-community/commit/711ad687b75beda671d71742c209f3c1744a5c37 
@ceyhunnabiyev really great job mate 😉

**Comment by oberon2007** [comment]
@Ste74 Please check again. There seems to be something wrong with highlight-colors of the black themes. Looks like also the maia black themes are currently using breath hightlighting... ;)

**Comment by oberon2007** [comment]
![black_maia](https://user-images.githubusercontent.com/11800714/30569398-f5372b10-9cda-11e7-9e36-12844c5a7473.png)

Also, strangely see in the screenshot, the highlight color on the left is different from the one on the right ...

**Comment by oberon2007** [comment]
![black-eta-maia](https://user-images.githubusercontent.com/11800714/30569436-2eec6bea-9cdb-11e7-9590-a0c306952877.png)

Also with the light theme there is something off with highlighting as you can see here.

**Comment by Ste74** [comment]
I checked only in gnome ..

> 
There seems to be something wrong with highlight-colors of the black themes. Looks like also the maia black themes are currently using breath hightlighting... ;)

yep .. typo error :p 

for other issue this evening try to pass the sed command in all files.. what is your image xfce?

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74 , @oberon2007  
What about Black Breath? Is something wrong with it? If not, change following colors to maia specific in Adapta Black Maia theme:
```
's/#00BCD4/#16a085/Ig'  -e \             #Correct. 
's/#009688/#009688/Ig'  -e \             #Correct, but you use same color for suggested  buttons, please remove this. 
's/#4DD0E1/#16a085/Ig'  -e \             #Wrong, this is light variant of #00BCD4, you have to use maia light variant, if you don't have, use 's/#4DD0E1/#4fbfa9/Ig'  -e \, generated in HSL code.
's/#4DB6AC/#2fe2bf/Ig'  -e \             #Wrong, light variant of #009688, please remove this.
```

**Comment by Ste74** [comment]
Modified https://github.com/manjaro/packages-community/commit/65763f67fec0ff7eb4bff88af2b6b3783c5dd537
@oberon2007 , @ceyhunnabiyev check it

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74 , if useful or important Adapta release out, I will create pull request for you, of course, if you want. First one has already been created :wink:.
