### ISSUE TITLE
Cannot search for Addons

### ISSUE THREAD

**Issue by nojeffrey** [manjaro/packages-community#337]
Fresh install of Manjaro 17.0.2 with KDE, if I go to the Addons page, I don't have any option to search for Addons.

![2017-07-19-135155_1706x878_scrot](https://user-images.githubusercontent.com/4727096/28350006-78caeebc-6c89-11e7-9dc5-a9419d4f4565.png)

**Comment by philmmanjaro** [comment]
Click on **learn more** or **see all** to go to the addon page.

**Comment by nojeffrey** [comment]
OK, "See all" worked. The issue seems to be with me, am blind.
