### ISSUE TITLE
budgie-desktop use -git?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#34]
https://forum.manjaro.org/index.php?topic=25257.msg216521#msg216521
What do you think?

**Comment by philmmanjaro** [comment]
We use already latest git-patches on top of it. I'm checking that branch time to time. See also [PKGBUILD](https://github.com/manjaro/packages-community/blob/master/budgie-desktop/PKGBUILD).

**Comment by oberon2007** [comment]
Yes, that's what I already guessed, having seen your recent update, thanks! :)
