### ISSUE TITLE
Request  package

### ISSUE THREAD

**Issue by Oczkins92** [manjaro/packages-community#341]
Please make package usb_modeswitch because there no is in Manjaro.I really dont want download from arch  site.Without this package moslty 3g modem does'nt working.Thank you and have nice day

**Comment by FadeMind** [comment]
CC @oberon2007  @philmmanjaro  @Kirek  please consider this:

Including in default LIVE IMAGE (as `manjaro-system` dependency) **usb_modeswitch** package from Arch Linux community repository.

https://www.archlinux.org/packages/community/i686/usb_modeswitch/

Regards

Tomasz

**Comment by Oczkins92** [comment]
No właśnie tą paczkę chodziło aby była w Manjaro

2017-07-26 16:51 GMT+02:00 Tomasz Przybył <notifications@github.com>:

**Comment by Ste74** [comment]
When was removed this ?

**Comment by FadeMind** [comment]
@Ste74  Package usb_modeswitch is optional dependency for networkmanager package. IDK when.

https://github.com/manjaro/iso-profiles/tree/master/shared

**Comment by Ste74** [comment]
Done 
https://github.com/manjaro/iso-profiles/commit/d80c98775dd8f129e99c5e4573b5853738e23aca
