### ISSUE TITLE
Firefox 55 released

### ISSUE THREAD

**Issue by francoism90** [manjaro/packages-community#349]
Thanks for providing firefox-kde, just to let you guys know a newer version has been released today. :)

**Comment by Kirek** [comment]
firefox-kde updated in unstable

**Comment by francoism90** [comment]
FF 55.0.1 released :)

**Comment by Ste74** [comment]
firefox gtk done https://github.com/manjaro/packages-extra/commit/c6e028427f8282302848b59c23d1a759ebd10905 ;)
