### ISSUE TITLE
vlc-nightly using wrong resolution

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#366]
Latest package **vlc-nightly 3.0.0v20170902-1** appears to be displaying the controls at the bottom in a wrong resolution. Icons are too big and the volum display is pixelated

![vlc](https://user-images.githubusercontent.com/11800714/30613569-dabf6488-9d88-11e7-832b-4dc81143fe8c.png)

Will check latest available snapshot...

**Comment by oberon2007** [comment]
The issue is unchanged with **3.0.0v20170919**.

**Comment by philmmanjaro** [comment]
Can't reproduce within XFCE. All normal ...

![bildschirmfoto_2017-09-20_10-13-29](https://user-images.githubusercontent.com/5050022/30633578-71b5af6a-9dec-11e7-9fb8-c59e483b774d.png)

**Comment by oberon2007** [comment]
My screenshot is xfce, too - xfce4-gtk3 actually. Are you using xfce4-gtk3 ?

**Comment by oberon2007** [comment]
Everything is too big here, no matter which icon- or gtk-theme. Tried with both **gtk3** and **gtk3-classic**, always looks the same.
Here's the about page 😜 :

![vlc2](https://user-images.githubusercontent.com/11800714/30634696-38df0912-9df0-11e7-8c1a-f9bfc757a8c1.png)

**Comment by philmmanjaro** [comment]
GTK2 as usual.

**Comment by Ste74** [comment]
@oberon2007 is still open? :p

**Comment by oberon2007** [comment]
I still have the problem ... but I had opened an upstream issue and I guess there isn't much we can do about it ourselves ... closing.
