### ISSUE TITLE
nvidia 384.90 refuses to build against rt-kernels

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#367]
Seems with the newest nvidia driver we can no longer supply nvidia-extramodules...
```
The kernel you are installing for is a PREEMPT_RT kernel!

The NVIDIA driver does not support real-time kernels. If you 
are using a stock distribution kernel, please install 
a variant of this kernel that does not have the PREEMPT_RT 
patch set applied; if this is a custom kernel, please 
install a standard Linux kernel.  Then try installing the 
NVIDIA kernel module again.

*** Failed PREEMPT_RT sanity check. Bailing out! ***
```
Happens with both linux49 and 411 base kernels.
Any ideas @philmmanjaro ?

**Comment by philmmanjaro** [comment]
https://aur.archlinux.org/packages/nvidia-rt/ doesn't work either?

**Comment by philmmanjaro** [comment]
Here some old links:

https://devtalk.nvidia.com/default/topic/572468/linux/nvidia-325-15-linux-rt-old-amp-amp-new-nvidia-rt-patch-methods-questions-about-nvidia-installer/
http://linuxaudioproduction.blogspot.de/2015/09/how-to-patching-and-compiling-nvidia.html

**Comment by oberon2007** [comment]
Thank you. It seems the way nvidia checks for PREEMPT_RT has changed.
I found a way to adjust and circumvent the test. It's building now 😉 
We'll just need to see then if it does in fact work on a system ...

**Comment by philmmanjaro** [comment]
Well, simply post about it and somebody will test it ;)

**Comment by oberon2007** [comment]
@budimanjojo can you please check if latest **nvidia 384.90** extramodule works? Packages are now on unstable branch.

**Comment by philmmanjaro** [comment]
Also announced in our [forum](https://forum.manjaro.org/t/unstable-update-2017-09-22-nvidia-384-90-nvidia-340-104-nvidia-304-137-haskell-python/31595).

**Comment by zhangtianzi** [comment]
Hi guys,
I installed 4.4.32-apollo-2-RT (a RT-kernel based on official Linux Kernel 4.4.32 with some modifications.). And I executed the shell script to install the Nvidia driver (My GPU is GTX 1050Ti).

The terminal print: "successfully install" , but the screen resolution is still very very slow（the nvidia card still does not work）.

After executing "nvidia-smi", the terminal showed "failed to initialize NVML: Driver/library version mismatch". how should I do?

Looking forward to your reply.

**Comment by zhangtianzi** [comment]
Hi guys,
I installed 4.4.32-apollo-1.5.0-RT (a RT-kernel based on official Linux Kernel 4.4.32 with some modifications.). And I executed the shell script to install the Nvidia driver (My GPU is GTX 1050Ti).

The terminal print: "successfully install" , but the screen resolution is still very very slow（the nvidia card still does not work）.

After executing "nvidia-smi", the terminal showed "failed to initialize NVML: Driver/library version mismatch". how should I do?

Looking forward to your reply.

**Comment by oberon-manjaro** [comment]
I cannot really help you there since you are using a non-manjaro kernel.
You can either use one of our rt-kernels or you will have to build your matching extramodules yourself.
However this isn't related to this issue here,  which has been closed long time ago btw :wink:

**Comment by oberon-manjaro** [comment]
If you're going to build your own extra module, the PKGBUILD can be found [here](https://gitlab.manjaro.org/packages/community/realtime-kernels/linux416-rt-extramodules/blob/master/nvidia/PKGBUILD) for reference.

**Comment by zhangtianzi** [comment]
Thank you @oberon-manjaro  , I have to use the apollo-kernel ，because we use an open powerful autonomous driving platform:Apollo .  I am trying to solve this problem,and  I will share it after I get it.
