### ISSUE TITLE
JADE icon integration on other desktops

### ISSUE THREAD

**Issue by codesardine** [manjaro/packages-community#371]
Jade integrates to the native icon theme well on XFCE, Gnome, Deepin I did not test with any others yet

But on Kde It it does look horrible probably on Lxqt also, I was thinking making Paper Icon Theme a default dependency instead of optional, and set paper as default theme on installation for a better experience, Some users realy like their icons and no application should set the user icons.

Any ideas how to go around this?

**Comment by philmmanjaro** [comment]
Do you have some screenshots @codesardine

**Comment by codesardine** [comment]
Any toughs on this should i add paper icons  as default, KDE uses adwaita theme, fot GTK apps?
