### ISSUE TITLE
Parole-gtk3 correction needed ..

### ISSUE THREAD

**Issue by Ste74** [manjaro/packages-community#373]
@oberon2007 , @philmmanjaro  i don't see the pkgbuild for `parole-gtk3` , i can't correct conflicts array or see if is wrong  .. this need adjustement. Please see [this](https://forum.manjaro.org/t/how-easy-is-it-to-break-the-manjaro-with-pamac/31877) ;)

**Comment by philmmanjaro** [comment]
All is good. The user installed a **[xfce-gtk3](https://github.com/manjaro/packages-extra/tree/master/xfce4-gtk3)** specific package. **parole** is also GTK3 and is the standard package.

**Comment by Ste74** [comment]
Ahhh this is the reason because not found in community repo.. is in extra repo ... :p :)
