### ISSUE TITLE
Flat Plat Gtk Theme Request

### ISSUE THREAD

**Issue by codesardine** [manjaro/packages-community#375]
Can Manjaro have this in the repos?, It s a nice clean Material design Theme.
Maybe change that blue color by a Green Teal.
src - https://github.com/nana-4/Flat-Plat
#
![flat](https://user-images.githubusercontent.com/4250006/31017107-5a0ab54c-a51f-11e7-952b-b89ae754001a.png)

**Comment by Ste74** [comment]
Possible duplicate of this https://github.com/manjaro/iso-profiles/issues/48

**Comment by codesardine** [comment]
duplicate indeed.

**Comment by Ste74** [comment]
In our repo you can find a theme based on this : Adapta ;) .. in any case if arc theme really dead i can consider to add another theme with official color .. we will see ;)
