### ISSUE TITLE
adapta-gtk-theme problem with qt theming

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#376]
At least with latest **adapta-nokto-maia** there are some problems with qt theming.
@Ste74 can you have a look, please?
Problem with background of **msm**:
![msm_nokto_maia](https://user-images.githubusercontent.com/11800714/31069111-4e32d450-a75b-11e7-8fe3-dda6c7ce6d36.png)
Wrong highlight color in **krita**:
![krita](https://user-images.githubusercontent.com/11800714/31069175-934ed43a-a75b-11e7-9040-2aa5ffe7cbdb.png)

**Comment by Ste74** [comment]
@oberon2007 , can you check if this work ? If yes i can grab from this ;) 
https://github.com/adapta-project/adapta-gtk-theme/issues/304#issuecomment-314102470

**Comment by oberon2007** [comment]
I've tried with both **AdaptaNoktoEta.colors** and a **AdaptaNoktoEtaMaia.colors**, but no difference.
However, notice that the colors in general are good and matching the theme, just the some properties are off...

**Comment by oberon2007** [comment]
Same issue also with all our other dark adapta variants, like for example Adapta-Black-Nokto-Maia:

![black](https://user-images.githubusercontent.com/11800714/31079449-00d5408c-a786-11e7-8030-3d4442a72953.png)

**Comment by philmmanjaro** [comment]
Seems to be a serial issue then :smile:

**Comment by Ste74** [comment]
Tista pushed another release of this theme , i build tonight this and we will see how work and if is again incorrect i ask at tista what happen ufffff

**Comment by Ste74** [comment]
New version build just now ( in unstable ) ...
![schermata del 2017-10-02 23-11-37](https://user-images.githubusercontent.com/11218234/31099762-65f80c1a-a7c7-11e7-90de-77d7e639fd45.png)
nothing change pfffff ( gtk / qt grrrrrrrrr )  @oberon2007 is the case to open an issue ?

**Comment by Ste74** [comment]
Ask on Adapta-repo

**Comment by oberon2007** [comment]
Mille gratie, Maestro!

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74 , @oberon2007 
I use Kvantum Adapta theme for qt applications in Gnome. I am going to prepare black variant:
![screenshot from 2017-10-03 01-42-19](https://user-images.githubusercontent.com/5506156/31100862-25fef73a-a7dc-11e7-898f-2668b6f076cc.png)

**Comment by ceyhunnabiyev** [comment]
There is some wrong color with push button on the original theme. I will replace it correct color during preparing black variant..

**Comment by oberon2007** [comment]
@Ste74 what do you mean with kvantum adapt? is it a different package? problems with all adapta-maia dark themes is still unchanged, for example with **manjaro-settings-manager**. We are simply using **qt5ct** for qt theming.

**Comment by ceyhunnabiyev** [comment]
Hi @oberon2007 ,   [Kvantum Adapta](https://github.com/tsujan/Kvantum/tree/master/Kvantum/themes/kvthemes) is installed by [kvantum-qt5](https://www.archlinux.org/packages/community/x86_64/kvantum-qt5/) ([kvantum-qt5-git](https://aur.archlinux.org/packages/kvantum-qt5-git)) . Then you select Kvantum Adapta dark theme in KvantumManager, then you select kvantum-dark on qt5ct in order to use Kvantum Adapta for qt applications in Gnome( [Screenshot from KDE](https://forum.manjaro.org/t/steamy-september-2017-screenshots/30621/80))

**Comment by oberon2007** [comment]
Great, thank you! That solves the problem of the broken background in manjaro-settings-manager. We'd now just need an adjusted version with the maia respectively breath colors for kvantum-qt5 ...

**Comment by Ste74** [comment]
Sorry for delay :) .. yep we can grab the kvantum pkgs and adjust for our color but @ceyhunnabiyev you know how change in qt5 theming the color ?

**Comment by ceyhunnabiyev** [comment]
@Ste74 , until tomorrow night I will try to share black, maia, breath color replacements. Just wait, please :wink:

**Comment by oberon2007** [comment]
Sounds great! Maybe additional properties could just be deployed in a separate pkg on kvantum-qt5? Might be the easiest way.

**Comment by oberon2007** [comment]
Sounds great! Maybe additional properties could just be deployed in a separate pkg on kvantum-qt5? Might be the easiest way.

**Comment by Ste74** [comment]
Double post @oberon2007 i delete one 😉

**Comment by Ste74** [comment]
> Sounds great! Maybe additional properties could just be deployed in a separate pkg on kvantum-qt5? Might be the easiest way.

Yep we can create a pkgs with specific config for us

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74 , @oberon2007 

KvAdaptaDark-Breath:
![screenshot-20171008204401-1364x707](https://user-images.githubusercontent.com/5506156/31319261-0445f92e-ac71-11e7-8814-cba69e5048d3.png)

KvAdaptaDark-Maia:
![screenshot-20171008205620-1364x707](https://user-images.githubusercontent.com/5506156/31319272-2d899066-ac71-11e7-9804-94af5ff8374b.png)

KvAdaptaDark-Black-Breath:
![screenshot-20171008213141-1365x729](https://user-images.githubusercontent.com/5506156/31319281-6218da94-ac71-11e7-8862-e5e34320c4b4.png)
[kvantum-adapta-scrips.zip](https://github.com/manjaro/packages-community/files/1367071/kvantum-adapta-scrips.zip)

**Note**: Developer of Kvantum didn't make release with Kvantum Adapta in github. I requested it, he says that it will be released in a week. I installed  [AUR](https://aur.archlinux.org/packages/kvantum-qt5-git) package

**Comment by Ste74** [comment]
Great 😄 i wait a little if a stable version is released otherwise grab from git version ..

**Comment by oberon2007** [comment]
I have created an [overlay](https://github.com/manjaro/packages-community/commit/8d1ea796614a7138422fd6f30be156221cbd5362) with the git version now.
For the breath and adapta versions I will make a separate package with you colors @ceyhunnabiyev , thanks a lot!!

**Comment by Ste74** [comment]
Perfect :)

**Comment by oberon2007** [comment]
@ceyhunnabiyev your scripts seem to do only one transformation. Is this Maia or Breath? Would you have the other versions for us, too?

**Comment by ceyhunnabiyev** [comment]
@oberon2007 ,
[kvantum-adapta-dark-and-light-only-breath.zip](https://github.com/manjaro/packages-community/files/1369704/kvantum-adapta-dark-and-light-only-breath.zip)
[kvantum-adapta-dark-and-light-only-maia.zip](https://github.com/manjaro/packages-community/files/1369705/kvantum-adapta-dark-and-light-only-maia.zip)

**Comment by oberon2007** [comment]
Awesome, thank you! Will make the **kvantum-manjaro** package tomorrow. 👍

**Comment by philmmanjaro** [comment]
@ceyhunnabiyev also from me thanks for your effort and support on this one. Highly appreciated.

**Comment by ceyhunnabiyev** [comment]
If you see  any problems about these, immediately say me, because I see in the forums you are so busy, especially with gnome 3.26..

**Comment by oberon2007** [comment]
Thank you, but I'm afraid your scripts are still confusing for me. I have summarized what you gave me [here](https://github.com/manjaro/kvantum-manjaro/blob/master/color_transformation)
However, what you call "Dark" is apparently the Black version. What I actually need to know is this:
Which colors need to be changed for these transformations:
Regular -> regular Breath and Maia
Nokto -> nokto Breath and Maia
Nokto -> Black Breath and Maia
Right now I don't know which transformations are needed for the Nokto and Black variations...
Thank you.

**Comment by oberon2007** [comment]
Looks like after applying the "Dark" changes I end up with the "Black" versions.
So for Nokto Maia and Breath do only the hightlight colors need adjustments?

**Comment by oberon2007** [comment]
Seems to work...

**Comment by oberon2007** [comment]
KvAdapta{,Breath,Maia}{,Black,Dark} are now simply separate themes in a dedicated [repo](https://github.com/manjaro/kvantum-manjaro)
**kvantum-qt5** is a dependency of the new [package](https://github.com/manjaro/packages-community/blob/master/kvantum-manjaro/PKGBUILD) and can be removed from the overlay with its next update.

**Comment by oberon2007** [comment]
Also nice: in **krita** for example, and likely in other qt5-apps you can now select all the new themes directly
![krita_themes](https://user-images.githubusercontent.com/11800714/31391550-2bdc5e76-add7-11e7-8ed8-7733411ce280.png)

**Comment by Ste74** [comment]
Can add ad optdepends for adapta respective pkgs?

**Comment by oberon2007** [comment]
I was about to do that - it's just a very long list already ... 😉 😆

**Comment by ceyhunnabiyev** [comment]
@oberon2007 , I didn't check it so deeply. If you find some blue color in qt applications, surely I said that it another color. For this, we have to generate new breath or maia color in hsl code. Please say me, I will generate it.

**Comment by Ste74** [comment]
Tonight upload new adapta ver .. so if you don't add i do ;)

**Comment by oberon2007** [comment]
https://github.com/manjaro/packages-community/commit/1947261d66f7176b063acffcd1edabf5b682dba6

**Comment by oberon2007** [comment]
@ceyhunnabiyev it seems to be fine. I was just wondering since you had several changes for the light themes I was expecting some needed also for the nokto versions.
We can always adjust when we find some mismatches, sure.

**Comment by Ste74** [comment]
@oberon2007 since my adapta provide also the regular adapta-gtk theme ( blueish ) when ready do you think to import also kvantum adapta/adapta-dark ?

**Comment by oberon2007** [comment]
Why? They are already included in the **kvantum-qt5** package and **kvantum-manjaro** depends on it.

**Comment by philmmanjaro** [comment]
I see it similar.

**Comment by Ste74** [comment]
> Why? They are already included in the kvantum-qt5 package and kvantum-manjaro depends on it.

Sorry i realize now .. install the theme and applied.. great and also great tool to select it 😄

**Comment by Ste74** [comment]
i started new build for adapta with the correction, when ready check if now all is manjarized

**Comment by ceyhunnabiyev** [comment]
Hi @oberon2007 ,  @Ste74  ,
kvantum-qt5 0.10.5 released out right now..
