### ISSUE TITLE
timeshift desktop entry not working

### ISSUE THREAD

**Issue by codesardine** [manjaro/packages-community#379]
replacing this -> sh -c 'xhost +SI:localuser:root && timeshift-launcher
by this -> timeshift-launcher

fixes it and asks for admin password

**Comment by Ste74** [comment]
Have you tried with wayland session ?

**Comment by Ste74** [comment]
Can you try .. at last i can push the stable release and do an announcemnt for this issue

**Comment by Ste74** [comment]
Please report here.
https://forum.manjaro.org/t/timeshift-v17-10-is-ready/32372
