### ISSUE TITLE
[adapta-gtk-maia] wrong icon highlight color

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#380]
![icon_selected](https://user-images.githubusercontent.com/11800714/31306273-bfa4f1fa-ab4c-11e7-906a-461c2dbc4dc6.png)
Selected icons on the desktop are blue ...

**Comment by Ste74** [comment]
@oberon2007 , i don't use in gnome the icon on desktop .. anyway i have add on gnome to see in my hands take a look (adapta-black-version)
![schermata del 2017-10-07 15-12-46](https://user-images.githubusercontent.com/11218234/31308182-4735b6f2-ab72-11e7-8823-bda7e0785548.png)
Do you mean with adapta-gtk-maia ? i don't build this name .. i build the adapta-gtk-theme with other breath and maia version . If you mean adapta-gtk-theme this is normal .. otherwise how i can replicate ?

**Comment by oberon2007** [comment]
My screenshot is xfce (-gtk3) with adapta-maia-eta.

**Comment by Ste74** [comment]
Why use this ?
https://github.com/adapta-project/adapta-gtk-theme#variant-matrix
in the matrix i see xfwm4 can use normal eta.. anyway a new release od adapta is out and i rebuild again ( also because want change gdm wallapaper :p )

**Comment by oberon2007** [comment]
I don't understand. Are your maia and breath pkgs not supposed to be used with xfce? Why should we use matrix? It won't have the right colors, right?

**Comment by Ste74** [comment]
LOL no i mean adapta dev suggest to use the normal version of adapta ( if you open the link you see the schemas ) and not the light version like eta .. in any case let me rebuild the pkg...

**Comment by ceyhunnabiyev** [comment]
@Ste74  ,  please remove color options next to autogen.sh. And use  sed command  in order to replace default color  with maia color as you did when you built black variant. By the way, does this issue occur in black variant?

**Comment by Ste74** [comment]
>  please remove color options next to autogen.sh.

This mean a bug in adapta sript to change a colour if it work without this, yes we have to check if black version is afflicted to exclude this..

**Comment by Ste74** [comment]
Since i can rebuild adapta with a new version, have you tried the black variant ? If no affected i build without the color selection on `adapta scrpt` and use `sed` command

**Comment by oberon2007** [comment]
It's the same blue hightlight color with ALL adapta gtk themes, including the 'black' variants.

**Comment by ceyhunnabiyev** [comment]
@oberon2007 , If you use  eta variant, it won't work..

**Comment by oberon2007** [comment]
eta or regular makes no difference with icon highlight color. It stays the same as with normal Adapta-theme, it never changes, no matter what other theme variant.

**Comment by Ste74** [comment]
Let me see if with atom editor i can found other blueish color ..

**Comment by Ste74** [comment]
@oberon2007 can you check if match with this ?
#03A9F4

**Comment by oberon2007** [comment]
Not easy to tell because it's on top of other colors, but seems to match, yes! 😄 👍

**Comment by Ste74** [comment]
Okay, I do not promise to be able to reload it tonight as the computer is loading the album of my ten-year wedding party hi hi hi .. but tomorrow I will surely look and see if I find other errors

**Comment by ceyhunnabiyev** [comment]
@Ste74 , @oberon2007 ,  I found the issue. @Ste74 , 
```
build_black-breath-theme() {
cd $srcdir
    cd "adapta-black-breath-theme-${pkgver}"
    msg "Apply Black theme"
    
    find . -type f -name '*.*' -exec sed -i \
	"s/#00BCD4/#1abc9c/g;\
	s/#009688/#1abc9c/g;\
	s/#4DD0E1/#2fe2bf/g;\
	s/#4DB6AC/#2fe2bf/g" {} \;
    
    _adapta-black
	
	./autogen.sh --prefix "${pkgdir}/usr" \
      --enable-plank \
      --enable-telegram \
      --disable-unity \
      --enable-parallel #--enable-gtk_next
    make
}
```
replace with following:
```
build_black-breath-theme() {
cd $srcdir
    cd "adapta-black-breath-theme-${pkgver}"
    msg "Apply Black theme"
    
    find . -type f -name '*.*' -exec sed -i \
	"s/#00BCD4/#1abc9c/Ig;\
	s/#009688/#1abc9c/Ig;\
	s/#4DD0E1/#2fe2bf/Ig;\
	s/#4DB6AC/#2fe2bf/Ig" {} \;
    
    _adapta-black
	
	./autogen.sh --prefix "${pkgdir}/usr" \
      --enable-plank \
      --enable-telegram \
      --disable-unity \
      --enable-parallel #--enable-gtk_next
    make
}

```
Ig  help you to ignore cases (#00BCD4 and #00bcd4, both have to be replaced).

**Comment by ceyhunnabiyev** [comment]
And also for maia:
```
build_black-maia-theme() {
cd $srcdir
    cd "adapta-black-maia-theme-${pkgver}"
    msg "Apply black theme"
    
    find . -type f -name '*.*' -exec sed -i \
	"s/#00BCD4/#16a085/g;\
	s/#4DD0E1/#4fbfa9/g" {} \;

    _adapta-black
		
	./autogen.sh --prefix "${pkgdir}/usr" \
      --enable-plank \
      --enable-telegram \
      --disable-unity \
      --enable-parallel #--enable-gtk_next
    make
}
```
replace with following:

```
build_black-maia-theme() {
cd $srcdir
    cd "adapta-black-maia-theme-${pkgver}"
    msg "Apply black theme"
    
    find . -type f -name '*.*' -exec sed -i \
	"s/#00BCD4/#16a085/Ig;\
	s/#4DD0E1/#4fbfa9/Ig" {} \;

    _adapta-black
		
	./autogen.sh --prefix "${pkgdir}/usr" \
      --enable-plank \
      --enable-telegram \
      --disable-unity \
      --enable-parallel #--enable-gtk_next
    make
}
```

**Comment by Ste74** [comment]
Sure will add `Ig` instead `g` ;)

**Comment by ceyhunnabiyev** [comment]
Yes, of course. I showed the function  completely in order to find quickly.

**Comment by Ste74** [comment]
Don't worry i already understand what you mean 😉

**Comment by ceyhunnabiyev** [comment]
Please do this in all adapta packages and remove color selection options next to autogen.sh.

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74 , if you build Adapta latest version 3.91.2.233, add following new color to `_adapta-black()` function in PKGBUILD (Adapta commit [this](https://github.com/adapta-project/adapta-gtk-theme/commit/f66ea3d274021fbe5a459a20fd53a3ecebccb5be) ):
`'s/#eeefef/#e7feeb/Ig'  -e \`

**Comment by oberon2007** [comment]
highlight color of desktop icons is still unchanged with today's updated pkgs ... Where might this property be hiding...?

**Comment by Ste74** [comment]
Uhmm.. let me see if is not esadecimal color

**Comment by oberon2007** [comment]
hm. yes, I have also just checked for ``3, 169, 244`` and did not find it anywhere.

**Comment by oberon2007** [comment]
when I see [this](http://xubuntugeek.blogspot.fr/2012/09/how-to-make-desktop-icons-text.html), I wonder if we need a specific xfce property for that.

**Comment by philmmanjaro** [comment]
Ya, noticed it also. Will create the new ISO anyway. So I see the latest changes for Thursdays presentation.

**Comment by Ste74** [comment]
After search in gtk2 folder in particular i find blue color.. :p

**Comment by oberon2007** [comment]
You did? If you mean ``visited_link_color:#9C27B0``, that's not it. Changing that one doesn't help.
After digging more into this and comparing with latest greybird-git my theory is that xfce4-gtk3 needs a different approach for styling than it used to be - makes sense of course since it's not gtk2 any more 😉 
This might need some more work still to make it work. At least for now we only see this minor issue with desktop icons...

**Comment by ceyhunnabiyev** [comment]
Adapta supports xfce4-gtk3?

**Comment by oberon2007** [comment]
everything seems to work fine, yes. it's just the one little thing.

**Comment by oberon2007** [comment]
![xfce_gtk3](https://user-images.githubusercontent.com/11800714/31408017-5383f904-ae07-11e7-83d3-2906f9386d45.png)

**Comment by Ste74** [comment]
Well guys .. found another blueish color .. rel2 work in progress :D

**Comment by philmmanjaro** [comment]
Take your time. No rush needed. Looking good so far.

**Comment by Ste74** [comment]
> Take your time. No rush needed. Looking good so far.

Even in my real work .. if something does not work I have to understand why ;)

**Comment by Ste74** [comment]
New revision in the repo .. change how work sed command..

**Comment by Ste74** [comment]
@oberon2007 have you checked if now is ok ;) ?

**Comment by oberon2007** [comment]
It's still the same. I am almost sure that the theme simply does NOT specify any color for the needed property and the blue highlight is simply xfce's default for it.

**Comment by Ste74** [comment]
@oberon2007 @philmmanjaro please create a file `gtk.css` into `~/.config/gtk-3.0 ` and put this content:

> /* xfdesktop icon theming */
> XfdesktopIconView.view {
> 	background-color: rgba(0,0,0,0.0);
> }
> 
> XfdesktopIconView.view:active {
> 	background-color: rgba(0,0,0,0.3);
> 	color: #16A085;
> 	border-radius: 1px;
> }
> 
> XfdesktopIconView.rubberband {
> 	background-color: rgba(0,0,0,0.3);
> }
> 
> XfdesktopIconView.label:active {
> 	background-color: rgba(0,0,0,0.3);
> 	color: white;
> }

Save and logout/login .. what is the effect ? ;)

**Comment by oberon2007** [comment]
@Ste74 , sei un EROEEEEE!!!!!!!!

![highlight](https://user-images.githubusercontent.com/11800714/32147299-52ffa810-bce5-11e7-8f79-ffed29103127.png)
@philmmanjaro , we need this still included in our final ISO - sorry... 😜

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74 , does this Adapta problem (second problem I mentioned  [here](https://forum.manjaro.org/t/messy-file-display-non-uniform-columns-in-nautilus/33687?u=jeyhunn)) occur on your computer? 
![screenshot-20171029141559-1364x215](https://user-images.githubusercontent.com/5506156/32147359-8f892a44-bcff-11e7-9152-472740fa7352.png)

**Comment by oberon2007** [comment]
So, I assume the deskotp icon hightlight fix can go somwhere in the theme's css files, right?

**Comment by philmmanjaro** [comment]
There should be a XFCE section in the CSS files somewhere ...

**Comment by Ste74** [comment]
@oberon2007 , yes i think we can put this code at the end of the gtk.css code into theme let me build a test packages .. @philmmanjaro you are right but for the old gtk2 .. i think new gtk3 version of xfce parse the gtk3 folder ...
@ceyhunnabiyev , not open tweak tools before but damn you are right .. is a bug :(

**Comment by ceyhunnabiyev** [comment]
@Ste74 , I created [issue](https://github.com/adapta-project/adapta-gtk-theme/issues/542).

**Comment by oberon2007** [comment]
The proper way would maybe be to add it in [_3rd-party.scss](_3rd-party.scss), although for our needs it will also work to just patch it in $pkgdir 😉

**Comment by Ste74** [comment]
Yeah.. found the same result .. but not .. we have to add in scss files.. because if understand correctly adapta is a more complex theme and the gtk are hard coded into gtk.gresource code .. :(

try to add this in the _3rdblabla and test the result ..

**Comment by oberon2007** [comment]
yeah, the theme files are compiled blobs. I'm afraid it will need to be added in this strange sass format ...

**Comment by oberon2007** [comment]
Maybe will this work?
```
// /*********
//  * XFce4 *
//  *********/

.XfdesktopIconView {
  &.view {
    background-color: rgba(0,0,0,0.0);
  }
  &.view:active {
    background-color: rgba(0,0,0,0.3);
    color: $selected_bg_color;
    border-radius: 1px;
  }
  &.rubberband {
    background-color: rgba(0,0,0,0.3);
  }
  &.label:active {
  background-color: rgba(0,0,0,0.3);
  color: white;
  }
}
```

**Comment by oberon2007** [comment]
Or maybe `XfdesktopIconView` is not a class but just a property, so without the leading dot?
```
XfdesktopIconView {
 and so on
}
```
?

**Comment by ceyhunnabiyev** [comment]
@Ste74,  [issue](https://github.com/adapta-project/adapta-gtk-theme/issues/542) fixed in Adapta version 3.92.1.33

**Comment by Ste74** [comment]
well @ceyhunnabiyev updated adapta-themes . @philmmanjaro , @oberon2007 with this commit ijust added two files , during compiling the content of this files are added in any _3d-party.scss.
https://github.com/manjaro/packages-community/commit/2161a5b7122bb224deaac14dcfb951fc00c864d7

**Comment by oberon2007** [comment]
unfortunately back to blue hightlight with **3.92.1.43-1**. Seems to be not working...

**Comment by oberon2007** [comment]
```
==> Apply Maia theme
cat: /home/bernhard/manjaro/community/adapta-manjaro-themes/src/manjaro-xfce-override-theme: No such file or directory
cat: /home/bernhard/manjaro/community/adapta-manjaro-themes/src/manjaro-xfce-override-theme: No such file or directory
cat: /home/bernhard/manjaro/community/adapta-manjaro-themes/src/manjaro-xfce-override-theme: No such file or directory
cat: /home/bernhard/manjaro/community/adapta-manjaro-themes/src/manjaro-xfce-override-theme: No such file or directory
```

**Comment by oberon2007** [comment]
Why not just simply patch **gtk/sass/3.22/_3rd-party.scss** ?

**Comment by oberon2007** [comment]
and instead of `color: #16a085;` use `color: $selected_bg_color;`
So it will be applied to both breath and maia accordingly.

**Comment by Ste74** [comment]
damn .. during compiling not see the message .. to testing compile used makepkg lol..
you are right .. tomorrow rebuild it , if you want feel free to correct ;) .. for patch question we have to do any time tista rebuild it and if you see this theme is rebuilded very fast..

**Comment by oberon2007** [comment]
Ok. Will try to package it. 😄

**Comment by oberon2007** [comment]
Ok. Will try to package it. 😄

**Comment by oberon2007** [comment]
It was a bit tricky 😜 The same values didn't just work in the theme itself cause apparently other features are inherited and like that for example unselected label suddenly has regular text color and like that becomes invisible on dark backgrounds.
Fixed now and also added some text-shadow for the white labels to also work more or less on light bachground. 😄

**Comment by oberon2007** [comment]
![sx-wall](https://user-images.githubusercontent.com/11800714/32205755-5f966a48-bdf1-11e7-89d6-ae8afb94bfcc.png)
![blue](https://user-images.githubusercontent.com/11800714/32205753-5f51f78c-bdf1-11e7-8ed4-7fa48b7e54ff.png)
![bright](https://user-images.githubusercontent.com/11800714/32205754-5f735454-bdf1-11e7-9d16-78e3c5fa3186.png)

**Comment by Ste74** [comment]
Thank you mate :D
