### ISSUE TITLE
[kvantum-qt5] KvAdaptaMaia wrong menu highlight color

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#382]
@ceyhunnabiyev could you maybe have a look what happens here in **calamares** for example?

![kvmaia](https://user-images.githubusercontent.com/11800714/31587586-5a707cd4-b1b2-11e7-89cf-ecca500a45c9.png)

**Comment by philmmanjaro** [comment]
@oberon2007: you mean the greenish on the left beneath the **Welcome to ...**

**Comment by oberon2007** [comment]
actually I meant the highlight color in the menu. it is supposed to be maia!

**Comment by philmmanjaro** [comment]
Ah OK, I meant the greenish in the whole window. In the old we had it white and in other themes Calamares is there white as well. Looks a little odd for me. The highlight I didn't noticed so much.

**Comment by oberon2007** [comment]
yeah, it's both not ideal.

**Comment by ceyhunnabiyev** [comment]
@oberon2007 , because in original theme, menu highlight color is not blue:
![screenshot from 2017-10-15 22-53-15](https://user-images.githubusercontent.com/5506156/31587950-c9a7b6be-b1fb-11e7-8c8d-9e5afa250840.png)

**Comment by philmmanjaro** [comment]
@ceyhunnabiyev: can you install Calamares on your end and just open it with the original theme to see if there is some blueish going on on the normal background as I showcased on @oberon2007's screenshot beneath **Welcome to...***

**Comment by oberon2007** [comment]
![cal_kvantumadapta](https://user-images.githubusercontent.com/11800714/31588232-1b9755a4-b1bd-11e7-8935-a2865937d37b.png)

**Comment by oberon2007** [comment]
it's not easy to see but the color picker shows that it is #FAFBFC which is in fact a very slightly bluish white.

**Comment by philmmanjaro** [comment]
Ok, makes sense, so we have to go for a slightly greenish white then. Current colour is not as best as of now. Needs improvement.

**Comment by oberon2007** [comment]
I've still not been able to locate the right properties to fix those hyper-green colors. See my latest attempt [here](https://github.com/manjaro/kvantum-manjaro/commit/3158e3925639b6f2ef8ba2d47afd15ec56e3c362)... 😶 
Doesn't seem to have the desired effect, though:

![colors](https://user-images.githubusercontent.com/11800714/31861094-f3ae463c-b726-11e7-99bc-582a2e76deff.png)

Can you maybe help, @ceyhunnabiyev . Would be much appreciated.

**Comment by oberon2007** [comment]
ok. I'm still finding more color codes that could be relevant ... am on it 😜

**Comment by oberon2007** [comment]
There are in fact more colors taken from that svg file than I thought 😉

**Comment by oberon2007** [comment]
seems I cracked it 😆 

![new_colors](https://user-images.githubusercontent.com/11800714/31861542-4cb819ee-b72f-11e7-8514-b4d21f20d29e.png)

**Comment by ceyhunnabiyev** [comment]
Hi @oberon2007 , sorry for late answer, you changed greenish color to `#d8fdf8`, but I didn't realize something here. You didn't like greenish color, or only lightness is the problem?

**Comment by oberon2007** [comment]
I'm not quite finished, yet. Will look more into it tonight. We are trying to avoid real green colors. The goal with maia colors is always more halfway between blue and green, so some degree of teal.
