### ISSUE TITLE
qt5gtk2: should be rebuilt after each qt5 update.

### ISSUE THREAD

**Issue by TomaszGasior** [manjaro/packages-community#389]
Currently `qt5gtk2` package from Manajro's `community` repository is not usable. When you install it and try to use any Qt5 application with `QT_QPA_PLATFORMTHEME=qt5gtk2` environment variable, app exists with error like this:
`Cannot mix incompatible Qt library (version ...) with this library (version ...)`
When I try to `aur/qt5gtk2` everything works.

It is because `qt5gtk2` **must be rebuilt after each `qt5-base` update**. It would be good if someone from Manjaro's team would take care about it. ;)

**Comment by Ste74** [comment]
You are in stable ?

**Comment by Ste74** [comment]
Done https://github.com/manjaro/packages-community/commit/bfeb889db2a68cb1f025cf23aa1bd9b0e1c59df3
@philmmanjaro we need always this ?

**Comment by Ste74** [comment]
Lol .. i have do in unstable now .. next qt5 update we can drop ;)

**Comment by philmmanjaro** [comment]
We ship it. I just forgot to add the PKGBUILD. @Ste74: can you push it to all branches? When done close this one. Thx.

**Comment by Ste74** [comment]
Done

**Comment by Ste74** [comment]
Done
