### ISSUE TITLE
obmenu-generator

### ISSUE THREAD

**Issue by fhdk** [manjaro/packages-community#393]
AUR version is now obmenu-generator 0.84-1

**Comment by Ste74** [comment]
@fhdk you can build if you need for your future openbox edition or you can't build ?

**Comment by fhdk** [comment]
Oh - I can build it but since @oberon2007 is the maintainer I don't want to step on any toes :)

**Comment by oberon2007** [comment]
Go ahead, @fhdk , my toes are fine! 😆

**Comment by oberon2007** [comment]
done.
