### ISSUE TITLE
rtorrent fails to compile

### ISSUE THREAD

**Issue by raphael-costa** [manjaro/packages-community#394]
This might have been a mistake, but I originally filed this bug in the Arch Linux bug tracker: https://bugs.archlinux.org/task/56252.

But as you can see  it was closed with "Builds fine in a clean chroot". I tried to create the clean chroot with `buildpkg -p rtorrent -cw` but it still failed. I used the PKGBUILD from Arch Linux since it hasn't been uploaded to this repository (it's from 2015) but it's in the Manjaro repositories. (checked here: http://mirror.ventraip.net.au/Manjaro/stable/community/x86_64/). I also tried using devtools just in case but it also failed.

I wonder if the Arch Linux dev even tried to compile rtorrent or just closed the issue because my log didn't build it in a clean root but at any pace I'm posting the issue here first.

**Comment by oberon2007** [comment]
The **rtorrent** package in the Manjaro repos is indeed a package inherited from upstream Archlinux. We never built it ourselves. So whatever is wrong with the package concerns Archlinux (or their upstream source respectively.
```
$ pacman -Si rtorrent
Repository      : community
Name            : rtorrent
Version         : 0.9.6-3
Description     : Ncurses BitTorrent client based on libTorrent
Architecture    : x86_64
URL             : http://rakshasa.github.io/rtorrent/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : libtorrent=0.13.6  curl  xmlrpc-c  libsigc++
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 445,02 KiB
Installed Size  : 1645,00 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Mo 07 Dez 2015 08:02:44 CET
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

**Comment by oberon2007** [comment]
I just tried building it with buildpkg and it does build without problem. So the issue must be somewhere on your end.
What error exactly to you get?

**Comment by oberon2007** [comment]
See [buildlog](https://pastebin.com/iLSGwkFp). Everything fine with the PKGBUILD and buildpkg.

**Comment by raphael-costa** [comment]
I noticed you're on the unstable branch and weirdly enough, the package fails rather quickly using the stable branch but everything worked when I passed the `-b testing` flag. I guess I'll switch to testing as a workaround since I really want rtorrent patched.

For reference, [https://pastebin.com/vJ9U3neH](here) is the stable branch failed build log.

**Comment by oberon2007** [comment]
Yes, that's strange. It's not obvious to me which package might be the problem here. - In any case it will be fixed with the next stable snapshot... 😉
