### ISSUE TITLE
Package thunar-shares-plugin-manjaro not work

### ISSUE THREAD

**Issue by LaLadaLa** [manjaro/packages-community#395]
This package https://github.com/manjaro/packages-community/tree/master/thunar-shares-plugin-manjaro not work for new users because this commit https://github.com/manjaro/packages-community/commit/035253334ab4e995e8817ea44553639f123e7e75#diff-df8c7d201a5afe3541a1d9eed6e53bed deleted file smb.conf.

The smb.conf file is new in the package https://github.com/manjaro/packages-extra/tree/master/manjaro-settings-samba but does not include:
[global]
   ...
   security = user
   guest account = nobody
   usershare path = /var/lib/samba/usershare
   usershare max shares = 100
   usershare owner only = yes
   group = sambashare
   force create mode = 0070
   force directory mode = 0070
   ...

**Comment by Ste74** [comment]
Hi, since we don't use more samba can you please test this [config](https://github.com/NuLogicSystems/PKGBUILD/tree/master/nulogic-settings-samba). The idea is to do a smb.conf for general purpose and ready OOTB ..

**Comment by LaLadaLa** [comment]
Hi.
I think that:
1.) "client max protocol = NT1" is not a good solution. E.g. LE 8.1.1 does not use SMB1(NT1) by default (see https://libreelec.tv/2017/09/libreelec-krypton-v8-1-1-beta/ ). The SMB1(NT1) protocol is obsolete with security risk. Forcing users to turn on SMB1 on LE device is the wrong way.
2.) The best solution is to wait for the gvfs-smb package to be fixed, which is probably why the "smb:///" (Windows Network) address is empty in Thunar.
3.) The best temporary solution is to fix "hostname.local" according to the instructions https://github.com/manjaro/packages-core/pull/85. The "smb:///" (Windows Network) address will still be empty, but it will have access via icons directly from "network:///" (Browse Network).

**Comment by Ste74** [comment]
Thank you @LaLadaLa  for your explaination .. feel free to add other contribute for samba config
Closed via https://github.com/manjaro/packages-extra/commit/e81e11a3539033bbbe1bb75faff827d50d6f6f41
