### ISSUE TITLE
Request Hyper

### ISSUE THREAD

**Issue by codesardine** [manjaro/packages-community#396]
Any chance we can have Hyper shell in the repos?  as i will like to ship it with Manjaro WebDad,
there is a package in the aur is also flaged out of date.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hyper

https://hyper.is/

Hyper has been downloaded more than 250,000 times and has over 300 themes and extensions. And he points to test results that suggest Hyper is comparable to PowerShell in terms of its effect on other executables.

src = https://www.theregister.co.uk/2016/12/13/hyper/

**Comment by Ste74** [comment]
Hi Vitor.. sure. Let me work on it today..

**Comment by codesardine** [comment]
I feel bad for asking you for stuff all the time but i am not very good with shell scripting tanks.

**Comment by Ste74** [comment]
Don't worry.. i'm not able to build a JADE desktop :) .. only when a new release of hyper is out please  inform us or correct the pkgbuild to inform us ;)

**Comment by codesardine** [comment]
Ok will do

**Comment by Ste74** [comment]
Done https://github.com/manjaro/packages-community/commit/c95a8c5b873cb7add27b958f3ce955652acea58e .. only in x86_64 repo

**Comment by codesardine** [comment]
thanks :+1:
