### ISSUE TITLE
MATE packages are obsolete

### ISSUE THREAD

**Issue by jonathonf** [manjaro/packages-community#397]
There are a number of PKGBUILD sources in the repo that are obsolete and have been removed from the overlay packages.

This issue will track these packages.

**Comment by jonathonf** [comment]
## MATE

- [ ] marco-1.18.0-1.1
- [ ] mate-backgrounds-1.18.0-0.1
- [ ] mate-common-1.18.0-0.1
- [ ] mate-control-center-1.18.0-0.1
- [ ] mate-desktop-1.18.0-1.1
- [ ] mate-icon-theme-1.18.0-0.1
- [ ] mate-icon-theme-faenza-1.18.0-0.1
- [ ] mate-indicator-applet-1.18.0-1
- [ ] mate-media-1.18.0-0.1
- [ ] mate-menu-17.04.2-0.1
- [ ] mate-menus-1.18.0-0.1
- [ ] mate-netbook-1.18.0-0.1
- [ ] mate-notification-daemon-1.18.0-0.1
- [ ] mate-panel-1.18.0-0.1
- [ ] mate-polkit-1.18.0-0.1
- [ ] mate-power-manager-1.18.0-0.1
- [ ] mate-screensaver-1.18.0-0.1
- [ ] mate-sensors-applet-1.18.0-0.1
- [ ] mate-session-manager-1.18.0-0.1
- [ ] mate-settings-daemon-1.18.0-0.1
- [ ] mate-system-monitor-1.18.0-0.1
- [ ] mate-terminal-1.18.0-0.1
- [ ] mate-themes-3.22.7-0.1
- [ ] mate-user-share-1.18.0-0.1
- [ ] mate-utils-1.18.0-0.1-
- [ ] mate-wallpapers-20171112-1

**Comment by Ste74** [comment]
Yep .. are obsolete but are usefull if we need again.. do you think if we create a repo where archive any pkgbuild not used now but for possible re use ?

**Comment by jonathonf** [comment]
The point of revision control is that old source still exists in older revisions. Plus, these packages have "upstream" sources at Arch.

**Comment by oberon2007** [comment]
Yes. Everything currently not used and outdated can safely be removed. It won't be lost anyway.

**Comment by Ste74** [comment]
I see now what you guys mean .. ok , let me purge the not needed packages

**Comment by jonathonf** [comment]
https://github.com/manjaro/packages-community/commit/6d009ca6d5b32bd27b9a7662d855347c1e8bbe30
