### ISSUE TITLE
linux-rt-lts-manjaro is behind upstream patch version

### ISSUE THREAD

**Issue by jonathonf** [manjaro/packages-community#399]
linux-rt-lts-manjaro is patch version 4.9.47, upstream is 4.9.61.

```
$ pacman -Ss linux49
core/linux49 4.9.61-3
    The Linux49 kernel and modules
core/linux49-headers 4.9.61-3
    Header files and scripts for building modules for Linux49 kernel
...
```

**Comment by oberon2007** [comment]
It's the latest available patch
https://www.kernel.org/pub/linux/kernel/projects/rt/4.9/

**Comment by jonathonf** [comment]
Patching against 4.9.61 [mostly succeeds](https://github.com/manjaro/packages-community/files/1464675/patch-result.txt). All but one applies with offsets, the one failing patch is:

```
patching file block/blk-core.c
Hunk #2 FAILED at 236.
1 out of 10 hunks FAILED -- saving rejects to file block/blk-core.c.rej
```

**Comment by oberon2007** [comment]
Could you post the content of block/blk-core.c.rej please?
Normally I just wait for the upstream patch updates. Adjusting the
patches to newer basekernel-patches often is tedious and messy and I am
certainly not knowledgeable enough about kernel source code to deem
myself qualified to tackle these things...

**Comment by jonathonf** [comment]
```
--- block/blk-core.c
+++ block/blk-core.c
@@ -236,7 +239,7 @@ EXPORT_SYMBOL(blk_start_queue_async);
  **/
 void blk_start_queue(struct request_queue *q)
 {
-       WARN_ON(!irqs_disabled());
+       WARN_ON_NONRT(!irqs_disabled());
 
        queue_flag_clear(QUEUE_FLAG_STOPPED, q);
        __blk_run_queue(q);
```

block/blk-core.c has a slight difference but updating the specific patch shouldn't introduce anything nasty:

```
void blk_start_queue(struct request_queue *q)
{
    WARN_ON(!in_interrupt() && !irqs_disabled());

    queue_flag_clear(QUEUE_FLAG_STOPPED, q);
```

**Comment by jonathonf** [comment]
Info from upstream:

On 13/11/17 16:55, Julia Cartwright wrote:
> On Sun, Nov 12, 2017 at 03:32:02PM +0000, Jonathon Fernyhough wrote:
>> Hi!
> 
> Hello Jonathon-
> 
>> How do the -rt patches match up against mainline and any security
>> fixes?  For example, mainline LTS 4.9 is version 4.9.61, but 4.9-rt is
>> version 4.9.47.
> 
> Yes, as of right now, the current 4.9-rt stable release is out of date,
> and is due for a refresh.
> 
> All of the maintained stable-rt releases effectively have two upstreams:
> the upstream stable releases (4.9.61 as you've mentioned), which bring
> in bug fixes from mainline, and secondly the latest rt-devel development
> tree.  RT specific bug fixes from the rt-devel tree are cherry-picked
> back to the relevant stable-rt releases.
> 
> We acknowledge we're a bit behind, and are currently in the process of
> reshuffling around the stable-rt release work.
> 
>> Is mainline 4.9.47 with -rt37 secure (etc.), or should the 4.9.47-rt37
>> patch-set be applied against the latest mainline point-release?
> 
> As Uwe mentioned, it's possible that you can just merge in the latest
> upstream 4.9.y release for your usecase.  Otherwise, you can wait for us
> to kick out an updated release (hopefully soon).
> 
> Thanks,
>    Julia
> 

So it looks like the patches might need to be applied to newer mainline releases... :frowning_face:

**Comment by philmmanjaro** [comment]
Ya, it takes always a while until they can catch up. Musicians rather use the function than the security. It always depends if there are needed security patches out there to be added manually if needed until they will update to the latest. Their testing process takes longer as mainline.

**Comment by jonathonf** [comment]
I meant more that we should be applying the patches to the latest LTS point-release rather than waiting for a new release from the RT project. This way all of our users will have secure kernels.

Of course, this isn't always going to be easy, but it's worth trying, and in the current case the changes are quite small.

**Comment by oberon2007** [comment]
It may be just one line in this case, but
1) you'd need to know what exactly
`WARN_ON(!in_interrupt() && !irqs_disabled());`
does and how to correctly adjust the patch. I don't.
2) in other cases in the past the discrepancies anyway were a lot bigger and as I already said it's way above my head to assess the changes in a competent and safe manner.
3) The typical situations where rt-kernels are used are not everyday environments but dedicated studio equipment.
4) basekernel patch updates being available don't necessarily mean that staying behind a few weeks will actually pose any security issues.
So what I am happy to offer on a regular basis is updating rt-patches as soon as upstream provides them.
But I am happy to leave the patch updates to you if you.
