### ISSUE TITLE
linux-rt-manjaro is based on EOL and unmaintained kernel series

### ISSUE THREAD

**Issue by jonathonf** [manjaro/packages-community#400]
`linux-rt-manjaro` is based on kernel 4.11.12 which went EOL in July 2017: https://lkml.org/lkml/2017/7/21/30

**Comment by jonathonf** [comment]
For info, https://cdn.kernel.org/pub/linux/kernel/projects/rt/4.13

**Comment by oberon2007** [comment]
The 4.13-rt patch is the only newer alternative and still quite new. Lots of adjustments are curretnly still being discussed if you follow the rt mailing list.
Anyway I'm about to switch to 4.13 base in the near future.

**Comment by oberon2007** [comment]
They just released a first patch version for linux 4.14. So I think it will make sense to skip 4.13 altogether...
