### ISSUE TITLE
thunderbird-kde PKGBUILD is out-of-date

### ISSUE THREAD

**Issue by jonathonf** [manjaro/packages-community#404]
thunderbird-kde is 52.4.0-1 in the repos, the PKGBUILD is 52.3.0-2.

```
$ pacman -Ss thunderbird-kde
community/thunderbird-kde 52.4.0-1
    Standalone mail and news reader from mozilla.org
```

**Comment by Kirek** [comment]
https://github.com/manjaro/packages-community/commit/21aff7eb9534fab523fe10500498d5c45de58978
