### ISSUE TITLE
Adapta gpg key

### ISSUE THREAD

**Issue by Ste74** [manjaro/packages-community#410]
@jonathonf , @oberon2007 : try to [update](https://github.com/manjaro/packages-community/commit/a2e36267176d2c1db0d1ad03de4aacfcb11627d9) adapta themes but now the gpg validation is wrong .. 
` adapta-gtk-theme-3.92.1.108.tar.gz ... FAILED (unknown public key 16A443152D7A865E)`
[here](https://pgp.mit.edu/pks/lookup?search=Tista&op=index) the keys of Tista .. what is wrong now ?

**Comment by jonathonf** [comment]
Have you imported the key, `gpg --recv-key 16A443152D7A865E` ?

**Comment by Ste74** [comment]
But why i have to imported if working in a clean chroot ? ( newbie question ;) )

**Comment by jonathonf** [comment]
Because it's not in the Arch or Manjaro keyrings.

**Comment by Ste74** [comment]
LOL thank you .. already say newbie question .. I hurt a tooth I'm a bit rickety
