### ISSUE TITLE
[arc-themes-manjaro] Do we need to create assets for old GTK versions?

### ISSUE THREAD

**Issue by jonathonf** [manjaro/packages-community#413]
For example:

https://github.com/manjaro/packages-community/blob/f2a1c730d01d5723061035fd4da8b6ce4543380f/arc-themes-manjaro/PKGBUILD#L395

Manjaro only has a single GTK3 version available, so is there any need to render assets for older versions too?

**Comment by Ste74** [comment]
Do you mean ?

**Comment by jonathonf** [comment]
I think so? I don't see why we'd package anything that's for any versions _not_ in the repos?

In this example, the PKGBUILD is building assets for GTK3 3.14, which isn't in Manjaro; this seems like a waste of time and makes the packages larger than they need be.

**Comment by Ste74** [comment]
Uhmm .. ok i can see to build adapta without gtk 3.18 assets ( all depends if the theme in configure.ac manage this flag and for adapta the answere is yes )  , for now i wont touch arc themes because this theme seem dead and in the future i think to remove it if nobody adopt upstream code.

**Comment by oberon2007** [comment]
Uhm ... What exactly do you want to remove?
```
adapta-maia-theme /usr/share/themes/Adapta-Maia/gtk-3.0/
adapta-maia-theme /usr/share/themes/Adapta-Maia/gtk-3.0/gtk-dark.css
adapta-maia-theme /usr/share/themes/Adapta-Maia/gtk-3.0/gtk.css
adapta-maia-theme /usr/share/themes/Adapta-Maia/gtk-3.0/gtk.gresource
adapta-maia-theme /usr/share/themes/Adapta-Maia/gtk-3.22/
adapta-maia-theme /usr/share/themes/Adapta-Maia/gtk-3.22/gtk-dark.css
adapta-maia-theme /usr/share/themes/Adapta-Maia/gtk-3.22/gtk.css
adapta-maia-theme /usr/share/themes/Adapta-Maia/gtk-3.22/gtk.gresource
```

**Comment by Ste74** [comment]
Good, don't see the final result :p , only in the adpata-repo .. but now see this

> 
>     To enable extra Gtk+ release support, pass these options:
> 
> --enable-gtk_legacy    enable Gtk+ 3.18 support (type: bool)
> --enable-gtk_next      enable Gtk+ 4.0 support (type: bool)
> 

.. legacy support is optional and we don't use ;)

**Comment by oberon2007** [comment]
sure! makes sense 😃 👍

**Comment by Ste74** [comment]
Uhmm it seems that someone tries to keep this theme .. i can do a shot
https://github.com/NicoHood/arc-theme

**Comment by Ste74** [comment]
Work in upstream to merge theme in the source
https://github.com/NicoHood/arc-theme/issues/12
