### ISSUE TITLE
[gnome-shell-extension-manjaro-update bug] Bump pending updates for ignored packages.

### ISSUE THREAD

**Issue by ceyhunnabiyev** [manjaro/packages-community#414]
I have ignored  AUR  package. Pamac says there is no updates, but  gnome-shell-extension-manjaro-update bumps pending update for this.

Thanks for this great extension..

**Comment by Ste74** [comment]
@Chrysostomus any idea why this happen? I'm happy to use update-notifier but only to knowling @guinux is possible use pamac to showing the updates ? This extension already use pamac to install

**Comment by Chrysostomus** [comment]
It uses either pacaur or yaourt to query updates. I'll see to it that Ignorepkg is respected. 

Using pamac to update should be the default currently. Is it not?

**Comment by Ste74** [comment]
> Using pamac to update should be the default currently. Is it not?

yep , is it

**Comment by ceyhunnabiyev** [comment]
Seems like neither pamac nor this extension works properly with AUR ignored packages.

**Comment by Ste74** [comment]
I think i can close this issue.. @ceyhunnabiyev ?

**Comment by ceyhunnabiyev** [comment]
But this is not fixed . Right now I checked, it shows pending ignored AUR packages.

**Comment by Ste74** [comment]
What is your aur helper ?

**Comment by ceyhunnabiyev** [comment]
I have both of them, I don't know exactly  which of them that pamac or this extension refer.

**Comment by Ste74** [comment]
Try to remove pacaur.. In this case the script will use yaourt. Check if the issue is still present..

**Comment by ceyhunnabiyev** [comment]
Still same problem:
![screenshot from 2018-01-31 00-35-07](https://user-images.githubusercontent.com/5506156/35589891-a6568182-061e-11e8-97d6-00d25d105dcd.png)

**Comment by ceyhunnabiyev** [comment]
yaourt -Syua shows me correct pending packages, but this extension not.

**Comment by ceyhunnabiyev** [comment]
@Ste74 , if you don't have time, please ignore this, this is a just example. I think It is not important for me or others right now.

**Comment by Ste74** [comment]
Don't worry .. i'm curios .. since also `pacui` use wrapper to update the packages if user install it @excalibur1234, @Chrysostomus how we can manage it or how `pacui`manage it ( `ignorepkg` )

**Comment by Ste74** [comment]
Well is a upstream issue ..**Yaourt** and **Pacaur** not support `--ignore` flag how **pacman** do @Chrysostomus 

https://github.com/rmarquis/pacaur/issues/626
https://github.com/archlinuxfr/yaourt/issues/331

**Comment by Chrysostomus** [comment]
I'll see if it works with yay, I hope we can replace yaourt with it in the future.

**Comment by Ste74** [comment]
@ceyhunnabiyev is still present the issue after this update ? 
https://github.com/Chrysostomus/update-notifier/commit/0121b7eba0d49fcbed4effbe2bf17baea14bfd9f

**Comment by ceyhunnabiyev** [comment]
Hi @Ste74 ,

> is still present the issue after this update ?

No. Thanks a lot.
