### ISSUE TITLE
depmod for new linux414-rt fails

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#415]
I've prepared a new rt version for basekernel 414.
For some reason depmod fails with
```
depmod: ERROR: fstatat(3, extramodules): No such file or directory
```
@philmmanjaro would you like to have a look at it?

**Comment by philmmanjaro** [comment]
Based on which PKGBUILD? Maybe try with the [old structure](https://github.com/manjaro/packages-core/blob/1c2f0d44b5b783af6a247a1ba6e88e84d3bc36ea/linux414/PKGBUILD) first.

**Comment by oberon2007** [comment]
I was able to fix is based on the old structure, yes. Thank you 👍 
Will look into why the new one didn't play another time.
In any case building the new extramodules now and will push 414-rt later then.
