### ISSUE TITLE
kio-sysinfo ?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#418]
This package is old and apparantly unmaintained. Is it still in use or should we remove it?
https://websvn.kde.org/trunk/playground/base/kio_sysinfo/
@philmmanjaro

**Comment by Ste74** [comment]
@Kirek ?

**Comment by philmmanjaro** [comment]
@oberon2007: point me to the PKGBUILD pls.

**Comment by Kirek** [comment]
https://github.com/manjaro/packages-community/tree/master/kio-sysinfo
Very old package, I think it can be removed without any problems. Also only useful for konqueror.

**Comment by Ste74** [comment]
Removed: not updated and maintained in upstream
 https://github.com/manjaro/packages-community/commit/2b90dc076dd8aaafdaef5ea0009172448db0f41f
