### ISSUE TITLE
Hyper libgtk-x11-2.0.so.0 missing.

### ISSUE THREAD

**Issue by codesardine** [manjaro/packages-community#420]
This only happens on testing and unstable branch, the package lib32-gtk2 has this library and making it a dependency of hyper fixes it. @Ste74 

On stable i dont have lib32-gtk2 package installed and hyper works fine.
any idea what could be causing this?
is this an issue i should open on hyper upstream?

**Comment by Ste74** [comment]
I don't know what happen.. installed `hyper` in my pc and it work ( unstable branch ) .
`lib32-gtk2` is not installed in my system..
You use a plugin ? ( not know `hyper` ) 
BTW `gtk2 ` is installed ?

**Comment by codesardine** [comment]
Yeah i was doing an iso build and missing gtk2 in the package list, should we make that a dependency for hyper?

**Comment by Ste74** [comment]
I can add it .. this means that your iso is just gtk3..

**Comment by codesardine** [comment]
yeah gtk3 software, a few QT, im working on it

**Comment by Ste74** [comment]
done fa1b5342357bbe38eeed557f6864f6d96424cbee

**Comment by codesardine** [comment]
tanks you are fast trigger, i was about to send a pull request
