### ISSUE TITLE
Patch for Cinnamon in Adapta

### ISSUE THREAD

**Issue by Ste74** [manjaro/packages-community#423]
@oberon2007 i can remove your patch ? 
See [here](https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.92.2.3)

**Comment by oberon2007** [comment]
Let me try it! Thank you for notifying! 😄

**Comment by oberon2007** [comment]
So, we have to keep the patch. The latest adjustments don't cover all the thumbnail issues. But since we have the proper ones included via my [cinnamon fork](https://github.com/oberon2007/Cinnamon/commit/85e61176b5605ea378caf97e962b6d4f14951fce) we're good to go like that 😄
