### ISSUE TITLE
[Feature Request] kvantum-manjaro for qt4 applications like VLC

### ISSUE THREAD

**Issue by ceyhunnabiyev** [manjaro/packages-community#427]
Qt4 and Qt5 Separately:
https://github.com/tsujan/Kvantum/blob/master/Kvantum/Arch/Qt4/cmake/PKGBUILD
https://github.com/tsujan/Kvantum/blob/master/Kvantum/Arch/Qt5/cmake/PKGBUILD

It would be nice to use Adapta for both Qt4 and Qt5 applications in Gnome..

**Comment by Ste74** [comment]
Not only in gnome .. let me work on it

**Comment by ceyhunnabiyev** [comment]
> Not only in gnome .. let me work on it

Sorry. I use only Gnome, that is why I said it.

>  is necessary additional configurations to work ?

I don't know exactly, but it is strange that upstream (Archlinux) only packaged kvantum-qt5, not qt4. I see only following difference (First one for qt4, second one for qt5):
```
cmake -DENABLE_QT4=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr
```
Kvantum-qt5 PKGBUILD in Archlinux:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/kvantum-qt5

**Comment by Ste74** [comment]
You use both in your system?

**Comment by ceyhunnabiyev** [comment]
No, just I see that famous application VLC  doesn't use kvantum-Adapta, overrides Adapta-gtk2, and it doesn't look cool. I searched that kvantum has qt4 variant. That is why I shared with you. I didn't test it.

**Comment by philmmanjaro** [comment]
**qt4** is mostly depreciated. Maybe you try **vlc-nightly**, which is **qt5** based and currently at version **v3.0-rc3**. 

@Ste74: if you want to maintain also a **qt4** based theme, go ahead. No pressure :smile:

**Comment by Ste74** [comment]
😜 I see now .. I do not use most of the qt apps in my end .. in the end i'm not sure if the effort is worth the result

**Comment by ceyhunnabiyev** [comment]
It is your decision, of course. I just suggested :wink:.
