### ISSUE TITLE
dmenu-manjaro

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#428]
@jonathonf I just saw that you had updated **dmenu-manjaro** in boxit. I've removed the package again because it was intentional to keep the old version for now.
@Chrysostomus and I are still waiting - or hoping for the patches to be updated.
The updates to core dmenu are not obviously important but on the other hand without the patches we use functionality of the older patched version.
Thank you.

**Comment by jonathonf** [comment]
OK, then we need to come up with a branch or tagging structure to make this clear. For example, keep pre-release package files in their own branch (e.g. `git branch dmenu-manjaro-4.7`). IMHO the repo state should really reflect the current state of packages in the repos.

**Comment by jonathonf** [comment]
I've updated the patches, but they need testing:

https://github.com/manjaro/packages-community/pull/429

**Comment by oberon2007** [comment]
Cool! @Chrysostomus would you like to check linehight- and xy-functions? I'm not familiar with those...

**Comment by oberon2007** [comment]
Just verified `-h` option seems to work fine.

**Comment by oberon2007** [comment]
And I got it now also how the -xyw options work.
Great job, @jonathonf , thank you! We can keep the patches like that, awesome!

**Comment by jonathonf** [comment]
The patches were added/accepted upstream:

https://git.suckless.org/sites/commit/?id=f864cef810f877c772078d8c68854a6e6fef34f2
https://git.suckless.org/sites/commit/?id=1cb61f172c7088556e608394e7dad4474f2ed380

I hope they don't break dmenus worldwide... :worried:
