### ISSUE TITLE
purple-whatsapp needs recompilation

### ISSUE THREAD

**Issue by ivoshm** [manjaro/packages-community#437]
Dependent library *protobuf-c* is on version 15 now but in package is needed level 9.

Thanks.

**Comment by Ste74** [comment]
Not sure we need this in our repo ... 
@philmmanjaro , @oberon2007 , @jonathonf .. any purple pkgs present in our overlay was added for sonar spin. I'm for drop this pkgs from our repository.. objections ?

**Comment by oberon2007** [comment]
I agree. sonar editions are no longer maintained.

**Comment by Ste74** [comment]
Done https://github.com/manjaro/packages-community/commit/00d579aa6a564ce8f88dc301b4cc3d2c47882045
