### ISSUE TITLE
snapd-git  conflict

### ISSUE THREAD

**Issue by bn0785ac** [manjaro/packages-community#439]
snapd-gt has a conflict

**Comment by Ste74** [comment]
What exactly ?

**Comment by bn0785ac** [comment]
snapd-git: /snap exists in filesystem

original log (at spanish)

snapd-git: /snap existe en el sistema de archivos

**Comment by Ste74** [comment]
You have installed snapd before from our repo or via other way ?

**Comment by bn0785ac** [comment]
before,  from repo (community)

**Comment by Ste74** [comment]
The  snapd and snapd-git are in conflicts .. all is fine in my hands.. for solve your issue simply remove snap present in your system 
`sudo rm /snap `

**Comment by bn0785ac** [comment]
i'm testing it

this was my content https://p.teknik.io/Simple/COxcl

i've run sudo rm -rf /snap

i'll test
