### ISSUE TITLE
compiz-manjaro out of date

### ISSUE THREAD

**Issue by dastious** [manjaro/packages-community#44]
There is a new little milestone version.
https://launchpad.net/compiz/+milestone/0.9.12.2

**Comment by korrode** [comment]
Yeah i know, I just haven't got around to it.
It's more than simply a version and checksum bump. There's some patches that need removing and some new ones i need to review.

I'll try get to it all tonight.

**Comment by philmmanjaro** [comment]
No problem. Take all the time you need. I noticed that this package needs more attention than usual. So far, great job Rob.

**Comment by korrode** [comment]
Sorry for delays.

Closing:
76ae0d804ec1a20cd303241fc209ebba2942d668

**Comment by philmmanjaro** [comment]
Hey Rob, no problem at all.

**Comment by dastious** [comment]
No problem, thank you very much.
