### ISSUE TITLE
catalyst compiling error with mpfr 4.0.0

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#445]
**catalyst** extramodules still need to be compiled using **gcc49**
With latest **mpfr 4.0.0** now I run into this error for rt extramodule:
```
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/cc1: error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory
```
Can this be solved this with by symlinking (how would I do that in a PKGBUILD ?) or will we need an older version of **mpfr**?

**Comment by oberon2007** [comment]
I created a symlink now manually in the chroot in **/var/lib/manjaro-tools/buildpkg/x86_64/bernhard/usr/lib** and the package builds like this.
Hope it will be alright like this.
Question still is how can we properly solve this for the future?

**Comment by oberon2007** [comment]
I min-package **mpfr-gcc49** to just create the symlink in the chroot as a makedepends, maybe?

**Comment by philmmanjaro** [comment]
I've to recompile the compiler. However it seems there is another solution for it also. Let me check some.

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/packages-extra/commit/856617ea2537c7a195ea64225a40c2f8d52a8a7a

**Comment by oberon2007** [comment]
Great! Thank you :)
