### ISSUE TITLE
vlc-nightly segfault

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#450]
I just rebuilt version 4.0.0-20171130-0243-git (didn't want to use an even newer one since they have gone back to dev status with those.
That didn't help. Still segfaulting...

**Comment by oberon2007** [comment]
One possibility would be that the latest xorg-server update broke it... Trying to verify.

**Comment by oberon2007** [comment]
Just saw this during installation:
```
:: Running post-transaction hooks...
(1/4) Updating icon theme caches...
(2/4) Arming ConditionNeedsUpdate...
(3/4) Updating the desktop file MIME type cache...
(4/4) Updating the vlc plugin cache...
error: command terminated by signal 11: Segmentation fault
```
weird!

**Comment by jonathonf** [comment]
I'd stick with the 3.0.0 series for `vlc-nightly` until 3.0.0 has been released.

We also might need a transition plan for people who got `vlc-nightly` as part of their default applications (e.g. to avoid the Qt4 dep). It's no good taking them from a working application (3.0.0) to a non-working unstable application (4.0.0) when `vlc` goes from 2.2.8 to 3.0.0.

**Comment by philmmanjaro** [comment]
v3.0-rc9 is now the current one I pushed.

**Comment by philmmanjaro** [comment]
In regard of **xorg-server** you may install **xorg-fonts-misc** as it got removed as dep with [this](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/xorg-server&id=b0a1c2fbb6ff248ba37914218c29c43243d6e237).

**Comment by oberon2007** [comment]
Seems the vlc segfault was caused by a foreign ffmpeg version on my system.
