### ISSUE TITLE
pkgver should reflect upstream version

### ISSUE THREAD

**Issue by jonathonf** [manjaro/packages-community#454]
https://github.com/manjaro/packages-community/blob/2733949fbee17b8853e29f40af47f90ceca64d7d/deepin-manjaro/deepin-desktop-base/PKGBUILD#L8

The `pkgver` variable should [match the upstream release](https://wiki.archlinux.org/index.php/PKGBUILD#pkgver).

In this case, upstream's version is carried in `_pkgrel` instead:

https://github.com/manjaro/packages-community/blob/2733949fbee17b8853e29f40af47f90ceca64d7d/deepin-manjaro/deepin-desktop-base/PKGBUILD#L7

If the change is only in the packaging file then only the `pkgrel` value needs to be incremented. If it's a new upstream version then `pkgver` should be updated.

At this point, a change to the `pkgrel` to match the upstream scheme would result in the package being "older" than the previous,

```
$ vercmp 20180117 2018.01.17
1
```

So, this would require one of:

1. a downgrade by users;
2. introduction of an epoch (`1:2018.01.17`);
3. maintaining the current approach.

**Comment by oberon2007** [comment]
In this case the package is actually quite different from upstream and it seems nonsensical to reflect a pkgver that doesn't even make sense in context of Deepin versioning.
I don't think it we need to bother in this specific case to introduce an epoch or have users downgrade.
Additionally although the pkgname sounds important its content is actually of minor importance. Most of the original upstream content isn't even installed on Manjar ;)

**Comment by oberon2007** [comment]
Neither does 2017.11.1 reflect any of the other deepin pkgvers, nor the version of the desktop, which is currently 15.5 ;)

**Comment by jonathonf** [comment]
The `source` URL refers to an upstream release, https://github.com/linuxdeepin/deepin-desktop-base/releases/tag/2017.11.1 (which has a version number). The Manjaro PKGBUILD uses that version, hence the `pkgver` should reflect the upstream version rather than "inventing" our own.

Just to say, this isn't really important, it's just a potential improvement for our packaging process.

**Comment by oberon2007** [comment]
See commit. We have to use epoch 2 now because we were already at epoch 1 ... that's why I wanted to avoid it but ok.

**Comment by jonathonf** [comment]
> that's why I wanted to avoid it but ok.

This is fine - if we want rid of the epoch we can remove it later and allow people to downgrade as the package version will look similar at that point. It's not like other packages don't do the same thing. :)

**Comment by oberon2007** [comment]
It seems totally unreasonable to cause confusion for the users by them having to downgrade an unimportant package just for number esthetics. Lets just leave it like that.

**Comment by jonathonf** [comment]
You're the one who mentioned that you didn't want the epoch, but that's fine. Leave it as-is.
