### ISSUE TITLE
Volnoti

### ISSUE THREAD

**Issue by dazWiLLiE** [manjaro/packages-community#459]
Problem: had volnoti from AUR, get question to replace with the community version, when I do that..

`:: Replace volnoti with community/volnoti? [Y/n]

error: could not remove database entry volnoti-0.1.r3.gc5a94af-2
error: could not remove entry 'volnoti' from cache`

I removed volnoti (sudo pacman -R volnoti), removed the cached file (/var/cache/pacman/pkg/volnoti-0.1.r3.gc5a94af-2-x86_64.pkg.tar.xz), and installed volnoti with pacman.

After sudo pacman -Syu, I still get:
`:: Replace volnoti with community/volnoti? [Y/n]`

It just loops?

**Comment by Ste74** [comment]
@Chrysostomus ?? Why use conflicts+replace? I think you have to remove this :P 
https://github.com/manjaro/packages-community/commit/264e4ecc482f21397b085b0cff9e1ce05965afac#diff-1d4420ece24fa3bb4f82fa217ba947b4R13

**Comment by oberon2007** [comment]
I guess that was just leftovers from a copied git-PKGBUILD :wink: 
provide and replace of course don't make sense for the package itself. Also conflicts only makes sense in the **volnoti-brightness-git** package and it's properly listed there.

**Comment by Chrysostomus** [comment]
Yes, this was an leftover error
