### ISSUE TITLE
rm conflict papirus-maia papirus-icon-theme

### ISSUE THREAD

**Issue by oberon-manjaro** [manjaro/packages-community#475]
@Ste74 is it really necessary that **papirus-maia-icon-theme** conflicts **paprius-icon-theme**? Is is not using different target dirs anyway?
It would be nice to be able to install both. In case of Deepin currently the maia version cannot be installed at all because **deepin-icon-theme** depends on papirus-icon-theme ... ;)

**Comment by Ste74** [comment]
You can see [here](https://github.com/manjaro/packages-community/blob/master/papirus-maia-icon-theme/PKGBUILD#L67) why i add the conflicts.. this icon theme is really complex in the tree.. most icons are symlinked with the main papirus folder so when i changed the name and for not searching all icons with symlink i have recreated the original folder :p .. if you install the original papirus icons theme you broke the maia versions...

**Comment by Ste74** [comment]
@oberon2007 
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1221
:stuck_out_tongue_winking_eye:

**Comment by oberon2007** [comment]
Great! Thank you! :+1:

**Comment by Ste74** [comment]
@oberon2007 
https://github.com/manjaro/packages-community/commit/530d4368d7f2eac736e36b9364eb5349fbd48309
It is ok :smile:

**Comment by oberon2007** [comment]
COOOL!! :tada: :champagne:

**Comment by Ste74** [comment]
:beers: for @PapirusDevelopmentTeam :smile:
