### ISSUE TITLE
The package dotnet-runtime is out of date

### ISSUE THREAD

**Issue by instalab** [manjaro/packages-community#484]
Hi I used arch before but now I am using Manjaro.
The problem is with that package [Arch Linux - dotnet-runtime 2.0.6-1 (x86_64)](https://www.archlinux.org/packages/community/x86_64/dotnet-runtime/)
It was flagged out of date and the old version is incompatible with ncurses 6.1.
I've created the updated PKGBUILD's for dotnet-sdk and dotnet-runtime and published them on by github.
It was confirmed that the patch fixes the bug: [System.Console fails with ncurses 6.1](https://github.com/dotnet/corefx/issues/26966#issuecomment-382608293)

Could we maybe update these packages in the official Manjaro Repositories?

**Comment by jonathonf** [comment]
Arch package is now at 2.0.7-1.
