### ISSUE TITLE
wrong syntax in [lightdm-settings] .install script

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#485]
@Ste74 `msg` is a command only known inside **manjaro-tools**! :stuck_out_tongue_winking_eye: 
```
/tmp/alpm_I9fRc4/.INSTALL: line 30: syntax error near unexpected token `}'
/tmp/alpm_I9fRc4/.INSTALL: line 30: `}'

/tmp/alpm_I9fRc4/.INSTALL: line 6: msg: command not found
/tmp/alpm_I9fRc4/.INSTALL: line 7: msg: command not found
```
**lightdm-settings** .install script needs a little fix!

**Comment by Ste74** [comment]
@oberon2007 you know why this way ? 
https://github.com/linuxmint/slick-greeter/releases
Why not release a number but this package ?

**Comment by Ste74** [comment]
Closed via https://github.com/manjaro/packages-community/commit/557f639105e135bc6b9a1d09821d3dc7bf8d781c

**Comment by oberon2007** [comment]
Thanks!
Yeah, Linuxmint now has this procedure with all its packages. They have these in between 'unstable' releases and then sometimes a proper stable release like for instance [Cinnamon](https://github.com/linuxmint/Cinnamon/releases) just now.
It can be useful maybe sometimes if you need a current fix to use one of these snapshots, like I just did for example with [pix](https://github.com/manjaro/packages-community/commit/82ffeb96a99442cd7ab0539ae7d7b4d556af5d19), where we now currently have version **1.6.2+master.mint19-1**
Maybe not so beautiful, but I think it should be visible in pkgrel that it's not a regular release ... :grin:
