### ISSUE TITLE
palemoon 25-7-2

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#49]
Someone one the German forum pointed out that palemoon-bin 25-7-2 has been available in the AUR for a while now. No idea how urgent it is to adopt the update but just wanted to let you know.

**Comment by philmmanjaro** [comment]
Well, this package is now at version **25.7.3** ...

**Comment by korrode** [comment]
I'll get back on the ball with Pale Moon updates soon, just right now my Manjaro system isn't even plugged into a normal monitor and doesn't have a normal keyboard and mouse plugged into it (but will be back up and running as normal in a couple weeks or so).

Anyone who is so inclined, feel free to update the Pale Moon packages whenever needed.

A few notes:

1. Our palemoon-bin package source is exactly the same as the AUR package and should remain as such unless there's a good reason to deviate.
2. I have in the past preempted the palemoon-bin update ahead of the AUR maintainer when i'm confident it's just going to be a pkgver and checksum bump, so feel free to update it even if the AUR maintainer hasn't gotten around to it yet, but when they do finally update confirm that the changes to the package source were just pkgver and checksum bumps. If there were other changes, bring them over.
3. I am the maintainer of the palemoon-atom-bin package on AUR, if anyone wants co-maintainership, just post me your AUR username. Oberon i already added you.
4. These -bin packages use precompiled binaries provided by upstream, there is no point or need to build them with manjaro-tools / in a chroot.

**Comment by oberon2007** [comment]
Thank you, Rob! :)
