### ISSUE TITLE
Catfish icon in deepin can scarcely be seen

### ISSUE THREAD

**Issue by sgse** [manjaro/packages-community#493]
Hello,
hope I'm right here ;-)

![deepinbildschirmfoto_bereich auswahlen_20180503163731](https://user-images.githubusercontent.com/17575778/39593316-b303db44-4f09-11e8-9fa6-6840b29c69a9.png)
Created one for me that everyone could use if need be.
![deepinbildschirmfoto_bereich auswahlen_20180503180140](https://user-images.githubusercontent.com/17575778/39593409-f152de5e-4f09-11e8-8df9-bf21377338e3.png)

[catfish.svg.zip](https://github.com/manjaro/packages-community/files/1972026/catfish.svg.zip)
https://forum.manjaro.org/t/deepin-catfish-logo-zu-blass-dunkel-im-starter/46377/11

regards
SGS aka sgse :-)

**Comment by sgse** [comment]
Wrong place, sorry.

**Comment by oberon2007** [comment]
No problem! I know it's a little confusing... :wink:
