### ISSUE TITLE
firefox-firetray-appind & thunderbird-firetray-appid are now renamed to firefox-firetray & thunderbird-firetray.. 0.5.4 release is out which merges the appind branch into master.

### ISSUE THREAD

**Issue by anexation** [manjaro/packages-community#5]
firefox-firetray-appind & thunderbird-firetray-appid are now renamed to firefox-firetray & thunderbird-firetray.. 0.5.4 release is out which merges the appind branch into master. They need to be rebuilt please..

https://github.com/manjaro/packages-community/blob/master/firefox-firetray/PKGBUILD
https://github.com/manjaro/packages-community/blob/master/thunderbird-firetray/PKGBUILD

**Comment by Kirek** [comment]
Done
