### ISSUE TITLE
alpm-octopi-utils: installing pacman (5.1.0-1) breaks dependency 'pacman<5.1'

### ISSUE THREAD

**Issue by notuxius** [manjaro/packages-community#502]
Unstable repos

**Comment by DewaldDeJager** [comment]
I am also experiencing this issue.

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/packages-community/commit/9b69b357916e85855dc55015661e18047395688b#diff-8e30a713e5b48461d68f1d2e275604c0
