### ISSUE TITLE
hyper 2.0 glitchy

### ISSUE THREAD

**Issue by codesardine** [manjaro/packages-community#505]
this version of hyper seems to flicker, not sure if is my graphics card, but previous versions where working well, maybe build another canary version,  anyone else have issues?

**Comment by codesardine** [comment]
sending a ping about this @jonathonf @Ste74 since you guys modified the pkgbuild.

 I am assuming it just needs a rebuild to pick up the new canary version, if not i will do the required changes myself, let me know if anything needs to be done?

**Comment by Ste74** [comment]
Create a PR if you want update hyper to a canary version but remember this:
```
╭─ stefano@manjaro   ~  
╰─ vercmp 2.1.0 2.1.0canary.2                              ✔  565  19:15:05 
1
╭─ stefano@manjaro   ~  
╰─                                                         ✔  566  19:16:54 

```
so correct the pkgver with `2.1.0canary.2`

**Comment by codesardine** [comment]
will test next version to see if it has same issue, not sure what vercmp means, what do you advise?

**Comment by Ste74** [comment]
[vercmp ](https://www.archlinux.org/pacman/vercmp.8.html) is a command line to see if pkgver is ok. In this case if you modify the pkgver as i suggest we don't need in the future the `epoch` array.. :wink:
