### ISSUE TITLE
ttf-nerd-fonts-symbols package cannot be installed: unknown trust pgp key.

### ISSUE THREAD

**Issue by FredBezies** [manjaro/packages-community#509]
Step to reproduce:

1. Open a terminal or pamac
2. Try to add ttf-nerd-fonts-symbols
3. Wait and see installation failing.

@Chrysostomus: looks like there is a problem with your key :(

```
sudo pacman -S ttf-nerd-fonts-symbols
resolving dependencies...
looking for conflicting packages...

Packages (1) ttf-nerd-fonts-symbols-2.0.0-2

Total Installed Size:  0,89 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
error: ttf-nerd-fonts-symbols: signature from "Matti Hyttinen <matti@manjaro.org>" is unknown trust
:: File /var/cache/pacman/pkg/ttf-nerd-fonts-symbols-2.0.0-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
```

**Comment by oberon-manjaro** [comment]
Matti's key has expired and seems he is not available right now. I will re-package this for now.
Most of his packages are quite specifically for the awesome and bspwm editions.

**Comment by FredBezies** [comment]
@oberon-manjaro It is the case. And it hurts. I sent a message via manjaro.org forum to warn him about this problem.

Wait and see :D

**Comment by FredBezies** [comment]
Thanks for the fix.

**Comment by GLock-PPC** [comment]
Still showing as expired...

**Comment by philmmanjaro** [comment]
fixed via: https://gitlab.manjaro.org/packages/core/manjaro-keyring/commit/d82274fe5d203f36260d2061f1f0dd188e32f931

**Comment by oberon-manjaro** [comment]
In fact Matti's key has already been updated ...
https://pgp.mit.edu/pks/lookup?op=vindex&search=0x8238651DDF5E0594
