### ISSUE TITLE
new pkg rootmenu file conflicts

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#51]
@Chrysostomus, well this is not so trivial, because people who already have *bspwm-scripts* installed and want to install *rootmenu* now will run into this problem:
```
error: failed to commit transaction (conflicting files)
rootmenu: /usr/bin/BspwmDesktopMenu exists in filesystem
rootmenu: /usr/bin/BspwmWindowMenu exists in filesystem
rootmenu: /usr/bin/bspwm-menu exists in filesystem
rootmenu: /usr/bin/dlogoutmenu exists in filesystem
```
This needs to be sorted with conflicts/replaces/provides ... something - I'm too tired tonight to still be able to think straight ;)
Lets sort this out tomorrow.
Maybe some of the experienced here have the right idea meanwhile :)
Good night!

**Comment by Chrysostomus** [comment]
I have no experience, but...
Rootmenu now provides those files and they have been removed from lemonpanel and bspwm-scripts. So I think we could bump their version and make rootmenu conflict with their earlier versions. We could temporarily add rm /usr/bin/{files} to package function of rootmenu as first item so it clears the way for itself, perhaps preceded by if statement to check if they exist to avoid errors. I think that could solve the issue even without the first option. 

I think most people would now get it during update pulled as depency of bspwm-scripts. I think that is the primary scenario we need to concern with, since partial upgrades are not supported (but people do it anyway... yeah,that needs ro be taken into account too)

**Comment by philmmanjaro** [comment]
If the other packages don't have those anymore, they all needed to been bumped and all is fine. Bernhard now knows what to do, hopefully ;)

**Comment by Chrysostomus** [comment]
Cool, I originally thought that might work so. Forgot to bump the versions though (difficult to do on lecture with smartphone).

**Comment by oberon2007** [comment]
Ok. Lets try that then. I was just confused because of the conflict errors I kept getting in the chroot when building the new packages. But of course the updated dependencies could not have been available there, yet ;)
Maybe @Chrysostomus you'd like to verify what really happens on a system with the old versions installed. In the worst case people would just have to rm bspwm-scripts first an then install rootmenu. Or maybe depends with version numbers would make it smoother.

**Comment by Chrysostomus** [comment]
Ok, I'll try when I have chance.

**Comment by Chrysostomus** [comment]
Just to make: installing packages genersted with makepkg from new pgkbuilds on live system after pacmsn -Syu is sufficient test? The live enviroment has old version of lemonpanel and bspwm-scripts installed.

**Comment by oberon2007** [comment]
Just a normal system update would be interesting, since **rootmenu** is a dependency of bspwm-scripts now anyway. I think it should not be a problem...

**Comment by Chrysostomus** [comment]
Aah, so it is already in repos?

**Comment by oberon2007** [comment]
yes. you will just have to do it in unstable.

**Comment by Chrysostomus** [comment]
Whoops, good that I checked! I thought that I had deleted dboxmenu and dboxrun from bspwm-scripts, but I had forgotten. Otherwise updates cleanly. I now made the change, if you rebuild bspwm-scripts it should work flawlessly.

**Comment by Chrysostomus** [comment]
Also, I found an issue with panels that needs fixing. I'll do it in a minute...

**Comment by oberon2007** [comment]
ah. pff. just pushed the updated pkg ;) Can do it again in the evening ...

**Comment by Chrysostomus** [comment]
Update is done. Rootmenu needs rebuilding also, I fixed the browser item in menus

**Comment by philmmanjaro** [comment]
You guys are fast. @Chrysostomus if you like we can teach you on how to publish your packages on your own terms. I think with time you get it. It is up to you on how brave you are ;)

**Comment by oberon2007** [comment]
Sure, of course you can do it! :)
The two pkgs are done anyway :)

**Comment by Chrysostomus** [comment]
Well it would be neat and would cause less extra work for you (mainly oberon). But I'd still like to run things by you sometimes, so that I don't mess up things. I should probably start reading about boxit (https://forum.manjaro.org/index.php?topic=18773.0) and signing packages then?

**Comment by oberon2007** [comment]
No problem at all for me, really! Just take your time and familiarize yourself with everything.
