### ISSUE TITLE
Budgie-Desktop broken

### ISSUE THREAD

**Issue by Ste74** [manjaro/packages-community#52]
Hi guys , yesterday the budgie desktop packages is broken , i try to recompile our pkg to build with new gtk 3.18 but not finish the compiling , now try with version from git and it work , i search the difference in wm ( is this broken) but not found ... Rebuild and installed in pc .. is possible to change pkgbuild from git ? 

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=budgie-desktop-git

**Comment by oberon2007** [comment]
you mean, just use the git version instead? sure. i can do that.

**Comment by Ste74** [comment]
Have via G+ talk with ikey ( founder of solus ) i ask him to relaese another stage like v8.3 ..

**Comment by oberon2007** [comment]
https://github.com/manjaro/packages-community/commit/680bae74f8fb02c574a8e0f5b44b4dd16cf29117
