### ISSUE TITLE
deepin-gettext-tools

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#57]
I have added **deepin-gettext-tools** to community because I need it as a makedepends for other deepin pkgs. I see now that it exists also as an arch-pkg. When I remove the overlay pkg now, will the arch-community pkg become available automatically or @philmmanjaro do you have to explicitly "pluck" it from there?

**Comment by philmmanjaro** [comment]
We have it since ages already in our pool/sync folder. Simply remove your overlay package:
http://repo.manjaro.org.uk/pool/sync/deepin-gettext-tools-1.0.1-1-any.pkg.tar.xz

**Comment by oberon2007** [comment]
ok. i must have missed that :) thanks.
