### ISSUE TITLE
Shared library error with command-not-found

### ISSUE THREAD

**Issue by jlmenut** [manjaro/packages-community#62]
hello,

I have this error message when I try to run cnf-lookup or cnf-populate. 

```
cnf-lookup: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory
```

I've checked and I have libboost_system.so in /usr/lib

**Comment by philmmanjaro** [comment]
**command-not-found** is an **AUR** package. We don't support this. Please recompile against the new boost library on your own.

**Comment by jlmenut** [comment]
What ? command-not-found is in this very same repository

**Comment by oberon2007** [comment]
Yes, it's a package we have adopted for the bspwm-edition. I have just rebuilt it and pushed version **0.4.5-3** to unstable.

**Comment by philmmanjaro** [comment]
Sorry, then I missed that.

**Comment by Darkhogg** [comment]
This is happening **again**, and it's been like this for a few months now:

    cnf-lookup: error while loading shared libraries: libboost_system.so.1.59.0: cannot open shared object file: No such file or directory

**Comment by oberon2007** [comment]
@Chrysostomus The latest release of this is ancient! Does anything contradict switching to git?

**Comment by Chrysostomus** [comment]
Last git commit is 1 year old. I think we should drop this entirely. The compiled version has been iffy in its workings from the start, even when aur version has worked. It seems that this does not wirk properly if you dont compile it yourself. 

I hope we get pkgfile back someday. This is really just a workaround to make up for lack of pkgfile.

**Comment by Darkhogg** [comment]
Once again:

    cnf-lookup: error while loading shared libraries: libboost_system.so.1.60.0: cannot open shared object file: No such file or directory

If this package is not going to be recompiled when boost updates, it should be removed.

**Comment by philmmanjaro** [comment]
@Darkhogg: you're so yesterday ;) 6aae2fba3f9e1a3d18e1155e7cbc663c1d9f3d32

**Comment by Darkhogg** [comment]
Yeah, I was about to remove that comment, I *just* saw the update. Oops!
