### ISSUE TITLE
dkms creates weird spl/zfs compile issues

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-community#69]
During Linux 4.4 extramodules compiling I found following issue with dkms: https://github.com/zfsonlinux/zfs/issues/4054. I've currently downgraded dkms on our end to the last working 2.2.0.3-16 until I find the issue with Arch's current community package.

**Comment by dszryan** [comment]
hi... any updates regarding this
issue still persists with:
  Linux media 4.4.13-1-MANJARO #1 SMP PREEMPT Wed Jun 8 09:21:59 UTC 2016 x86_64 GNU/Linux

+RD

**Comment by philmmanjaro** [comment]
Well we have the issue tracked also here: https://github.com/manjaro/packages-extra/issues/57 Since we don't use dkms anymore for Manjaro it is solved at least for us.
