### ISSUE TITLE
can someone help with [espeak] please!?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-community#85]
```
cd dictsource && ESPEAK_DATA_PATH=/build/espeak/src/espeak-1.48.15 LD_LIBRARY_PATH=../src: ../src/espeak --compile=af && cd ..
Can't read data file: '/build/espeak/src/espeak-1.48.15/espeak-data/phontab'
Failed to load espeak-data
Makefile:2666: recipe for target 'espeak-data/af_dict' failed
make[1]: *** [espeak-data/af_dict] Error 1
make[1]: Leaving directory '/build/espeak/src/espeak-1.48.15'
Makefile:597: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by philmmanjaro** [comment]
Why is **espeak** on your list? Arch didn't rebuilt it ...

**Comment by coffeeking** [comment]
hi
I used to get that error all the time when trying to build from reece's
repository. I emailed him about it and all I got was, oh it must be
something with your build environment, it works hear. I was wondering
how burnhard got around it.
Thanks
Kendell clark

**Comment by philmmanjaro** [comment]
latest git code gave me:
```
Compiling: 'lfn_rules'
/bin/sh: line 1: 29527 Segmentation fault      (core dumped) ESPEAK_DATA_PATH=/build/espeak/src/espeak-1.48.15 LD_LIBRARY_PATH=../src: ../src/espeak --compile=hu
```

**Comment by oberon2007** [comment]
1. It is on my list likely because we use a newer version than arch. I installed it an ran our check scripts and it got listed
2. My PKGBUILD used to work last time... :-/

**Comment by philmmanjaro** [comment]
Hmm, some random shit is going on ...

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/packages-community/commit/8818900d0c9bcfc20e2e123c00a54e36e1bfa0ec
