### ISSUE TITLE
compiz v0.8 packages are needing a C++11 ABI rebuild

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/packages-community#88]
Seems the older **compiz** series is broken due the **C++11 ABI bump**:
```
compiz (core) - Error: Couldn't load plugin '/usr/lib/compiz/libccp.so' : /usr/lib/libcompizconfig.so.0: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv
compiz (core) - Error: Couldn't load plugin 'ccp'
```

We either fix those packages or remove them.

**Comment by Kirek** [comment]
I will rename with the same name as the packages from aur, so we can drop them eventually...

**Comment by philmmanjaro** [comment]
Great idea.

**Comment by phantom009** [comment]
Downgrading the protobuf package (one of the compiz dependencies) to the one prior to the update solves the problem. Maybe the problem lies there vs in compiz itself?

**Comment by Kirek** [comment]
No, downgrading protobuf fixes the problem because it uses the old ABI (so compiz old abi, protobuf old abi, no problem). But the newer protobuf uses the new abi so its causes problems whne something else compiled with the old abi wants to use it.

**Comment by Kirek** [comment]
Obviously a package cannot be replaced for the package that it has replaced, so to go back to the aur names is not trivial. I'm just removing them, too much time wasted on this.

**Comment by philmmanjaro** [comment]
Ah ok. Fine with me.
