### ISSUE TITLE
Tox package uses deprecated client

### ISSUE THREAD

**Issue by TheLastProject** [manjaro/packages-community#9]
The client in the Tox package, ProjectTox-Qt-GUI, has been deprecated for ages. Please switch to uTox or qTox, or remove it altogether ("stable" packages of alpha rolling-release software that hasn't had a single release yet is silly).

**Comment by Kirek** [comment]
I agree, removed.
https://github.com/manjaro/packages-community/commit/f0c6a1de9ff3689d0df0e49efa42451fc47c418c
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20150413/003064.html
