### ISSUE TITLE
qpdfview --> texlive-bin depend

### ISSUE THREAD

**Issue by udeved** [manjaro/packages-community#90]
Is there a way to make textlive-bin depend optional?

Its 50MB extra and it makes it eventualy lose to okular.

**Comment by udeved** [comment]
Should I build it and push to 3 branches?
Reduces iso size about 50MB

**Comment by philmmanjaro** [comment]
I don't had time to build it yet. If needed barley, then build it.

**Comment by udeved** [comment]
I put it in unstable, but I wanted to test before moving to testing and stable.

**Comment by philmmanjaro** [comment]
woops, just snapped it over ...

**Comment by udeved** [comment]
Doesn't matter, I was just thinking perhaps it needs a make flag too or something.

**Comment by philmmanjaro** [comment]
What do you mean? So it is broken without **textlive-bin** as of now?

**Comment by udeved** [comment]
I dunno yet, unstable iso just finished, but my bet is on its fine.

**Comment by philmmanjaro** [comment]
Ok, keep me updated ...

**Comment by udeved** [comment]
Looks good.

**Comment by udeved** [comment]
~~~
[manjaro@manjaro-openrc ~]$ qpdfview /mnt/HOME/eugen/Dokumente/BSI Schutzprofil/SmartMeter/06910301.pdf
qpdfview: error while loading shared libraries: libsynctex.so.1: cannot open shared object file: No such file or directory
~~~

**Comment by philmmanjaro** [comment]
Install **texlive-bin** to fix the issue ... Seems we have to revert it ...

**Comment by philmmanjaro** [comment]
Seems to be related to this one here: https://bugs.launchpad.net/qpdfview/+bug/1338797

**Comment by udeved** [comment]
This is very ugly, texlive-bin is big package, why the hell don't arch split out the shared lib then?

**Comment by udeved** [comment]
~~~
[manjaro@manjaro-openrc ~]$ sudo pacman -S texlive-bin
Löse Abhängigkeiten auf...
Suche nach in Konflikt stehenden Paketen...

Pakete (8) gd-2.1.1-3  libpaper-1.1.24-9  libsigsegv-2.10-2  libvpx-1.5.0-3
           potrace-1.12-1  t1lib-5.1.2-5  zziplib-0.13.62-2  texlive-bin-2015.37497-9

Gesamtgröße des Downloads:                25,63 MiB
Gesamtgröße der zu installierenden Pakete:  63,82 MiB

:: Installation fortsetzen? [J/n
~~~

63MB extra renders qpdfview useless for small iso profiles.
I need to test if okular(iirc still not fully kf5 ported) takes less space.

**Comment by philmmanjaro** [comment]
Did you actually tested the last instance of this package yet?

**Comment by udeved** [comment]
I thought I tested it, but it escaped me, that the build still pulled previous version.

**Comment by udeved** [comment]
Pretty "scary" when looking at texlive-bin PKGBUILD....

~~~
 echo "-------------------------------------------------------"
   echo "--> Building the whole beast ..."
   echo "-------------------------------------------------------"
~~~

**Comment by philmmanjaro** [comment]
What is the issue now? Revision 3 doesn't use **textlive-bin** at all ...

**Comment by udeved** [comment]
My crystal ball didn't tell about rev 3 yet.
It uses internal libsynctex I guess?

**Comment by philmmanjaro** [comment]
Yes, correct. It should be already online on netzspielplatz [unstable] ...

**Comment by udeved** [comment]
Great, works now.
Should be in stable too, and I can rebuild 15.12 and update remote iso.

**Comment by philmmanjaro** [comment]
Done, up in five ...

**Comment by udeved** [comment]
Despite this, its good case to test out deployiso in full.

**Comment by philmmanjaro** [comment]
Still had no time to do so ...

**Comment by udeved** [comment]
Worked great for me last night.
started upload with 80k, went to bed, pc suspended.
Picked up upload for the missing 50MB.
Now I am gonna update remote, should be quick.
